### ISSUE TITLE
remove prepareException method in Exceptions\Handler

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/internals#1020]
In L5.6 (and in previous releses) standard ExceptionHandler uses a prepareException to encapsulate current exception in some other Exception class:

```php
    protected function prepareException(Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        } elseif ($e instanceof AuthorizationException) {
            $e = new AccessDeniedHttpException($e->getMessage(), $e);
        } elseif ($e instanceof TokenMismatchException) {
            $e = new HttpException(419, $e->getMessage(), $e);
        }

        return $e;
    }
```

Why is this method needed? Why can't `ModelNotFoundException`, `AuthorizationException` and `TokenMismatchException` extend their relative exception classes? There is any reason?

```php
class TokenMismatchException extends Exception
{
}
```

```php
class ModelNotFoundException extends RuntimeException
{
    [....]   
}
```

```php
class TokenMismatchException extends Exception
{
}
```

**Comment by sisve** [comment]
A ModelNotFoundException is exactly that, a model-not-found exception. It's not a http exception that can properly be represented as a http status code as-is. The error could even be thrown during an artisan command where there is no http context to talk of.

Another argument would be that a try/catch that catches HttpException should not catch ModelNotFoundException since that isn't http related.

It's the exception handlers duty to handle the exception in any necessary manner. The prepareException method could be renamed into wrapExceptionInWhateverOtherExceptionClassThatIsSuitableForWebRendering, but in the end, all it is meant for is wrapping/replacing exceptions with other exceptions that are more suitable for rendering for the web.

**Comment by alberto-bottarini** [comment]
It makes sense. Thank you
