### ISSUE TITLE
The framework design is deeply violating "Tell don't ask" or "Law of demeter" principle

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/internals#1027]
I know many people do not accept this but that does not prevent me write it here.

If we start at `public/index.php` and read through the request/response life cycle of the laravel framework
we can clearly see that it is deeply nested calls are asking objects for a "Response" object which are eventually sent to the user like this:

```php
 $response->send();
```

And that is killing me,ask ask ask
It is not telling them to send the response.

I my self by pass all these by have a helper function like below.

```php
function sendAndExit($response)
{
    $request = app('request');
    // send the response to the users browser
    app('router')->prepareResponse($request, $response)->send();
    // dispatches an event
    app('events')->dispatch(new \Illuminate\Foundation\Http\Events\RequestHandled($request, $response));
    // this is just needed when we have terminable middlewares in our app.
    app(\Illuminate\Contracts\Http\Kernel::class)->terminate($request, $response);
    exit;
}

```

and use it like this:
```php
    $response = response()->json('You should be logged in');
    sendAndExit($response);
```

I do not expect the whole framework design to be revolutionized for the next version.
But I see this wrong design decision root years before the laravel was even invented and it is still plagues many modern frameworks today.

===============

Pardon me if my opinion is against many MVC guys that says: 
```Controllers Should Return A Response```

After years of working like this now I see that It is an old and terrible idea.
I do not know who has decided to start writing an MVC framework many years ago using this wrong idea but I hope he pardons me, because I think his wrong idea is now everywhere.

**Comment by JeffreyWay** [comment]
lol

**Comment by sisve** [comment]
class ExampleController extends Controller {
        public function exampleAction() {
            return new JsonResponse('You should be logged in');
        }
    }

Using this as an example, I can easily write a test for this.

    $controller = new ExampleController();
    $response = $controller->exampleAction();
    // assertions goes here.

Let's look at your sendAndExit method...

    $request = app('request');

So, you have to have a working container and resolve a working Request instance. Okay, I guess we could accept that. It's not too extreme.

    app('router')->prepareResponse($request, $response)->send();

Okay, so you must have a router setup too. And that prepareResponse will modify the response, so it's hard to test the actual response that the action returns.

    app('events')->dispatch(new \Illuminate\Foundation\Http\Events\RequestHandled($request, $response));

Okay, so I also need an event dispatching system active just to test my action.

    app(\Illuminate\Contracts\Http\Kernel::class)->terminate($request, $response);

Wait, we're executing the terminable middlewares? When did we invoke them in my test to begin with? Their handle() method was never executed!

    exit;

Okay, we're giving up here. There's no way you've even considered testing when suggesting this.

> Tell-Don't-Ask is a principle that helps people remember that object-orientation is about bundling data with the functions that operate on that data. It reminds us that rather than asking an object for data and acting on that data, we should instead tell an object what to do. This encourages to move behavior into an object to go with the data.

Source: https://martinfowler.com/bliki/TellDontAsk.html

The Tell, Dont Ask principle is about bundling your functions with the data. You've misunderstood this principle. It's about having `$request->method()` instead of having a `$requestDataReader->readMethodFrom($requestData)`.

> The Law of Demeter (LoD) or principle of least knowledge is a design guideline for developing software, [...]
> The fundamental notion is that a given object should assume as little as possible about the structure or properties of anything else (including its subcomponents), in accordance with the principle of "information hiding". It may be viewed as a corollary to the principle of least privilege, which dictates that a module possess only the information and resources necessary for its legitimate purpose.

Source: https://en.wikipedia.org/wiki/Law_of_Demeter

You're example code would have my action talk to the ioc container, the router, the event dispatching system and all the middlewares. Clearly your example is breaking the Law of Demeter.

**Comment by taylorotwell** [comment]
Hey @imanghafoori1, thanks for your post. I think one problem is you need to frame it in terms of actual applications maintainability, testing, etc. Right now, you're just saying "something is wrong because it breaks this rule". You need to define exactly what changes you would make and how it would improve things **for end users**. That is what matters. How would it make their applications more maintainable? More testable? More understandable?
