### ISSUE TITLE
TokenGuard's tokens are stored in cleartext

### ISSUE THREAD

**Issue by piperone** [laravel/internals#125]
Storing passwords in cleartext is viewed as a big no-no in our line of work. I would imagine that the same arguments apply to storing tokens that can be used to authenticate as a user the same way a password can. 

Given this, I don't understand why Laravel's TokenGuard does not hash the api_token it uses to authenticate users but instead stores it in cleartext. I'm not at all comfortable with storing what essentially is a password without it being hashed and salted first. 

Can anybody shed some light on this?

**Comment by michaeldyrynda** [comment]
I recently came across this issue in implementing the functionality in Laravel 5.1 - the problem I couldn't come up with a good way of resolving was once the token is salted and hashed, you've no way of looking it up again and matching it against the clear text token being sent to the app.

Salted and hashed strings work for passwords because you have the username to match against, you need some piece of information the user can pass in clear text, and use the token as a password. I ended up just prefixing it with the user id - `<id>:<random_string>` and storing the salted and hashed `<random_string>` in the database, using the ID to find it, then doing a hash check.

I think, however, that the simple token being stored as plain text isn't too bad, as long as you provide an easy way to delete / invalidate them.

That said, if anybody has a better solution to this than my implementation, I'm all ears. It feels hacky.

**Comment by Garbee** [comment]
These are also long and randomized tokens, so brute-forcing these to access an account would take an extremely long time.

If your DB is breached here, you just invalidate the tokens just like passwords. Meanwhile, since the user didn't create these tokens and they are one-way their private information isn't at risk.

This is a matter of, private user data should be hashed. A token is a *secret produced by the server only for the servers use*, which doesn't meet the same bar as needing to be hashed. If a user loses their key, it is just like them losing their password on their own accord. If the server loses it, well, you still handle it just like a password. Invalidate immediately and force people to refresh their stuff.

**Comment by malhal** [comment]
This is an important discussion because the token in the user table certainly looks like the keys to the kingdom. I read somewhere else someone was considering regenerating the token after every request, however I would imagine that is high risk if the response doesn't make it through e.g. on an unreliable network connection.

When I implemented this before Laravel added the Token guard, I simply used the session key as the token, that has the added benefit that users can be logged in on multiple devices and invalidating the token on logout without affecting the other devices, with a database session driver it meant it was persisted too. I'd imagine down the line people will start to being to develop for tokens per device, at which point they will be pretty much reimplementing the session key feature. The session also has some kind of encryption on it too.

**Comment by Garbee** [comment]
> This is an important discussion because the token in the user table certainly looks like the keys to the kingdom.

How would an attacker gain access to said user table? In what way is it being stored in plain-text a vulnerability when your application/server is already hacked into and they have direct access to your database?

**Comment by malhal** [comment]
I suppose programmer error could lead to them being leaked, the api_token isn't included in the hidden array in the default User model, so any feature that is sharing user information could accidentally expose it, e.g. user that created a post. Also the field isn't part of the default migration so too short Varchar could be used, similarly the token generation is not provided so that could be another weakness. Furthermore the built in Auth controllers don't work from the new api routes (because they use sessions and redirects), so if a user implements those and neglects to implement any throttling that could lead to brute force attacks. The token should probably expire and be refreshed at some point with a new login, that would be a lot of extra work to get right. Maybe the feature just needs to come with a health warning.

**Comment by Garbee** [comment]
> I suppose programmer error could lead to them being leaked

Programmer error can lead to anything being leaked, including plain-text passwords. I don't see a need for the tokens to be hashed by default still, even with all the other things pointed out.

What I'm seeing is, we should be clear to developers to treat tokens as if they were passwords and guard them within the application from accidental leakage. But, actually hashing them provides no real benefit over storing as plain-text for easy comparison.

**Comment by michaeldyrynda** [comment]
One of the issues with hashing a server-generated token is matching them up with the user making a request. The user sends you the plain text token, which you have to somehow with a database record, which is hashed.

Hashing of passwords works because the user has something to identify themselves (email). We look up the record in the database for the email address and compare the stored hash with the computed hash of the password they supply.

This isn't going to work with bearer tokens unless you require the consumer to also send an email address or username in the request. For a sufficiently long and randomly generated token string, I don't think hashing the token is necessary.

**Comment by taylorotwell** [comment]
I'm open to PRs on this issue.
