### ISSUE TITLE
Need a clean way to change resource route URLs without changing the route names

### ISSUE THREAD

**Issue by nhowell** [laravel/internals#130]
Let's say I have this existing route.

```
Route::resource('photos', 'PhotoController');
```

And later on it is decided to change the URL for photos from `/photos` to `/images`. I would have expected the following code to allow me to change the URL for the resource but retain the route names so I don't need to change them everywhere they are used in the app.

```
Route::resource('images', 'PhotoController', ['as' => 'photos']);
```

However, instead of replacing the route basename, it is prefixing `photos.` to the route names. So you end up with route names like `photos.images.index` instead of the expected, and I would argue more useful, `photos.index`.

Why is the current behavior to prefix when you can achieve that with a `Route::group()`.

I'm aware of the `names` option that you can pass to `Route::resource()`, but it is quite tedious to rename every route in the resource.

I'm willing to make a PR for 5.3 (since this would be a BC) if approved. I'm open to other solutions, as well.

**Comment by Garbee** [comment]
Check the `Naming Resource Routes` section in [the docs](https://laravel.com/docs/5.2/controllers#restful-naming-resource-route-parameters). Just set the resources to the existing names and modify away.

**Comment by nhowell** [comment]
@Garbee As I said, I'm aware of the ```names``` option. It, however, requires you to rename every single route in the resource to achieve the desired effect.

**Comment by Garbee** [comment]
I don't think doing a BC break on this is appropriate personally. If developers have a large route file already dependent on the current behavior then it would be a major upgrade pain for them. There must be a non-BC break that can be made to make this easier since you don't want to list out every individual name. Or you could just make a custom method/function to handle generating the array for you, that shouldn't be too difficult for people to implement in their own projects as-needed instead of including even more within the Laravel core.

**Comment by nhowell** [comment]
If a BC break is unacceptable, the functionality could be added to with new option.

For example:
```
Route::resource('images', 'PhotoController', ['basename' => 'photos']);
```

Anyway, I assume this is a common problem for other developers, too. I think it should have an official way of being handled nicely.
