### ISSUE TITLE
Now that events, jobs, listeners and policies directories are gone by default, should the generators default location be app/ (like the model generator)?

### ISSUE THREAD

**Issue by philbates** [laravel/internals#147]
Removing these directories gives the developer freedom to put their events, jobs etc in exactly the directory structure they want. It seems a little strange that `make:event FooEvent` would place the new event in `app/Events/FooEvent.php` - wouldn't it be more consistent to place it at `app/FooEvent.php`? If the developer still wants a models directory, they would just type `make:model Events/FooEvent`.

Thoughts? Was this done purely for backwards compatibility?

**Comment by JosephSilber** [comment]
That would be horrible!

The directories are gone so that if you don't use them they shouldn't clutter up you project. But you still want them organized when you do use them.

BTW, all generators allow you to pass it a path, so you've still got all the flexibility you need.

**Comment by philbates35** [comment]
> The directories are gone so that if you don't use them they shouldn't clutter up you project. But you still want them organized when you do use them.

Not necessarily, you might want to group things into domain/feature rather than by type. Like you say, it is possible to pass a different path to the generators so it's not really a big deal to continue to do that. That said, in my opinion it would be fine to just place everything in the project root and really leave it up to the developer where to put it.

**Comment by tomschlick** [comment]
More and more I keep thinking maybe having an artisan config file with all the paths and default options for the generators would be a good idea. That way if you want events placed in the root or in a random obscure folder it wouldn't be a problem, just se your config and the next time you generate it will be placed there by default.

**Comment by drbyte** [comment]
> @tomschlick More and more I keep thinking maybe having an artisan config file with all the paths and default options for the generators would be a good idea. That way if you want events placed in the root or in a random obscure folder it wouldn't be a problem, just se your config and the next time you generate it will be placed there by default.

I was thinking similarly.

**Comment by jlaswell** [comment]
Taking the approach of using an optional dotfile would keep it out of the
way for most who prefer defaults.

**Comment by Garbee** [comment]
The paths should  be auto-created once you use a generation command. They just aren't there if you never use them.

**Comment by legshooter** [comment]
Like mentioned by others, the dirs are gone because they hold no files to begin with.

Generating them in this specific way keeps everything consistent, as other stuff is already grouped by type.

Grouping things by "domain" has always been more logical in my eyes, but I don't get how throwing everything into the same dir by default helps in that sense, it just breaks the aforementioned consistency without any added value.
