### ISSUE TITLE
[Proposal] Make laravel validator less monolithic structure

### ISSUE THREAD

**Issue by Skysplit** [laravel/internals#156]
Currently laravel `Validation` class in my opinion is too monolithic structure.  
This makes it hard to extend/replace single validation rule without replacing `Validator` and `ValidationServiceProvider`.

In my opinion it would be better if validation rules are split into seperate classes that implement `ValidationRule` contract.

I find [Yii2 validation](https://github.com/yiisoft/yii2/blob/b30b5a99ea0a00c0a57839fe88658f0437406dab/framework/validators/Validator.php#L55) class being built in much cleaner way than it currently is in laravel.

**Comment by tomschlick** [comment]
Yeah that would definitely make the validation stuff more modular and maintainable. Great idea for a pull request! Probably wouldn't make it in until 5.4 towards the end of the year but would be a welcome change.

**Comment by Skysplit** [comment]
Also, when it comes down to validation rules, I find passing arrays as rules parameters to be very convenient (again, following Yii2 example).

Moreover I think current `Validation` class behaviour is inconsistent when it comes to usage of `Translation` service.
It uses translator, but it does not pass parameters to it and instead forces user to add replacer.

Again, I find Yii2 validator very good example of flexibility and extensibility.

**Comment by brayniverse** [comment]
@Skysplit, that's an excellent proposal. Looking at Laravel's `Illuminate\Validation\Validator` class, I doubt it'd be too difficult to accomplish either. _Famous last words_.

If you're interested, I'm available to help prepare a PR.

**Comment by brayniverse** [comment]
I've started working on something and I'm seeing some great potential for improving validation. All while maintaining backward compatibility. When I'm finished extracting the existing validators into their own classes, I'll share a few ideas I have. I've completed the basic validators already, but I haven't started on the ones that interact with the database yet; I presume they'll take some time to do. 

Even if my work isn't used, it's fun to experiment.

**Comment by KennedyTedesco** [comment]
Good for a major version (Like Laravel 6 or something) because this change would probably break things.

**Comment by Skysplit** [comment]
@brayniverse I would be extremely thankful for your help :)

Because new will validator breaks backwards compatibility anyway, I'd also consider removing `Validator::replacer()` in favour of passing attributes to translator directly.

[Validator::addError()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L647)

Currently error message is translated in [Validator.php#L1951](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L1951)

And then params are replaced in [Validator.php#2101](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L2101)

Which in my opinion is pretty inconsistent behaviour, as parameters should be replaced by translation component instead.

**Comment by brayniverse** [comment]
I extracted all validators into their own classes. Though, I'm still not satisfied - I'll do some refactoring of my work this evening. All tests still pass which is good.

I am now registering all validators under a `$validators` property on the Validator class. Including extensions, so extensions can now override existing rules. I feel like the `$validators` array should be public, though, maybe in a config file, or a file like `app/Validation/Kernel.php`; with custom validators residing in `app/Validation/Rules`.

All validators follow this format.

```php
class FooValidator extends Validator
{
    /**
     * Validate a given attribute.
     *
     * @param string $attribute
     * @param mixed $value
     * @param mixed $parameters
     * @return bool
     */
    public function validate($attribute, $value, $parameters = null)
    {
        return true;
    }

    /**
     * Get the validation message.
     *
     * @return string
     */
    public function message()
    {
        return $this->getTranslator()->trans('validation.foo'); // could be trans('validation.foo')
    }
}
```

If they interact with the database (exists, unique, etc.), they can use the trait `Illuminate\Validation\Validators\InteractsWithDatabase`.

There's some helpful date related methods when you use the `Illuminate\Validation\Validators\InteractsWithDates` trait.

Each validator returns their own validation message, so you can handle translation in the `message()` method. I haven't implemented this part yet though, it's next on my agenda.

The abstract `Illuminate\Validation\Validators\Validator` class that validators extend needs quite a few values injected into it from the `Illuminate\Validation\Validator` class. An ideal validator would be POPO, which is why I want to refactor my work this evening. 

When I think I've got something worth sharing I'll push up somewhere public to ask for feedback. I'm still experimenting so my approach may change if something better comes up.

**Comment by tomschlick** [comment]
Yeah I would suggest starting a WIP pull request on the laravel/framework repo. That way we can get more visibility and feedback for this. Seems like a good approach overall though 👍

**Comment by garygreen** [comment]
Massive +1 to this. Also it would be nice to have some kind of `RulesCollection()` for each attribute and act on methods like `->merge(['min:3]');` and other stuff. That could potentially reduce the amount of parameters being passed between the validation methods and further split up the validation logic, too.

**Comment by brayniverse** [comment]
I've been a bit busy and fell behind with this. I started from scratch; my first attempt was very destructive - I deleted a lot without thinking. My new approach allows the same result without having to extract any of the internal rules. So you can override framework rules if you need. You can store class based rules in `app/Validation/Rules` and register them in `app/Validation/Kernel`, along with closure based rules.

I think I'm going to split this into two separate PRs. The `app/Validation` directory, service provider, and console make command. Then a second PR proposing the ability to override internal rules. Because the former can merge into 5.3 without breaking changes and the latter may need more consideration. 

Aside from returning error messages from a `message()` method on class based rules, I don't plan on tackling translation or modifying messaging in any way with my PR. If somebody else with more of an idea of what is required wants to address that, they're more than welcome.

I'll reference this issue when submitting my PR either tonight or tomorrow.

**Comment by garygreen** [comment]
@brayniverse isn't the whole point of this suggestion to split up the internal rules? How much does your proposed PR actually simplify things? By the sounds of things it doesn't really split a lot up...

**Comment by brayniverse** [comment]
@garygreen as I see it, the problem is not that the framework's implementation is a monolith - though the title implies it. It is that you cannot easily override internal validators.

> This makes it hard to extend/replace single validation rule without replacing Validator and ValidationServiceProvider.

If the following is possible, I think we solve the problem without a major rewrite.

```php
Validator::extend('required', function ($attribute, $value, $parameters, $validator) {
    // override `required` with custom logic.
});
```

It's quite easy to do so by checking for the extension before trying to call `$this->$method` [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/Validator.php#L525). And if the extension exists, use it instead. No extraction required.

The rest is just a different proposal for keeping validation rules organised; I should probably not have recommended it within this thread because it is unrelated to the initial proposal.

**Comment by garygreen** [comment]
> I should probably not have recommended it within this thread because it is unrelated to the initial proposal.

Yes :wink: what your proposing isn't related to this issue at all. Your just making it easier to override built in validators and not tackling the monolithic problem - which isn't easy to solve without massive breaking changes, probably something fitting for the master branch.

**Comment by garygreen** [comment]
Also, personally I don't like the sound of being able to override built in validators. What if one of your packages decides it'll be nice to override a validator, and your scratching your head wondering why it's not validating as per the docs.

Just create a new rule imo.

**Comment by Skysplit** [comment]
I'm also working on PR and I must say making validator "less monolithic" is much easier to say than to do. There are few problems that have to be resolved. The biggest one is that many rules depend on other rules. This combined with notation like `foo.*.bar.*` makes it difficult to split up rules from `Validator` class.  
 For example:
```php
[
    'foo.*.bar.*' => 'required_if:foo.*.baz.*,value'
]
```

However it is possible to do. However, I'm working on this Validator mostly from scratch and also trying to extend features (I can post some PoC if you want).  
I'm doing my best to keep compatibility with current validator, however I find `Validator::replacer()` making really alot of inconsistency and I think I'll abandon this feature for sake of better params replacement.

**Comment by brayniverse** [comment]
@garygreen haha I hadn't even thought of that. It'd be a real security risk. With that said I don't think I want to allow overriding of rules.

**Comment by garygreen** [comment]
@Skysplit preach brother. It's a massive undertaking but I think it'll be worth it. One thing that would simplify the validator (by my minor messing around, around 500-600 lines split out) just be decoupling how the messages are generated for the failed rules. Take a look at my proposed issue and see what you think #164

**Comment by Skysplit** [comment]
@garygreen I read issue you've created. My work is in really early phase and I'm pretty far from implementing messages and message translations.

However, offtoping here a little bit, I think it is pretty nice idea to translate messages only if they're required/called by MessageBag

**Comment by Skysplit** [comment]
Hi everyone. I Just made PR to laravel's main repo. Please, feel free to review current code, I really appreciate it!

**Comment by abellion** [comment]
Closing such a good PR kills me --'
