### ISSUE TITLE
[Proposal] Allow custom notification type and channel names

### ISSUE THREAD

**Issue by fgambino** [laravel/internals#162]
Currently, all broadcast notifications construct the channel name like this:

```
$class = str_replace('\\', '.', get_class($this->notifiable));

return $class.'.'.$this->notifiable->getKey();
```

It would be great if we could specify a mapping of classes to custom prefixes, or even use the morph map that eloquent already provides.

In addition, the notification `type` column in the database uses the notification's full class name. This becomes a pain to maintain because the notifications can no longer be moved around the application unless a migration is created to update the paths. 

I don't think the `type` column is actually used anywhere to reconstruct the class, so maybe a `type` property can be added to the notification class as an override?

```
public $type = 'invoice-paid';

public function via($notifiable)
{
    return ['broadcast', 'database'];
}
```

**Comment by jlndk** [comment]
Dont we already have the broadcastAs() function?

**Comment by a-komarev** [comment]
@jlndk it works only for Broadcasting Events, not for notifications.

@fgambino you can define event name since [v5.6.4](https://github.com/laravel/framework/releases/tag/v5.6.4) just return custom event name in `broadcastType` method of your notification. It was implemented in PR https://github.com/laravel/framework/pull/23236

This issue could be closed since all the questions which were raised here are solved.
