### ISSUE TITLE
Auto detect available methods on resourceful routes

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#178]
At the moment when you do `Route::resource('users', 'UserController')` it will add all the available resourceful routes.

It would be nice if the controller was inspected to automatically determine what methods are handled, that way you wouldn't need to supply the `except` or `only` options.

This would save on generating routes which don't point to any handlers and cleanup a lot of routing stuff. It's always felt a bit clunky adding `except` and `only` options to your routes file.

**Comment by KKSzymanowski** [comment]
I like this idea very much.
Is it possible to get this functionality mergered? I've seen a lot of "No plans to add this to core" and I don't know if I should work on this if it might get rejected.

**Comment by brayniverse** [comment]
@KKSzymanowski it can be offputting. Nevertheless, as long as you keep it simple, and have a good argument for what you're adding, then it's more likely to be accepted. Don't be discouraged from giving it a go. You could always discuss and plan an implementation here first if you don't want to do any coding yet.

**Comment by garygreen** [comment]
The only thing I would say is I'm not sure how fast the detecting of the available methods will be, as it would have to be done for each request on the fly. Of course the routes would be cached on production so that wouldn't be a problem, but it's just something to keep in mind.

**Comment by garygreen** [comment]
I can see this all be handled by some `ResourceInspector.php` class which will tell you what verbs are for each controller, looking up from cache if available ;)

**Comment by KKSzymanowski** [comment]
I don't think the speed is an issue here, because as you said you would cache routes in production.

As for implementation I don't think a separate class is required.
Inside `ResourceRegistrar::register()` there is a following loop:
```php
foreach ($this->getResourceMethods($defaults, $options) as $m) {
    $this->{'addResource'.ucfirst($m)}($name, $base, $controller, $options);
}
```
which basically registers routes for each resource method.
Inside this loop we could check if the controller has a specific function and if not, `continue` to the next method:
```php
$controllerReflection = new \ReflectionClass($this->getControllerFQCN($controller));

foreach ($this->getResourceMethods($defaults, $options) as $m) {
    if (!$controllerReflection->hasMethod($m)) {
        continue;
    }

    $this->{'addResource'.ucfirst($m)}($name, $base, $controller, $options);
}
```
Implementation details:
```php
/**
 * @return string
 */
protected function getCurrentNamespace()
{
    $options = array_last($this->router->getGroupStack());

    if(!isset($options['namespace'])) {
        return '';
    }

    return $options['namespace'];
}

/**
 * @param  string  $controller
 * @return string
 */
protected function getControllerFQCN($controller)
{
    return $this->getCurrentNamespace() . '\\' . $controller;
}
```

1. The `Router::groupStack` options are merged on every `Router::group` call so if there is a namespace in the top level, it will be present everywhere. However if for some reason user decides to remove the namespace declaration from `RouteServiceProvider`, no `namespace` index will be set - we need to check for that.
2. Fully qualified name is needed for instantiation of `ReflectionClass`.
3. `method_exists` is 2 times faster than instantiation of `ReflectionClass` and calling `hasMethod`, but we would also need to check if the `class_exists` because when no routes would be defined there will be no error saing that it doesn't. ReflectionClass will take care of that for us. Second argument for using `ReflectionClass` is it just looks better. Besides, as we agreed on, speed doesn't really matter at the end of the day and also these reflections are very fast(over 1M calls per second).

What do you think?
@taylorotwell Is this acceptable?

**Comment by michaeldyrynda** [comment]
If you're going to use`Route::resource` the implication would be that you use all the methods. Any time you reach for `with` or`except`, I would generally just define each route explicitly

**Comment by garygreen** [comment]
> If you're going to useRoute::resource the implication would be that you use all the methods. Any time you reach for with orexcept, I would generally just define each route explicitly

So when you handle all the methods but not e.g. `show` your telling me you define all those other routes explicitly? That doesn't sound too pretty to me. There's nothing wrong with doing `['except' => 'show']` but it just seems like extra crud you shouldn't really need to add - the controller could be expected to automatically work out what methods are handled.

**Comment by franzliedke** [comment]
If anything, the automatic detection should be done on another helper method on the `Route` facade IMO. Having the ability to define which routes should be exposed directly in the router is helpful when reusing a controller, where you might want to expose different routes depending on where the controller is re-used.

As long as that functionality stays intact, I have nothing against a new helper method. ;)

**Comment by KKSzymanowski** [comment]
`Route::smartResource`?

**Comment by taylorotwell** [comment]
Would be fairly slow.
