### ISSUE TITLE
[Proposal] Add Illuminate\Auth\Events\Registered event

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/internals#197]
I think it would be very good, if Laravel would ship with an `Illuminate\Auth\Events\Registered` event. It would fit very well with the other Auth events, like login, and lockedout. 

It would be very useful for sending welcoming emails to members who singed in and other related stuff.

**Why add it to the core and not implemented as a user?**
The main benefit of adding it to the framework would be, that packages can rely upon it. 

For example this package: https://github.com/jrean/laravel-user-verification#example needs to ask the user to add 2 traits and some code to the `RegisterController`. 

If there was an event the package could encapsulate all the logic and the user would have an easier time setting it up, as well as upgrading to new Laravel versions (if they require an update to the `RegisterController`).

**Comment by brayniverse** [comment]
I've often wanted this myself. Though I would propose using past tense instead, because it would follow the event naming convention set by the framework.

The convention seems to be either _something is happening_ (e.g. `Attempting`) or _something has happened_ (e.g. `Authenticated`), and in the context of a user has signed up `Registered` makes more sense.

**Comment by lukasoppermann** [comment]
Sure, I only read the login Name, but of course the event should follow the naming convention, I totally agree.

**Comment by brayniverse** [comment]
My PR was merged so we can close this issue whenever you're ready.
