### ISSUE TITLE
Allow generic return type declaration for all responses

### ISSUE THREAD

**Issue by connorjburton** [laravel/internals#210]
Currently there is no way to declare a return type as a response, this is because `Illuminate\Http\Response`, `Illuminate\Http\JsonResponse` and `Illuminate\Http\Response` do not all extend the same class or implement the same interface.

I am trying to achieve

```php
use Illuminate/Http/SomethingThatRepresentsResponse

class Foo {
  function bar(): SomethingThatRepresentsResponse
  {
    return response()->json(['name' => 'Connor', 'state' => 'CA']);
  }
}
```

My proposal is to create an empty interface that all response classes implement, which we would then be able to declare as a return type.

**Comment by tomschlick** [comment]
+1 yes please!

--
Tom Schlick




On Thu, Sep 15, 2016 at 6:40 AM -0400, "Connor Burton" <notifications@github.com> wrote:












Currently there is no way to declare a return type as a response, this is because Illuminate\Http\Response, Illuminate\Http\JsonResponse and Illuminate\Http\Response do not all extend the same class or implement the same interface.



I am trying to achieve

use Illuminate/Http/SomethingThatRepresentsResponse

class Foo {
  function bar(): SomethingThatRepresentsResponse
  {
    return response()->json(['name' => 'Connor', 'state' => 'CA']);
  }
}



My proposal is to create an empty interface that all response classes implement, which we would then be able to declare as a return type.

**Comment by Garbee** [comment]
Remember, Laravel is built on Symfony components. `\Symfony\Component\HttpFoundation\Response` is the class you are looking for.

**Comment by connorjburton** [comment]
Ah, thanks for that @Garbee - solves my issue 👍

**Comment by tomschlick** [comment]
Does RedirectResponse extend that too? I seem to remember some issues with that one previously. Am on mobile or else I would look myself.

**Comment by connorjburton** [comment]
It does, yes. @tomschlick

**Comment by tomschlick** [comment]
Thanks. 

--
Tom Schlick




On Thu, Sep 15, 2016 at 7:31 AM -0400, "Connor Burton" <notifications@github.com> wrote:












It does, yes. @tomschlick

**Comment by Garbee** [comment]
To be sure you always have it work, what I do is this...

1) Inject `Illuminate\Contracts\Routing\ResponseFactory` into `App\Http\Controllers\Controller`.
2) Assign the response factory to the controllers `$response` property.
3) In your controllers, type hint that Symfony class and only use `return $this->response->{json,view,redirect}();` to handle providing responses.

So far it has yet to fail on any response I've needed using this method.

**Comment by connorjburton** [comment]
Type hinting that `Response` class also works well with https://github.com/teepluss/laravel-restable
