### ISSUE TITLE
[5.4] Studly case routing parameters by default

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#213]
At the moment when you register a resource with a dash like:

``` php
Route::resource('news-categories', 'NewsCategoryController');
```

It will register the routes like:

``` php
/news-categories/{news_category}/edit
```

This breaks implicit model binding if your controller parameters are studly case:

``` php
public function edit(NewsCategory $newsCategory)
{
   //
}
```

You would have to change your variable to be `$news_category` for it to work, or manually provide `parameters` as an option to override, or bind the model explicitly through `Route::model()` which defeats the purpose of implicit model binding.

Laravel promotes PSR-2 which means studly case variable names. The proposed solutions are:

1. Change all parameters to be studly-case so implicit model binding works straight out the box. 
2. and/or Support snake case for implicit model binding.

**Comment by bobbybouwmann** [comment]
+1

**Comment by JosephSilber** [comment]
Not that I'm against this, just noting that this has nothing to do with PSR-2.

PSR-2 intentionally says nothing about the casing/dashes of variable names.

**Comment by garygreen** [comment]
@JosephSilber didn't know that, I thought it did have style guidelines on that sort of thing.

**Comment by bobbybouwmann** [comment]
I'm definitely for consistency here in the whole framework, just like we do with relations

**Comment by a-bashtannik** [comment]
+1 for studly case

**Comment by jhoff** [comment]
For what it's worth, I think the reason that many people think PSR-2 has an opinion on properties and variables is because the [PSR-2 Coding Style Guide Additions](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md) recommends it.

Generally speaking, Laravel does seem to prefer studyCase properties and variables for the most part and it seems to me that recent framework changes support that idea.

**Comment by a-bashtannik** [comment]
In any case this behavior (snake_case) is unpredictable now. People (like me) assume PSR-2 recommendations to be used if there is no other way specified in docs.
