### ISSUE TITLE
[feature] Failover options for Cache, Database and Queue drivers

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/internals#235]
## Proposal

It would seem relatively trivial in a future version to have the ability to have a "tiered fail-over" ability when services such as databases, caches and queues are unavailable. 

For example if using Redis as the cache driver and for some reason Redis fails, having the ability to serve the file cache driver as a next best fit would give a great software layer fail-safe ability.

Some may say this is the responsibility of the operations layer and not an application concern, although IMO whilst that is true, there always exists room for fail-over on ALL layers at once.

Thoughts?

**Comment by tomschlick** [comment]
Eh that gets weird for certain things. For database it's fine to failover to a slave, but for cache failing over to a file cache is weird because if you failover, a cached item is invalidated, and then you go back to the Redis cache you'll be serving the old data.

Same thing with Queues, if you failover put an item into the queue and the main queue service comes back online then you could effectively forget about the queued item.

**Comment by andrewmclagan** [comment]
Better a failed queue item, and stale cache rather then down time?

**Comment by Garbee** [comment]
> Better a failed queue item

Woah there, it entirely depends upon the work being done. Although, what you could do is just have a listener on the fallback queue always running, that way anything put onto it will still be executed. Not big deal there really.

As far as a stale cache though, that one is a problem. If you start serving old data to users, they may think changes they made haven't taken effect. When it comes to caching, if it fails it fails. Don't fallback to some other method (especially one that can't scale horizontally.) Otherwise you are going to make your already difficult challenge of cache invalidation that much more difficult. The goal should be to make things simpler for people in Laravel, not more complex.

**Comment by tomschlick** [comment]
IMO the only thing that makes sense for auto failover is something that is in a Master-Master configuration. Any other way and you're asking for issues when something silently fails over, then goes back when the original service is back online.

**Comment by andrewmclagan** [comment]
If the failover was executed on an exception, which Im assuming would be the best case. It would be easy to automatically flush the caches. I feel there is allot of flexibility if fail-over is handled on the application. Having the application aware of a failure and able to respond is always going to be more effective then fail-over on the operations level. These side-effect you describe are achievable right?

**Comment by andrewmclagan** [comment]
Database:

Sure its perhaps better to leave this to something like a Galera cluster, although even those can go down. An auto fail-over to a replicated slave as you stated would be as simple as catching a connection exception and moving on.


Cache:

The risk here is serving stale data, this could be overcome by catching the connection exception, flushing the caches and moving on.

Queue:

This is more complex. If there are items in the queue driver at time-of-failure they may be lost. IMO the current implementation of the queue is lacking in reconciliation of jobs anyway. Once items are sent to the queue driver there are cases where they can presently fail silently anyway. There are patterns where queue tasks are reconciled at time intervals to check if they have completed. Perhaps as queues are generally more complex these could be an exception.

**Comment by andrewmclagan** [comment]
Yeah my thoughts a year+ later are this is operations domain... not application domain.
