### ISSUE TITLE
[Proposal] Use route groups in auth routes

### ISSUE THREAD

**Issue by HendrikGrobler** [laravel/internals#245]
The way the routes are structured currently could benefit from using groups to avoid repeating prefixes and the Auth namespace.

Additionally, routes could be updated to use named routes and use 'as' in route groups, however this is a lot more opinionated and would require updating the view stubs to use the route helper and named routes instead.

I feel like this is often code that newcomers will go to in order to see how the auth routes work and it would be beneficial to teaching them about the recommended way of structuring routes by updating this code to use the best practices described by the documentation.

Please see this commit for an example of all the above proposed changes:
https://github.com/HendrikGrobler/framework/commit/93c3dc11bf149ad2e8f99293b3475b2e49a4e296

**Comment by ameliaikeda** [comment]
The first thing I do whenever I create a new Laravel project is to copy-paste the auth routes and give them names. Giving them all a prefix may be a little overkill and takes away from the simplicity of adding `redirect()->route('login')` to something, though.

In a production app I work on, we have an audit logging package (which could possibly be open-sourced) that runs as a middleware on all routes and logs the user doing an action. We found it easier to just name all routes and use route names, because changing URLs would usually break the logging in some way and require a migration.

**Comment by deframe** [comment]
+1 for grouping the routes as the classes and views are already grouped via namespace and folders.

I'm not fond of prefixing the route names as 'login' -> 'auth.login' is too big a break for too little benefit IMO. Without the prefix you'd need to rethink the names of the password reset routes as 'reset' and 'email' are meaningless on their own.

**Comment by HendrikGrobler** [comment]
Thanks for the feedback guys, I am going to go ahead and submit a PR for basic route grouping (not named routes and 'as' prefixes).
