### ISSUE TITLE
[Proposal] Automatic route naming when name not set

### ISSUE THREAD

**Issue by ivuorinen** [laravel/internals#254]
Currently `\Illuminate\Routing\Router::auth` does not name any other routes than `$this->get('login', [...])`, making default views use `url('/register')` for example.

I suggest naming convention `foo` on GET routes (where `foo` references `->name('foo')`) and `foo.post` in POST routes. This could be extended with other HTTP Verbs like `foo.options` and `foo.patch` for example. `->any()` would act like default GET.

Unnamed routes could be automatically named using the `\Illuminate\Routing\Router::get` `$uri` parameter replacing `/` with `.`, making `$this->get('password/reset', [...])` get name `password.reset` and `$this->post('password/email', [...])` named as `password.reset.post`.

This would help reflect changes in `routes/*` in views that could otherwise be overlooked.

As I'm not 100% familiar how Laravel could be extended to make this magic work, I imagine using something like `php artisan route:list` builds and detects HTTP Verbs from routes could be one starting point.

Only possible problem I could come up was changing route group name, making the route name in views change too, but that would be expected behaviour.

Anything I'm missing here?

**Comment by Garbee** [comment]
`password/reset` later becomes `auth/reset` for some reason. This then means the name changes from `password.reset` to `auth.reset` which is not what you want. Names should be considered constant so that you can generate routes dynamically from them and it doesn't matter what the actual URI path is. That is the whole point behind route names.

This proposal is essentially saying instead of using the route path you'd like to mangle that into a route name of the same structure. Which doesn't gain you anything in application development and maintenance.

**Comment by ivuorinen** [comment]
Ah, good point. Didn't realise those cases. Closing this one and returning back to drawing board.

**Comment by sailingdeveloper** [comment]
You might want something, a package perhaps, that generates these names, and stores them in the routes/*.php files. This way they don't change, but they are dynamically generated once
