### ISSUE TITLE
Migrations - Schema::dropIfExists() vs Schema::drop()

### ISSUE THREAD

**Issue by lukewhitehouse** [laravel/internals#255]
I'm not sure if this has been mentioned before but I don't see the point in having separate `dropIfExists()` and `drop()` methods when attempting to drop a table using Schema. Surely theres no reason to ever not use `dropIfExists()`?

I think it would be good in a future version to bake the functionality of `dropIfExists()` into `drop()` by default. Eager to hear feedback on this, are there any side effects?

Luke

**Comment by bobbybouwmann** [comment]
Well one use case would be in your migrations. Let's say I have some migrations and I want to rollback one migration, but before that I delete a table by hand from the database. When using `drop` with the rollback you will get an error since the table doesn't exist anymore and the rollback would fail. If I use `dropIfExists` the rollback would succeed while I would expect it to fail right?
