### ISSUE TITLE
[Proposal] Database Collection (std) objects to array

### ISSUE THREAD

**Issue by ozldmezot** [laravel/internals#269]
Database related concern about consistency:
Since 5.2 Laravel changed its return type of DB fluent query results from simple arrays to collections just to make it more consistent with Eloquent Collections.

I'd like to propose to extend it even further, similarly to Eloquent Collection,  when using toArray() the underlying objects should be converted to arrays as well. Seeing as the object is an instance of StdClass it can be doable. Or we could apply Arrayable interface to DB result set, therefore without breaking other components using Collection.

Example:

```
$users = User::all();
$users->toArray(); /* Underlying objects converted to array */

$users = DB::table('users)->get();
$users->toArray(); /* underlying objects would be converted to array as well */
```

**Comment by sisve** [comment]
I would like to point out that the current "Eloquent Collection" is just the same Collection class as DB::table(...)->get() returns, it just happens to be that all Eloquent models are Arrayable.

Changing this so that all objects get converted to arrays is a huge breaking change.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L36
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Collection.php#L1193
