### ISSUE TITLE
Config Cache problem

### ISSUE THREAD

**Issue by bestreaction** [laravel/internals#27]
If i can directly config:cache command, .env file could not run correctly. And i dont read it env variables.
But i run config:clear after everything is ok. it is very annoying error.

**Comment by JamesGuthrie** [comment]
This sounds more like a bug report, which should be created in https://github.com/laravel/framework, this repository is for discussing new features. Please close this issue.

To answer your question, the config:cache command caches the config, which can be in part loaded from the .env file. The behaviour you are seeing is the expected behaviour.
