### ISSUE TITLE
Type hinting causes recursion

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [laravel/internals#278]
Test case:
Two custom classes. Each typehints other class in __construct method
Classes are defined as singletons

```
$this->app->singleton(TestRepositoryInterface::class, TestRepository::class);
$this->app->singleton(Test2RepositoryInterface::class, Test2Repository::class);
```

I've cleared for simplicity

```
class TestRepository implements TestRepositoryInterface
{
    public function __construct(Test2RepositoryInterface $test2Repository)
    {
    }
}

class Test2Repository implements Test2RepositoryInterface
{
    public function __construct(TestRepositoryInterface $testRepository)
    {}
}
```

When I do `app()->make(TestRepositoryInterface::class)` in my unit test it causes recursion.

The error is
`PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /var/www/html/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 78` by xDebug even if I set it to 5000.

**Comment by jhoff** [comment]
I think you maybe forgot to update your example to use Test2Repository instead of AnswerFileRepository...

But given that they both use each other in the constructor, it makes sense as under the hood the singleton will attempt to new up an instance of both. I don't see a problem here.

**Comment by KonstantinKolodnitsky** [comment]
Sorry, my fault. I've corrected my example.

The sense on singleton is that it's only one instance of a class exists. So I thought that doing so I can just use this object instead of instantiating new one.

@jhoff How can you not see the problem? There is a recursion. Do you think that my architecture is wrong? Or what's the problem?

**Comment by jhoff** [comment]
Sorry, I mean I don't see a problem with the framework. It makes sense to me that it would cause recursion.

app()->make(TestRepositoryInterface::class) instantiates a new TestRepository instance, but during it's construction, it tries to instantiate Test2RepositoryInterface by creating a new Test2Repository instance, but because the first TestRepository isn't done constructing yet, it goes into the first loop of recursion trying to new up another TestRepository. Rinse and repeat.

It's a chicken or the egg situation. You can't dependency inject one without the other and vice versa.
