### ISSUE TITLE
Easy way of restructuring the HTML of the pagination

### ISSUE THREAD

**Issue by khru** [laravel/internals#282]
In a few of my projects I has to create a Custom pagination because I wasn't able to chabge the HTML structure and the css class of the pagination.

**Comment by tomschlick** [comment]
Did you try publishing the blade files and modifying those as described here: https://laravel.com/docs/5.3/pagination#customizing-the-pagination-view

--
Tom Schlick




On Mon, Oct 31, 2016 at 4:24 PM -0400, "khru" <notifications@github.com> wrote:












In a few of my projects I has to create a Custom pagination because I wasn't able to chabge the HTML structure and the css class of the pagination.

**Comment by khru** [comment]
No I haven't tried that, thx. But I still think It can be a cool feature and not to hard to create.

**Comment by timacdonald** [comment]
I've just done this using @tomschlick link and it works perfect, can completely re-write or adjust small parts of the pagination html as needed.
