### ISSUE TITLE
Generator for Global Scopes

### ISSUE THREAD

**Issue by alexbowers** [laravel/internals#283]
There is currently no generator for scopes. Is there a reason this is omitted?

My current process when having to create a global scope is to go to the documentation and copy the example, then replace as necessary; so boilerplate would be useful here. Whilst they may not be used often, it will be handy for the times it is used.

**Comment by brayniverse** [comment]
I presume there is no generator because there is no recommended place to store scope classes. Maybe if we could agree on a sensible default, then the generator would be accepted. I recommend using the `app/` directory along with all your models.

Try submitting a PR and see what people say. If you haven't got the time, I'd be happy to produce one tomorrow.

**Comment by alexbowers** [comment]
The documentation seems to suggest (based on the namespace) `app\scopes`.

https://laravel.com/docs/5.3/eloquent#query-scopes

**Comment by brayniverse** [comment]
Huh guess I was wrong :), still worth trying a PR I think.

**Comment by alexbowers** [comment]
Yeah, i'll try to submit one this evening

**Comment by alexbowers** [comment]
PR Submitted

**Comment by alexbowers** [comment]
PR was rejected.

**Comment by brayniverse** [comment]
@alexbowers that's a shame. You could always create a package for this.

**Comment by alexbowers** [comment]
It isn't the end of the world, so i'm not too bothered by it. Next time I wish to use a generator to use it, I will probably create a package for it. But as taylor said, it isn't common enough that people will use an external package for it. It would have been nice to be "just there" for the rare case that it is used.
