### ISSUE TITLE
Laravel Generator Commands accepting multiple class names

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#297]
As in the title.

Usage:
```
php artisan make:model User Role Permission
```
```
php artisan make:controller UserController PostController SessionController
```

What do you think?

**Comment by brayniverse** [comment]
Sounds good, I'd find that useful.

**Comment by KKSzymanowski** [comment]
Or would it be better to create separate *plural* commands like:
```
php artisan make:models User Role Permission
```
Which would call existing *singular* commands in a loop.

**Comment by KKSzymanowski** [comment]
Also, I have one concern about the `make:command` command.

It accepts a `command` option which specifies the name of the newly created command.
Should the new implementation give all created commands the same name or should it exit with an error saying "The 'command' option isn't supported when multiple classes are being created"?

**Comment by dugajean** [comment]
I like the idea, however I think it would be troublesome to implement a whitespace separated list of names, since they will be counted as further arguments by the Symfony console component. I'm not highly familiar with its API, but a way to get around this would be to have a comma separated list of names like this:

```
php artisan make:models User,Post,Comment
```

And yes, I also support the idea of pluralizing the word. Makes more sense.

**Comment by KKSzymanowski** [comment]
I implemented that but it was rejected [here](https://github.com/laravel/framework/pull/16410).

I asked @taylorotwell, but haven't got any feedback if he'd like the *plural* commands better.

As for the implementation details, Symfony perfectly supports space-separated arguments and converts them to an array automatically.
