### ISSUE TITLE
[Proposal] Broadcasting improvements (Removing the need for insane server setup)

### ISSUE THREAD

**Issue by jlndk** [laravel/internals#332]
Hey guys.

I've been thinking making these feature requests since Laravel Echo was annonced. 
Even though the broadcasting improvements in 5.3 made it much easier to build realtime apps, I still think more work could be done to make it even easier. Therefore I got two concrete proposals to make it much easier for us to create strong and maintainable reamtime apps.

- Make it posible to use the same way of attaching event listeners as routes and closure commands  (in a routes/events.php or something similar)
- Create a new broadcast provider, which establishes a websocket server, and broadcasts dirrectly to the client

I dont know if these concrete ideas should be discussed in seperate issues. If that's the case I'll of cause seperate them if that's better :). 

## Closure Syntax for event listeners
When using the current way of defining events in laravel it can quickly become really hard to maintain when you have many of them. I therefore suggest adding a way of defining event listeners in the same easy way you allready can for routes and console commands. 

I would add a events.php file to routes, alongsite web.php, api.php and console.php.
In there you could use a syntax simelar to:
```php
<?php
//referencing a method on a listener
Event::listen('App\Events\UserCreated', 'App\Listeners\UserListener@onUserCreated');

//creating an inline closure
Event::listen('App\Events\UserDeleted', function() {
  //
});
?>
```
I know that you're already able to use Event::listen in this way in the EventServerProvider already, but i think it would be valuable to add a seperate file for events, in the same way routes and console commands already has. It would really bring a more consistant workflow when building realtime apps.

## Websocket broadcast provider
No matter how much I've used the current system I just can't help but think how unnessesarely complicated it seems. I just find it strange that we're required to either subscribe to an external service (pusher) or have a crazy server setup to have realtime funcionality in laravel apps. In my opinion we should just be able to run a http server and a websocket server, without all of the layers between.

I've been thinking about implementing a custom broadcasting provider which communicates directly through a websocket, and broadcasts the event, instead of going through a queue runner, redis and a node server, as it is recommended in the docs if you don't want to pay a monthly fee to another company. 

I've already made a somewhat working prototype using Ratchet (http://socketo.me/). I got it working just fine, but unfortunately found some implecations along the way. The big problem is that a websocket server has a totally diffrent lifecycle than both a HTTP request and a console command. Therefore I found it necessary to write a custom kernel for websocket server. 

This would of cause also mean that we would have to implement a new connector in Laravel Echo too, and therefore decide which protocol we should use. In my testing i've just been using Autobahn.js, which we could potentially write a wrapper around. Just like we do with Pusher and Socket.io. 

What are your thoughts on these?

**Comment by happyDemon** [comment]
I'm personally not a fan of defining the events in one file, having them the way they're currently setup gives me a better overview.

However it would be nice to have ratchet as additional broadcaster option.

**Comment by barryvdh** [comment]
For ratchet you would still need to keep a process running  that listens to a new port, right? So instead of:
`/usr/local/bin/laravel-echo-server start`
in your Supervisor config, you get:
`/usr/local/bin/laravel-echo-server start`

And you will need to communicate with the ratchet API, what Redis now does for SocketIO (using queues).

Imho, a minimum Laravel server would:
 - have Node + NPM (or Yarn) installed
 - Is running queues already (for email, events etc), preferably using Supervisor

So extra requirements are:
 - Install a socket server
 - Install Redis

You are going to need to install a Socket server either way, using Node (`yarn global add laravel-echo-server`) or PHP (`composer create-project some-php-echo-server`?) and configure at least something (port, ssl path etc)

About Redis, I think laravel-echo-server supports HTTP broadcasting, so you can avoid Redis. https://github.com/tlaverdure/laravel-echo-server#http

But there is no built-in HTTP broadcaster in Laravel, so you could implement that yourself. You can even use sync queue, but that would slow your app down a lot.
