### ISSUE TITLE
Public storage directories confusion

### ISSUE THREAD

**Issue by philbates** [laravel/internals#34]
Our of the box on a fresh Laravel 5.2 application, you have the `public` disk defined in `config/filesystem.php`, which points to `storage_path('app/public')` with visibility `public`. Not being familiar with Flysystem, I would have expected that this directory would be configured to be publicly available via a URL, eg `/storage/file.doc` where the actual location is `storage_path('app/public/file.doc')`. But out of the box this isn't the case. What is the intended purpose of this directory? As far as I can see, in order to make the `public` storage directory actually public, I either need to make a controller that returns the file, or create a symlink in the `public` directory pointing to `storage_path('app/public')`.

I also just noticed that the default `.gitignore` file has a `/public/storage` entry, which doesn't actually exist. So how is that directory supposed to be created?

Maybe it would make more sense for `public/storage` to always exist (by committing a `public/storage/.gitignore`), then make the `public` disk to point to `public/storage`?

**Comment by andaril** [comment]
Here is explanation of this: http://taylorotwell.com/spark-storage/

It's just not documented for now I guess.

**Comment by gocanto** [comment]
I don't understand the fact of making a direct access from ```public``` to ```storage``` folder. I do not have problem working with the storage one, in fact, it better because the files are not accessible from the ***url***

I really don't know what the others think

**Comment by philbates35** [comment]
Interesting, I hadn't seen that blog post. So although undocumented, it's expected to make a symlink.

Just a thought - it would be nice if in the same way that the `.env.example` is copied in the composer create project hook, the symlink should be created too so that everything works out of the box on a fresh project. I guess the issue is that symlinks don't work the same on Linux Mac and windows, so it would hard (impossible?) to write a one line script in `composer.json` that creates the symlink.

**Comment by mattwells** [comment]
@philbates35 having composer create symlinks would be difficult as different OS's have different commands to create symlinks, if they support it at all. 

Maybe if you created an extension for composer?

**Comment by tomschlick** [comment]
You could always write a quick artisan command to do that... `storage:symlink-public` which would check the OS and create the appropriate symlink for that system during bootstrap.

**Comment by philbates35** [comment]
That's a pretty good idea, and seems like something worth adding to the core and `laravel/laravel` IMO. That way it's obvious exactly what the public storage directory is and how it works.

**Comment by philbates35** [comment]
Related PR: laravel/internals#2265

**Comment by philbates35** [comment]
Related PR: laravel/docs#2265

**Comment by barryvdh** [comment]
FYI, [Symfony Filesystem](http://symfony.com/doc/current/components/filesystem/introduction.html#symlink) has a `symlink` method, so if you require that, it should be pretty easy.

```php
$fs = new Symfony\Component\Filesystem\Filesystem();
$fs->symlink(storage_path('app/public'), public_path('storage'));
```

**Comment by barryvdh** [comment]
But if you deploy, something like this should probably do the trick also:

```
"post-install-cmd": [
	"ln -s public/storage storage/app/public"
],
```

**Comment by BrandonSurowiec** [comment]
@barryvdh Thanks for the post-install-cmd. I had to add `r` so it would use the relative paths.

```
"post-install-cmd": [
    "ln -sr public/storage storage/app/public"
],
```

**Comment by gocanto** [comment]
Just for curiosity, what is the issue of having the storage as it came? I would like to know

**Comment by g3n1us** [comment]
Great new add from Taylor...

@BrandonSurowiec Shouldn't the command's arguments be reversed?
"ln -sr storage/app/public public/storage"

**Comment by gstoa** [comment]
Indeed the symlink command should be "ln -sr storage/app/public public/storage"

**Comment by ctf0** [comment]
i know am kinda late to the party but i have a couple of questions
1- why not just change the path in the config to directly go to the public path not the storage path ?
2- lets say i have sub folders `storage/app/public/events & storage/app/public/teams` , how the symlink would work then ?

**Comment by michaeldyrynda** [comment]
As was linked to by @andaril earlier, symlinking of the public storage directory was done so that the public user content is not lost between deployments.

If you symlink `storage/app/public`, all containing folders will be served there - the only thing that changes is that the content itself is not actually within `public`, it is just referenced there.

**Comment by gocanto** [comment]
@ctf0 Because the storage folder purpose is to keep users file away from external sources. If I am wrong, please clarify it for us then.

**Comment by TheAifam5** [comment]
I'm using public storage and can't get access to it. Shows "Access denied.". Any ideas?
chmod is -rwxr-xr-x

**Comment by ctf0** [comment]
@gocanto when u alias the storage folder to the public, the user is going to access this files, so why make the way around if u gonna end up at the same point "have the user accessing the public folder resources" ?

**Comment by gocanto** [comment]
@ctf0 I personally don't do this. My schema is to keep users files in the storage and link them through a (get route) for them to be served out. I do not know what the problem is with this approach and I am courios to see where it goes.

**Comment by ctf0** [comment]
having a route to serve files is a un-necessary extra step, it creats and overhead and its not right + it misses what this issue is about,

this post is about to keep ur files in the storage folder to avoid any probs when deploying with something like Envoyer, and to only keep the necessry files in the public "ex. css,fonts,js,etc..", but if u gonna copy the storage folder anyway so why not just keep everything in one place "my original questions above"

- the problem with that approch is for example, when the user save an image, i save its path to the db so i can just call it `src={{ $photo->link }}` but now when u upload to the storage u cant do that because storage folder it not public and u will get a 404.
- 2nd problem is when u try to call the image u will have to append the public path to each folder like `assets(public/folder/user_id/somthing.jpg)` because thats the alias, again an extra un-necessary step.
- 3rd problem is that creating the alias folder cmnd is different for each platform, like on mac i cant use the `r` and i have to use the full path in order to make the alias, this creates one more thing to worry about when u deploy specially if u r new to the whole server deplying/managment thing.

**Comment by JosephSilber** [comment]
Here's an artisan command to link it:

php artisan storage:link

It's now cross-platform, so there's no extra work on your part.

**Comment by ctf0** [comment]
@JosephSilber that is not available in laravel.

a temp solution , 
because most of the user content u will be storing will be images, u can save it in the db as base64 data uri and call it simply by `src=$image->link` , now every user will get his own content and u dont need to worry about routing or any extra steps to fetch the data from the storage path.

this is easier as well when dealing with the user deleting/managing his content, u simply search for the id of the item and delete it.

**Comment by AssinieDev** [comment]
` [ErrorException]
  symlink(): No such file or directory`

When trying to use the command below
`php artisan storage:link`

**Comment by JosephSilber** [comment]
@assinieDev If you've upgraded from an older version of Laravel, you have to first create the `public` directory in `storage/app`.

Do that before running this command, and it should work.

**Comment by AssinieDev** [comment]
I'm using Laravel 5.3 RC1 and `storage/app/public` already exists

**Comment by ctf0** [comment]
@AssinieDev its introduced in 5.3, not in 5.2

**Comment by M4gicT0** [comment]
@AssinieDev Yeah got the same problem cause my symlink came from my server so I had to delete first, and then call `php artisan storage:link`.

**Comment by thatdoorsajar** [comment]
I'm on Windows 8.1 and using Homestead and after a few hours of head against the wall the only command that I can run to successfully setup the symbolic link to have it work both inside and outside of the Homestead VM is:
`mklink /D public\storage ..\..\storage\app\public`

**Comment by jordanramstad** [comment]
I have tried everything to get this to work on windows 10, the only one to work was @thatdoorsajar  suggestion worked. It may be due to using vmware instead of virtual box, but it remains that the symlink is hard to handle in windows environments with homestead.

```
Artisan::command('storage:link-windows', function () {
    exec('mklink /D public\storage ..\storage\app\public');
})->describe('Windows symlink');
```

This is a simple command that can use artisan to make the symlink in windows. At least when the problem is the same as mine. Using artisan helps to bypass problems associated with using something like ming32 rather then CMD as well. Cannot guarantee it will help everyone, but hopefully can help some.

**Comment by sisve** [comment]
Symlinks are special in implementations of shared folders in virtual machines. They often require some configuration to work.

VirtualBox: https://www.virtualbox.org/ticket/10085#comment:14
Vmware: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1007277

**Comment by votemike** [comment]
The documentation isn't clear that `php artisan storage:link` should be run inside the VM. I stupidly ran it on my local machine and was confused for a while as to why it didn't work. Should the documentation be updated again?

**Comment by ventouris** [comment]
I have the same issue. When I run the 

`php artisan storage:link`

I have the following error:

  [ErrorException]                      
  symlink(): No such file or directory 

I use local by Flywheel for local development.

**Comment by sisve** [comment]
@ventouris Your problem isn't related to this issue, and it isn't a bug report. Try asking on the forums or on [Slack](https://larachat.co/) instead.

**Comment by philbates** [comment]
Closing as the `php artisan storage:link` command was added to generate the symlink, clearing up any ambiguity and confusion about the public storage.

**Comment by kamil-kielczewski** [comment]
I have error `symlink(): No such file or directory` when I call in my Dockerfile command `php artisan storage:link`.

Reason: in my local project I ALREADY have `public/storage' link (!) and docker copy it on image building process - and this cause above error.

Solution: add to `.dockerignore` file follwing line:

    `public/storage`

**Comment by sujalpatel022** [comment]
try to delete existing storage symbolic link and then try `php artisan storage:link` command

**Comment by daniel-farina** [comment]
If you are on windows you can run this command from Gitbash  as an Administrator. That's the trick .

```
ln -sr storage/app/public public/storage
```

**Comment by HesamSJD** [comment]
> @barryvdh Thanks for the post-install-cmd. I had to add `r` so it would use the relative paths, but even though it linked it doesn't appear to be working locally on homestead. I probably need to SSH into the server.
> 
> ```
> "post-install-cmd": [
>     "ln -sr public/storage storage/app/public"
> ],
> ```

try ln -r many ways , ln -sr worked ,

**Comment by bernaud2k** [comment]
> But if you deploy, something like this in your composer.json should probably do the trick also:
> 
> ```
> "post-install-cmd": [
>     "ln -sr storage/app/public public/storage"
> ],
> ```

You are helped me. Thank you so much!))

**Comment by kefivitch** [comment]
This works for me !
```
cd public_html
ln -sr ../storage/app/public storage
```
