### ISSUE TITLE
[Proposal] php artisan migrate:refresh --with-data

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/internals#343]
I would like to make a PR with the following feature, but I don't know if you want to see it.

## The change
Have you ever run `php artisan migrate:refresh` but wished it preserved all of your data (say test users)? Of course, there are seeders, but sometimes we just don't have time to write them.

The proposal is to create a new flag, say `--with-data`. The way it would work is it would save all of the data in the db to a file and then, after `migrate:refresh`, attempt to repopulate the db with saved data.

* If the schema for a table didn't change then there would be no problem.
* If the newly introduced field was _nullable_ or had a _default_ value there wouldn't be a problem either. 
* If a column disappeared, then it just wouldn't be populated.
* If a new column was introduced, wasn't _nullable_ and didn't have a _default_, the
```
Warning:
The schema of a table abc changed and the newly created column xyz couldn't be populated.
All of the data has been saved in storage/framework/cache/2016_12_19_154217_database_data.sql.
You can manually restore it and populate the database table.
```
would be shown.

## Feedback
I'd like to know:
* if you like the idea,
* is the `--with-data` flag a good one (name wise),
* should the `storage/framework/cache/` path be used to store the data,
* should the file be deleted if the save was successful.

**Comment by sebastiandedeyne** [comment]
In which case would you have a newly created column when *refreshing* a migration?

**Comment by DCzajkowski** [comment]
Many people (who work alone on some idea), when the code is still in development, change migrations and `migrate:refresh` instead of creating a new migration with a new column, that way initial migrations are clean and tidy.

**Comment by Garbee** [comment]
You can use composer scripts to setup a set of commands that would dump your DB to a file, refresh the migration, then load the file back in. This would also work with whatever DB config you have since you have absolute control over the dump.

I don't see why this should be added into Laravel's core. It seems like a niche case. Especially since you *should* be writing seeders from the start to handle generating test data anyways.

**Comment by DCzajkowski** [comment]
> You can

You could. But it takes time. And writing out `--with-data` is very simple, fast, and takes care of everything for you.

**Comment by Garbee** [comment]
Put plainly, I'd rather we not introduce extra core maintenance for a niche case that is trivially handled with alternative methods readily available through the pre-existing tooling required to run Laravel in the first place. This way, fewer things to worry about going wrong in the future.

**Comment by DCzajkowski** [comment]
With that way of thinking Laravel development would stop and no new features would be introduced, as everything requires some type of maintenance.

**Comment by Garbee** [comment]
Keyword `niche`. As in it only serves a very small subset of overall users therefore isn't as useful for the majority to have available.

**Comment by DCzajkowski** [comment]
> it only serves a very small subset of overall users

I wouldn't agree it is a small group. The fact you don't do so doesn't mean others don't either. I have seen many people needing that feature. I don't have any real data on that though.

**Comment by Garbee** [comment]
How many of those knew you could achieve the exact thing you need in like 4 lines added to `composer.json`? I'm not saying it is the most straightforward thing since you do need to get the DB credentials dynamically from the env, but it is doable. No reason to go tossing more things in when a little bit of effort on developers ends gets the job done cleanly and accurately to your setup.

**Comment by DCzajkowski** [comment]
If it is 4 lines of code, could you share them?

**Comment by bobbybouwmann** [comment]
I would rename the `--with-data` to `--seed` since we already have that with `php artisan migrate ---seed` to run the seeds after the migrations.

**Comment by Garbee** [comment]
I can't "give you the code" as it depends on your DB. Essentially this though:

1. Add a new script entry in your composer scripts. Value is an array.
2. Add first entry to do the dump
3. Second entry to migrate
4. Third entry to apply dump to db
5. Profit

You can even do a little `bin` directory and just do some quick shell scripts to call to to make the dumping and restore isolated out of the composer file itself. Fairly trivial effort overall.

**Comment by DCzajkowski** [comment]
@bobbybouwmann The `--seed` is already in use for seeding (RefreshCommand.php@needsSeeding()).

**Comment by DCzajkowski** [comment]
@Garbee That doesn't sound like a 'trivial' thing to do. Can you share an example for MySQL or SQLite? Also, if it is dependent on a database, isn't it Laravel's goal to automate it?

**Comment by brunogaspar** [comment]
👎  from me.

Just use the seeders, that's the whole purpose of them, to seed data.

However, if you really want to go the route you suggested, which seems fine for your application, i would just create a package and extend the migrate command to allow some sort of flag.

**Comment by Garbee** [comment]
@DCzajkowski It really can't since to do a DB dump you need to call out to external applications, like `pgdump` or `mysqldump`. Unless you want to do things in a highly inefficient manner.

If you do some searching around for dumping a given database I'm sure you'll find plenty of tutorials. It shouldn't take long to work up a quick few-line bash script to do the tasks needed to plug into composer.

**Comment by flymke** [comment]
Hey guys, I just stumbled over that. Actually I agree to @DCzajkowski. It should be not that difficult to add something like --with-data ? I mean for things like changing a field to be "nullable" or simply adding another field. Actually I am still new to Laravel but I've already been really missing this feature. Afaik Symfony includes that out of the box with php app/console doctrine:schema:update --force (and I've been using that quite a lot). Maybe I am wrong, but this would be indeed a great feature!

**Comment by Garbee** [comment]
If you really want this kind of composition, use seeders (as mentioned) and make your own composer script that runs a migration reset then seeds the DB. It's not complicated at all to DIY in your projects. It also gives you full control over what tools are used and makes it easier to move packages later.

**Comment by PieterjanDeClippel** [comment]
I want to move my **users, password_resets, oauth_refresh_tokens, oauth_personal_access_clients, oauth_clients** to another database with the name **internal** so that these can be shared with all my applications in a manageable way.

Sadly all my other data is linked to the user-table so I can't just drop these tables and move them to another db.

First I'd need to actually rollback the migrations and apparently you folks think it's not necessary to back up the data to add them again after re-running the migration.

**Comment by gagishmagi** [comment]
I think it's not an easy task because this is what the sql way does:
1. Copy the structure to temp view or table and store in the db.
2. After that copy also data to temp view or table and store in the db.
3. Destroys the table structure and the data
4. Copy back the structure 
5. Now copy back the data from the temp view/table.
6. Destory the temp table structure and the data.

It can break on each of the steps and you need to handle all these issues
either show what went wrong or find the step that broke and continue from there.
seems like too much work for a tiny feature , even I will also like it to be in the next version of artisan
I don't really believe that it will happen but, only time will tell... :+1:

**Comment by yaquawa** [comment]
I wish there's an option to read migration file, and compare to the production db find the diff, and then output the sql file to be applied to the production db… 

Because.. keep altering table = keep the migration files increasing, which you'll get a bunch of migration files that you won't be able to track intuitively. Life shoudn't be this HARD!!!
