### ISSUE TITLE
Store binary UUID in MySQL

### ISSUE THREAD

**Issue by a-komarev** [laravel/internals#350]
I'm using Laravel 5.3.x with MySQL 5.7.x.

There are plenty of articles how to speed up performance significantly by optimizing and store UUID values in BINARY(16) column for the MySQL InnoDB. [Here is one of them](http://mysql.rjweb.org/doc.php/uuid).

I was sure that `$table->binary('id', 16)` will make `BINARY(16)` column. But was surprised that it generates `BLOB` field. And BLOB is made for Binary Large Objects.

There is a hacky way to do the job:
```php
Schema::create('movie', function (Blueprint $table) {
    $table->string('title');
    $table->timestamps();
});

DB::statement('ALTER TABLE `movie` ADD `id` BINARY(16) FIRST;');
DB::statement('ALTER TABLE `movie` ADD PRIMARY KEY (`id`);');
DB::statement('ALTER TABLE `movie` ADD `producer_id` BINARY(16) NULL AFTER `id`;');

Schema::table('movie', function (Blueprint $table) {
    $table->foreign('producer_id')->references('id')->on('producer')
          ->onDelete('cascade')->onUpdate('cascade');
});
```

But when I've started to make big package with a lot of UUIDs, I've understood that migrations are unreadable and hardly maintainable because of lot of foreign keys (each model has 1-3 FK). And the most valuable reason that it's not database agnostic.

Questions I want to rise:

- Is there any reason why migration binary method `$table->binary('id');` generates BLOB column instead of BINARY?
- What do you think about adding method to blueprint to make BINARY column with fixed size in MySQL (I haven't researched other database engines accordingly this question yet)?
- If make this method, how you would name it? I was thought about `$table->binaryUuid('id')`.
- Another one approach is to use `VARBINARY(16)`, because as I understand MySQL 8.x will use it for UUIDs, so method will be `$table->varbinary('id', 16)`.

Any advise how to deal with it will be appreciated!

**Comment by nicholas-eden** [comment]
There is also the `Blueprint::uuid` method, which is mapped to char(36).  It would make sense to change that to binary.

I'd like to see the `Blueprint::binary` method mapped to the actual binary column type, and add a blob method.

**Comment by sisve** [comment]
This would be a big bc-break for migrations. Creating a uuid-column for my users.id-table, and later (after this change) a user_addresses.user_id column, and they would not be compatible for a foreign key.

We've already seen this with timestamps  - https://github.com/laravel/framework/issues/17313

**Comment by Garbee** [comment]
Personally having it as a char in MySQL is fine. Developers can query it without any extra work. If anything like this does get added it should be `uuidAsBinary` or something along those lines. So developers that want this could opt in to using it.

**Comment by michaeldyrynda** [comment]
There shouldn't be any extra work needed by developers if you change the field in the database to be `binary(16)` instead of `char(36)` and it is indeed a more efficient method. I agree that changing the behaviour of the current `uuid` would be a BC break. You'd probably want to wait till probably 5.5, noting that Laravel isn't really semver, and 5.4 is around the corner.

It's simple enough - and we've done it not long ago at work - to simply extend the underlying schema/blueprint classes to handle it in your app, if you needed the functionality in the meantime.

As an aside, I'd be more inclined to use UUID as a kind of public ID, whilst using `id` internally, as this is more efficient when handling internal indexes for MySQL; unless you're planning on ordering the UUID column, too.

> For the table with UUID as PRIMARY KEY, you can notice that as the table grows big, the time taken to insert rows is increasing almost linearly. Whereas for other tables, the time taken is almost constant.

**Comment by Garbee** [comment]
Everything I'm seeing as to how to work with them involves converting them through hex values to binary form. Perhaps someone could reference something that shows how it works specifically. Or possibly setup a small demo app that shows it working fine.

This should *not* be a point release change if the normal `uuid` type is modified for MySQL. While Laravel may not follow SemVer, modifying the way people's *databases are created* is critically massive. A change like that if done would *need* to be a 6.0 feature. However, there is a perfectly valid and non-breaking way to do this which is `uuidAsBinary` or some variant as a new method for the schema builder. Very simple, non-intrusive, and doesn't break anything. It also could make converting via migrations easier since you call `uuid` first then make a new migration to change that to `uuidAsBinary`. So, you don't break anything at all for developers and things stay natural.

**Comment by kocoten1992** [comment]
vote on uuidAsBinary , here is an article https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
