### ISSUE TITLE
Create many records at once

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/internals#357]
Is there a functionality to create many models with one database call?
I know about the `insert` method. Yes, I can pass an array of arrays to it, but it wouldn't create timestamps or hit *Eloquent event listeners*.

If there isn't a way to do this currently, may I propose a method called eg. `createMany`.
There is however a problem with retrieving ids for all inserted rows, but for example MySQL's InnoDB guarantees atomicity of *bulk inserts* so it can be calculated using `LAST_INSERT_ID()`(which returns id of the first row in the batch) and `ROW_COUNT()`. That way the method can return a collection of models as an analogy to the `create` method returning a single model instance.

Would this work for other RDBMSes?
If not, it can just return a boolean as an analogy to the `insert` method.

What do you think?

Main use case, for me at least, would be migrations where I sometimes need to insert hundreds of rows into many tables and using `create` in a loop results in them running for couple of minutes.

**Comment by sisve** [comment]
When you say that _InnoDB guarantees atomicity of bulk inserts_ you probably misunderstood what that means; mysql guarantees that either all or none of those rows are written to the table in a single-statement-transaction-like behavior. There are no additional guarantees on the generated keys; they are still generated according to [innodb_autoinc_lock_mode](https://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html) in steps of [auto_increment_increment](https://dev.mysql.com/doc/refman/5.7/en/replication-options-master.html#sysvar_auto_increment_increment). There are no guarantees that the generated keys are continuous; it just happens to be so in the default configuration.

Instead of special logic and attempting to calculate the values (in all evil scenarios I can make up), how about generating the primary keys in your application and insert them into your database? This is common with uuid keys, and would totally remove the step where you ask the database about the generated keys.

**Comment by KKSzymanowski** [comment]
@sisve Thanks for your response.
Your are correct, I didn't get the whole picture of the AUTO_INCREMENT behaviour in InnoDB.

I agree, this may be dangerous in some configurations and moreover, some databases may simply not support it. I think this leaves us with two options:
1. Return first created model - user can wrap it up in a transaction and get all new rows with `Model::where('id', '>=', $firstInserted->id)->get();`
2. Just return a boolean as `Model::insert` does.

**Comment by mpyw** [comment]
Related
[[Proposal] findOrCreateMany · Issue #1695 · laravel/ideas](https://github.com/laravel/ideas/issues/1695)
