### ISSUE TITLE
Php artisan app:name allows special chars

### ISSUE THREAD

**Issue by dispix** [laravel/internals#36]
Hi !

I'm pretty new to Laravel and the world of web development in general, but I feel like this is something I had to signal somewhere :

When using the `php artisan app:name` command, there's no restriction on the name you give to your app. For example, I used `php artisan app:name laravel-people` and the hyphen broke my project.

Wouldn't it be possible to prevent people from trying to use this kind of special characters in the command ?

**Comment by tomschlick** [comment]
Looks like that was suggested in PR laravel/framework#12996 but was closed for some reason. I'd inquire on there about it.

**Comment by Chaosbit** [comment]
I had the same issue, would be nice to have there some protection as it messes up a lot of files.

**Comment by michaeldyrynda** [comment]
I think it's time to remove `app:name` - then all the problems go away :)

**Comment by tomschlick** [comment]
@michaeldyrynda 

![](https://media.giphy.com/media/RddAJiGxTPQFa/giphy.gif)

😄

**Comment by skyrpex** [comment]
The App namespace should be the standard for the every project (non library
code)...

**Comment by jbrooksuk** [comment]
> The App namespace should be the standard for the every project (non library code)...

Why?

**Comment by skyrpex** [comment]
IMO it makes sense that your application root is `App` (because it's your application, and there's only one), and the same for your `Tests` (for the sake of standarizing). The rest of the code is library code, so it'll be namespaced with the proper vendor name.

It just makes things more consistent and allow tools and commands to be easier to write (there's no need to handle variable namespaces when scaffolding code).

**Comment by michaeldyrynda** [comment]
It also removes cognitive overhead when switching between projects.

The more similar my applications are from project to project in terms of layout and directory structure, the more efficiently I can move between them as necessary, focussing less on where things are.

**Comment by CupOfTea696** [comment]
@michaeldyrynda yes, but this just allows people the option to change it. No one is forcing you to change the App namespace to something else. I feel this is just a matter of preference, really, and I see no point in removing the command...

**Comment by skyrpex** [comment]
> [...] and I see no point in removing the command...

Because t's a hard to maintain command: you need code that detects your root namespace (see Application::getNamespace for reference). That's complex and can easily break.

On the other hand, it makes scaffolding commands more complex because they also need to know the root namespace.

Finally, you want to reduce to a bare minimum the code that creates / alters existing other source files. That's extremely hard to maintain.
