### ISSUE TITLE
[Proposed change] Add input confirmation to make:auth command

### ISSUE THREAD

**Issue by jrl05k** [laravel/internals#376]
IN  ..../laravel/framework/src/Illuminate/Auth/Console/MakeAuthCommand.php

  ......
  ......
  ......

/**
 * Execute the console command.
 *
 * @return void
 */
public function fire()
{
        if($this->checkAuthExists())
        {
            $proceed = $this->ask('Do you want to proceed? [Y/N]');
            if(strtolower($proceed) !== 'y')
            {
                $this->info('Operation cancelled.');
                return false;
            }           
        }
    ......
    ......
    ......

    /**
     * Check if views or controller already exist 
     *
     * @return boolean
     */
    protected function checkAuthExists()
    {
        $exists = false;
        foreach ($this->views as $key => $value) {
            if(file_exists(base_path('resources/views/'.$value)))
            {
                $this->info('View already exists: '.$value);
                $exists = true;
            }
        }
        if(file_exists(app_path('Http/Controllers/HomeController.php')))
        {
            $this->info('Controller already exists: HomeController.php');
            $exists = true;
        }

        return $exists;
    }

**Comment by michaeldyrynda** [comment]
In what scenario would you need this confirmation I wonder?

This is something you ought only to run whilst in development, so if you did it by accident somehow, you'd just roll it all back via version control.

**Comment by jrl05k** [comment]
If you were to create a layout file: ..../views/layouts/app.blade.php and later on you decide you want authentication and use make:auth, it would overwrite the app.blade.php file without warning. You are right that if you had made a commit before running make:auth you could just roll it back.

**Comment by bonsi** [comment]
Although I agree this feature would only be useful on rare occasions, I actually ran into the same issue yesterday and was going to submit an issue with PR for it. 

When I'm working out an idea for a new project, I tend not to start with auth scaffolding but try to implement a basic working version of my idea first. If later it turns out I need authentication, I would like use the make:auth command without it having overwriting all the work I already did.

I agree, a VC rollback would normally work just fine, IF I already took the time to add my "playground" to VC. I guess the real problem here for me is that having to think about committing to a VC first before using make:auth is more like a mental burden. Now that I know make:auth just plain overwrites any existing files, I'm sure I will think of it next time before using it, but any newcomers to the framework (or existing users who never used make:auth before) will still get surprised by this "undocumented feature".

**Comment by tomschlick** [comment]
It could just prompt before overwriting any files. So if it's your first time running it then no prompt, if you already did it asks for confirmation before overwrite.

**Comment by skyrpex** [comment]
Maybe it could just prompt if there are files that will actually be
overwritten.

**Comment by shalvah** [comment]
This happened to me last week, and I pushed to the live server without knowing my own code had been overwritten. 

But I'd suggest that the command gives the user the option to choose a different directory/name for the files instead of only aborting or overwriting.

**Comment by Garbee** [comment]
Make command should be off in production. But that doesn't help when you do it local, then commit all without looking at the change list and push.

**Comment by shalvah** [comment]
Exactly what happened to me @Garbee
