### ISSUE TITLE
Allow Gate to resolve interfaces?

### ISSUE THREAD

**Issue by hiendv** [laravel/internals#38]
As previously mentioned here: https://github.com/laravel/framework/issues/11965
I think it would come in handy for Gate to resolve interfaces.
At the moment, the Gate is resolving the argument by `get_class` [(see)](https://github.com/laravel/framework/blob/3044a65740a945f610f7f9f8106a2b2f0ce96de7/src/Illuminate/Auth/Access/Gate.php#L402-L413) if it's an object but there's much more we can do. If an interface can be used as the argument, we can exploit the potential of Gate: resolving based on type, multiple policies, etc. For example, we define a rule on modifying objects which implement `BelongingContract` of `Illuminate\Contracts\Auth\Authenticatable`. So we don't have to duplicate the logic in cases like: an user updates a comment or an author deletes his article.

``` php
class BelongingPolicy
{
    public function modify(Authenticatable $user, BelongingContract $thing)
    {
        return $user->id === $thing->user_id;
    }
}
```

We can also implement a "pipeline" to check the ability and arguments against policies, like middlewares you know. The type-check can be done by using e.g `class_implements()`, Reflection.
I would appreciate hearing your opinions on this. Thank you.

**Comment by KonstantinKolodnitsky** [comment]
I'm highly support this!

**Comment by KonstantinKolodnitsky** [comment]
My solution
https://laracasts.com/discuss/channels/laravel/can-gate-resolve-interfaces

**Comment by themsaid** [comment]
Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.

**Comment by ronlinet** [comment]
> Thank you for your suggestion, but looks like not enough members are interested in such change so I'm going to close this issue.

I politely disagree with the above comment. 
This issue is not about supporting the idea, it is about design improvement. 
Lack of Interface Resoliving in Gates is knocking out the whole Repository Pattern Methodology where the Developer cannot reuse the Contracts and have to choose between rewriting the SQL logic directly in gates or bypassing the Contracts and initiating the Repository Classes directly in gates. 
Initiating the Repository Classes directly in Gates without using the Interfaces is breaking the Repository Pattern standards. 
Such an advanced OOP tool as Laravel should consider this issue.  
Regards,
