### ISSUE TITLE
Deprecating changes for 1 release instead of removing

### ISSUE THREAD

**Issue by barryvdh** [laravel/internals#383]
What do you feel about 'officially' deprecating methods that are to be removed? (Where reasonably possible).

For example:
> share Method Removed - The share method has been removed from the container. This was a legacy method that has not been documented in several years.

Instead of removing them directly, can't we deprecate them first, for a single release?
Similar to Symfony; http://symfony.com/doc/current/contributing/code/conventions.html#deprecations

> A feature is marked as deprecated by adding a `@deprecated` phpdoc to relevant classes, methods, properties, ...:
```php
/**
 * @deprecated since version 2.8, to be removed in 3.0. Use XXX instead.
 */
```

> A PHP E_USER_DEPRECATED error must also be triggered to help people with the migration starting one or two minor versions before the version where the feature will be removed (depending on the criticality of the removal):
```php
@trigger_error('XXX() is deprecated since version 2.8 and will be removed in 3.0. Use XXX instead.', E_USER_DEPRECATED);
```

So trigger a silent deprecation error, and add a custom error listener to show them only in dev mode, log them, show them in de debugbar etc.

This would ease the transition between upgrades for application AND packages.

(And if a half year is too long, perhaps start deprecating them half-cycle as they occur, so you will at least receive them earlier)

**Comment by franzliedke** [comment]
Sounds like a very good idea for a project the size of Laravel, especially considering its versioning scheme. :+1:

**Comment by Garbee** [comment]
> (And if a half year is too long, perhaps start deprecating them half-cycle as they occur, so you will at least receive them earlier)

I'd love this. If we know something is deprecated with the next version, why not go ahead and mark it as such in the currently supported versions as well? This way even those minor updates to existing systems starts to provide developers feedback about what to expect in the future.

**Comment by RemiCollin** [comment]
Big +1 on this. Especially for package maintainer, this would drastically reduces the time taken to catch up on every new release.

**Comment by mpociot** [comment]
Yes - please!

**Comment by viezel** [comment]
+1

**Comment by CristianLlanos** [comment]
👍🏻

**Comment by fergthh** [comment]
+1

**Comment by garygreen** [comment]
I would be against this because it would slow down the development of Laravel - I think being forced to deprecate something in one release before it's removed would be a step backwards and actually slow down updates. The fast moving pace of Laravel is what makes it stand out from something like Symphony and this suggestion adds a bit of a barrier to rolling out faster updates.

**Comment by Garbee** [comment]
It only adds a barrier in a few cases. Typically, anything "removed" is renamed or tweaked to be completed in a different way. So the methods can stick around, be deprecated but proxy the future code. Giving developers time to update their code without having to do a swift run-through and deep QA check to avoid oddball breakage.

For the few places where it would be a problem, we can handle those as they occur in a meaningful way to let developers know problems will occur in future updates.

**Comment by franzliedke** [comment]
@garygreen I don't use Laravel because of its "fast moving pace". I like its philosophy, its expressive code and its rich feature set. In fact, breaking changes annoy me.

IMO, frameworks like Symfony and, for example, Ember.JS, that have a well-thought-out deprecation process, show that it is possible to stay innovative and keep moving ahead without frequent breaking changes - even in the JS ecosystem, which likes to move at breakneck speed.

A changed process would lead to different behavior, and likely would result in new features etc. being more carefully considered in terms of their longevity. From my perspective, that's a good thing.

**Comment by jbrooksuk** [comment]
> @garygreen I don't use Laravel because of its "fast moving pace". I like its philosophy, its expressive code and its rich feature set. In fact, breaking changes annoy me.

Did you know that you can lock your dependencies down to an explicit version? This shouldn't affect your position on Laravel, because it's up to you to manage your dependencies :)

**Comment by franzliedke** [comment]
Of course I do. How does that help me when I want to use new features but can't because old ones are changed?

**Comment by jbrooksuk** [comment]
That's up to you to manage as part of your upgrade paths.

**Comment by franzliedke** [comment]
Well, I appreciate @barryvdh's suggestion. Laravel has obviously been leaning in the "meh, just go with it" direction for the last few years. I think it would be wise for such a widely-used project to acknowledge this wide usage (along with all its diversity), which includes developers that grow tired of so many updates, and don't always have the time / resources to do so - or have better things to do.

That's all. :)

**Comment by Toyinster** [comment]
Sensible suggestion - was thinking exact same thing on the Laravel 5.4 upgrade

**Comment by garygreen** [comment]
> Laravel has obviously been leaning in the "meh, just go with it" direction for the last few years.

You can lock your dependencies, nothing is forcing you to upgrade to new versions - and if you do, you should expect breaking changes.

Your "meh" comment makes it sound like Laravel has been reckless with it's upgrade process, but this is not the case. Breaking changes are always kept to a minimum - Laravel tries to follow semvar and will not introduce any clear breaking changes in patch versions.

A new major version which has new methodologies, or want's to get rid of a feature to do something better, should not be held back because it's forced to deprecate a feature one version beforehand. This is a way of stalling progress. The intentions are good, but I don't think it's necessary, especially when there is always a clear upgrade path via the docs for every major Laravel version, and again, nothing is forcing you to upgrade.

**Comment by barryvdh** [comment]
Laravel does not follow SemVer, but I know it tries to avoid BC breaks in mino versions when possible.
I don't want to slow down development, just whenever something becomes deprecated, clearly document it. And when possible, allow a transition period.

**Comment by garygreen** [comment]
> I don't want to slow down development, just whenever something becomes deprecated, clearly document it. And when possible, allow a transition period.

How is "allow a transition period" not going to slow development down? By allowing a transition period, i.e. one release, you *are* slowing development down. If the thing that want's to be changed needs complete removal/rewiring of a feature, you can only remove it not in the next version but version after - that is slowing down development, your staggering because of this change.

> just whenever something becomes deprecated, clearly document it.

Laravel does this already, it's called the upgrade notes. It's very detailed in all the things that are breaking and need changing, plus gives hints on new improved ways of doing things where possible.

**Comment by LKDevelopment** [comment]
Ahm no that is clearly wrong. Not all Breaking Changes are documented in the Upgrade Notes. Such Things like the rename of TestReponse->seeJson() to assertJson() or something else aren't documentated.

**Comment by garygreen** [comment]
> Ahm no that is clearly wrong. Not all Breaking Changes are documented in the Upgrade Notes. Such Things like the rename of TestReponse->seeJson() to assertJson() or something else aren't documentated.

Probably just overlooked - I agree it should be documented. I'm sure Taylor would happily accept a PR to mention it on the upgrade guide.

This is a sensible suggestion but I just don't feel it's needed, I'm just seeing it from the point of view of - I want shiny new things in the next major version of Laravel, I don't want my shiny thing to be held back because of this "deprecate it for one release" law. If there's a way around that, I'm all for it.

**Comment by barryvdh** [comment]
Just a few examples where you could have a deprecation message before removing:
 - Container `share`, could have been deprecated and then removed in favor of singleton
 - Session `set`, (could point to `put`)

And where aliases could be used:
 - Router `middleware` -> `aliasMiddleware`
 - Router `getParameter()` -> `parameter`
 - Collection `every` -> `nth()`
etc

And I agree that this doesn't make much sense for apps, but for packages it can be a bit annoying, on every new version it just breaks a bit. Would be a lot more relaxing if more just keeps working but people can report/fix deprecated errors in 6 months instead of rushing out `version_compare` or `method_exists` hacks..

**Comment by garygreen** [comment]
@barryvdh 

All of those were mentioned in the upgrade guide. Package developers (such as yourself) shouldn't just +1 their `composer.json` without checking what's actually going to break. As soon as those methods are going to be deprecated, maybe they could be added in the patch version so at least if you did a composer update you'll get a notice, though I don't think removal should be stalled for one version.

Anyway, I'm clearly outnumbered here given all the +1's and -1 in my name, so I'll let other's chip in their thoughts. 😄

**Comment by barryvdh** [comment]
Yeah well multiple issues were added only after it broke and we noticed it wasn't yet documented..

**Comment by garygreen** [comment]
> after it broke and we noticed it wasn't yet documented..

Well if that's the case then that's bad. The upgrade guide is the single source of truth for what is breaking, so it should definitely be documented. 

On reflection we did actually have similar problems when `lists` was removed from collection and query builder, that is another example that could have been deprecated beforehand and would have saved a bit of headache. I think if it's not going to cause headaches to deprecate something for one reason, then 👍

**Comment by Jeroen-G** [comment]
> How is "allow a transition period" not going to slow development down? By allowing a transition period, i.e. one release, you _are_ slowing development down.

No, you are not. The moment a new Laravel version is released, everyone wants to go develop with its new shiny things. If package X depends on a function that is removed it would take more time before that package can be used on the new Laravel version. If the function gets deprecated, the X's maintainer can issue a compatible release the same day and have more time to work on a replacement of the deprecated function without slowing down the development of its users.

**Comment by garygreen** [comment]
I think we're talking about different things here. I completely agree that deprecating smaller changes is worthwhile, I'm talking about a bigger feature that requires something to be breaking and won't work in the next version without it. Then you are delaying shiny feature X because of this deprecation rule. I'm all for this change if it doesn't delay development, that is all.

**Comment by Garbee** [comment]
The rule should only apply to things that can be aliased. The recommendation is for *methods* that get modified. Typically, there is a way to allow the previous name/signature while still having the new stuff as well. Which means the deprecations are generally always applicable to be kept around for one release once the decision is made. We aren't talking about things like the bus system rework where it went from dual-class to self-handling.

Although, any interface/class *renames* would also be nice to leave a deprecated alias item in place for a version. As was done before for the `SelfHandling` interface iirc.

**Comment by RyanThompson** [comment]
No brainer - have to properly deprecate if you want to move forward and not burn bridges. Take note from Symfony.

**Comment by taylorotwell** [comment]
We will attempt to deprecate removals for 1 release in the future.

**Comment by jbrooksuk** [comment]
Nice!
