### ISSUE TITLE
Move the integrated test package to it's own repository / project

### ISSUE THREAD

**Issue by sileence** [laravel/internals#4]
The idea is to move everything under src/Illuminate/Foundation/Testing to its own repository.

That way it would be a new package / library included by default as a dev-dependency in the laravel/laravel project. 

Advantages: 
- Adapters for multiple versions of Laravel, even the old ones (4.2, 5.0)
- When migrating a project from, let's say 5.1 to 5.5 the same testing package with the same API, etc. will be available for both, so it is more powerful and reliable.
- Testing is a dev-dependency, no need to deploy it.
- Can be easier to maintain / organise, since it will have its own repository, issues, PRs, etc. 
- Could even have adapters for non-laravel projects. 
- laravel/testing sounds good

**Comment by franzliedke** [comment]
I think adapters for other projects would indeed be cool.

**Comment by hootlex** [comment]
+1

**Comment by jrmadsen67** [comment]
just spent part of today trying to bring the latest Testing from Laravel into Lumen - definitely in favor of this!

**Comment by taylorotwell** [comment]
This will most likely be done. Closing this since I've already started working on it.

**Comment by Modelizer** [comment]
@taylorotwell `Integrated` package consist with many testing support which also include Selenium. Are you planning to integrate Selenium as well when you build a new repo for `src/Illuminate/Foundation/Testing` as @sileence suggested?

My thought is to make this [package](https://github.com/modelizer/selenium) a base and create a new package for BDD testing. Example Selenium with Behat.

Sounds good? because I need to plan the way you are comming up with :)
