### ISSUE TITLE
[Proposal] Add Builder methods "orWhereYear" and "orWhereMonth" for convenience

### ISSUE THREAD

**Issue by jlmmns** [laravel/internals#404]
It would be helpful to have methods like `orWhereYear` and `orWhereMonth` for convenience.

**Comment by brayniverse** [comment]
Do you mean similar functionality to the magic methods `->where{$column}($value)` (e.g. `->orWhereEmail('foo@bar.com')`) or are you implying the date value should be parsed and compared (e.g. `->orWhereYear(2016)` if db value is `2017-01-01`)?

**Comment by jlmmns** [comment]
@brayniverse The date value should be parsed and compared.

Example:

`$builder->whereYear('date', 2016)->orWhereYear('date', 2017);`

To query on the `date` field to be in either 2016 **OR** 2017.

Same thing for `whereMonth` & `orWhereMonth`,
and `whereDay` & `orWhereDay`.

**Comment by brayniverse** [comment]
So underneath, it'll do something like this.

```SQL
SELECT * FROM users WHERE year(created_at) = 2017 OR year(created_at) = 2016
```

Is this possible in other supported grammars? i.e. Postgres, SQLite, etc...

**Comment by jlmmns** [comment]
@brayniverse Exactly.

Not sure about the other database drivers, though.

**Comment by brayniverse** [comment]
Looks like `year()` is not available in SQLite. However there is a `strfttime()` function.

http://stackoverflow.com/questions/33688263/sqlite-filter-records-by-month-year

**Comment by brayniverse** [comment]
This Macro will give you the functionality for the time being.

```php
Builder::macro('orWhereYear', function ($column, $value) {
    $this->orWhere(\DB::raw("year({$column})"), $value);
});
```

**Comment by garygreen** [comment]
I would be against adding this, not because it's not useful but because it adds yet another thing to maintain in the query builder. Others would end up saying where's the `whereDay` or `whereNotLeapYear` blah. If you find it useful, just do it in a macro in your own app, like @brayniverse has suggested 👍

**Comment by ntzm** [comment]
@garygreen There is already a `whereDay` [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L1041).

It does seem strange that there is `whereDay`, `whereMonth` and `whereYear` but no "not" methods. If anything they should be added for consistency's sake

**Comment by brayniverse** [comment]
@ntzm submit a PR if you want. It might be a bit difficult to make it work across all db grammars so that will probably be a nuisance for Taylor to maintain, and based on that he may decline the PR. If that's the case, create a third-party package with any useful generalised `Builder` macros you make. _Similar to what Spatie have done here https://github.com/spatie/laravel-collection-macros_
