### ISSUE TITLE
suggestion: array controller-method syntax in router

### ISSUE THREAD

**Issue by terion-name** [laravel/internals#419]
It would be very convenient to add route action syntax like `[LoginController::class, 'login']`. With complex routes `['uses' => [LoginController::class, 'login'], middleware ...]`. Entire framework moved from raw strings to` ClassName::class` style, this is very convenient, so here it will fit too

**Comment by priimailma** [comment]
Then you would have to import the controllers in your routes file or refer to the full namespace.

```php
['uses' => [App\Http\Controllers\Auth\LoginController::class, 'login'], middleware ...]
```

**Comment by terion-name** [comment]
@priimailma I don't see a problem in importing classes. This is made in two clicks in any IDE

**Comment by Garbee** [comment]
Importing is a non-issue. In fact, that is in some cases highly encouraged so you can do static analysis over your codebase to see where things are used. Otherwise, tooling can't be sure if the controllers are being used or not.

Personally I've hacked around this for a while. What I do is actual route provider classes that get called in the service provider to setup routes. They inherit from a base class which provides a static `uses(string $controller, string $method) : string` method that returns them concatenated with the `@`.

**Comment by Garbee** [comment]
Toying around with this idea just now it is actually very weird the way callables work. Implementing something like this will need a good benchmark set to run against to make sure no performance regressions are introduced.

The problem is, for callables you can't just pass in a class name and method and have it work. That only works when dealing with *static* methods. For non-static methods you need to pass an *instantiated object* into the callable. This is clearly undesirable as we don't want to create thousands of object instances just to register routes in larger applications. So, internally when we are running the callable we'd need to detect if the method being called is static or not. Then if not static create the object instance on-the-fly internally using the application container.

The same slight problem happens when you are getting the route signature parameters from the action. We'd need to check if the action is callable. If it is, then we need to reflect the class and see if the method exists. If not, then we check against the `__invoke` method otherwise we check the specified method's signature.

This is all just adding support in, not even making sure we don't somehow inadvertently break anything existing.

**Comment by ntzm** [comment]
I would like see this as well, I've always disliked the `ControllerName@method` syntax because it feels like a wrapper around something that PHP can natively do anyway.

**Comment by Garbee** [comment]
PHP doesn't do this without a possible gigantic performance impact. As using standard callables means the route's can't be cached since you can't rely on the listing since that would also cache the parameters, which would suck for FormRequests for example.

I'm working on a patch for this, but it is a hack on top of what PHP provides internally to keep things performant.

**Comment by terion-name** [comment]
@Garbee there is nothing to do with callables. This syntax, I suggest, will change absolutely nothing in router, it's just added syntax variation. Router breaks `Controller@method` string by `@` symbol, appends namespace to `Controller` and gets the same `['Namespace\Controller', 'method']` that is exactly the same as `[Controller::class, 'method']`. So it requires only one change  in route parsing, all further processing will be left as it was

**Comment by Garbee** [comment]
The problem is it is a callable syntax. Which people would still take could be used. So we need to make sure that works the same as well. Which, my patch does. So standard PHP works fine *and* we get the benefit of using methods on dynamic objects as well.

I understand that a simpler version could be done, however that then leads developers to thinking normal callables could be used as well when they in fact could not. My attempt at fixing this makes sure people have as many ways to use the router as they wish.

**Comment by terion-name** [comment]
@Garbee callable syntax for object methods requires to pass `object` as first array item, not classname. Using such construct as callable will try to invoke class `static` method. 
I don't see any confusion here, it's obvious that these are not native callables. 
Moreover it would be dumb to use callables in routes because you will need to construct objects for very every controller, with all their dependencies, that will have a huge performance impact, instead of using classname strings (`::class`) to lazy load only resolved route controller

**Comment by Garbee** [comment]
That's exactly what I was saying @terion-name. :wink: Good thing I have it figured out in a way that allows callable support *and* lazily-loading dynamic methods. So you aren't constructing objects until necessary, yet still allowing static methods to be used when you only need to return simple data that doesn't have dependencies.

<details>
<summary>Patchfile</summary>

```patch
From 726af440250bddaed464f26006cba9d8a30ba912 Mon Sep 17 00:00:00 2001
From: Jonathan Garbee <jonathan@garbee.me>
Date: Sat, 18 Feb 2017 10:34:55 -0500
Subject: [PATCH] Ability to use callables for router uses.

---
 src/Illuminate/Routing/Route.php       | 22 ++++++++++++++++++++++
 src/Illuminate/Routing/RouteAction.php |  5 ++++-
 src/Illuminate/Support/Str.php         |  6 +++++-
 tests/Routing/RoutingRouteTest.php     | 25 +++++++++++++++++++++++++
 tests/Support/SupportStrTest.php       |  1 +
 5 files changed, 57 insertions(+), 2 deletions(-)

diff --git a/src/Illuminate/Routing/Route.php b/src/Illuminate/Routing/Route.php
index 7ccec1b..babc038 100755
--- a/src/Illuminate/Routing/Route.php
+++ b/src/Illuminate/Routing/Route.php
@@ -4,6 +4,7 @@
 
 use Closure;
 use LogicException;
+use ReflectionClass;
 use ReflectionFunction;
 use Illuminate\Support\Arr;
 use Illuminate\Support\Str;
@@ -185,6 +186,27 @@ protected function runCallable()
     {
         $callable = $this->action['uses'];
 
+        if (!is_object($callable)) {
+            $controllerName = $callable[0];
+            $methodName = $callable[1] ?? '__invoke';
+            $controller = new ReflectionClass($controllerName);
+
+            if ($methodName && $controller->hasMethod($methodName)) {
+                $method = $controller->getMethod($methodName);
+                if ($method->isStatic()) {
+                    return $callable(...array_values($this->resolveMethodDependencies(
+                        $this->parametersWithoutNulls(), $method
+                    )));
+                }
+
+                return $this->container->make($controllerName)->{$methodName}(
+                    ...array_values($this->resolveMethodDependencies(
+                        $this->parametersWithoutNulls(), $method
+                    ))
+                );
+            }
+        }
+
         return $callable(...array_values($this->resolveMethodDependencies(
             $this->parametersWithoutNulls(), new ReflectionFunction($this->action['uses'])
         )));
diff --git a/src/Illuminate/Routing/RouteAction.php b/src/Illuminate/Routing/RouteAction.php
index 678806b..580bf17 100644
--- a/src/Illuminate/Routing/RouteAction.php
+++ b/src/Illuminate/Routing/RouteAction.php
@@ -39,7 +39,10 @@ public static function parse($uri, $action)
             $action['uses'] = static::findCallable($action);
         }
 
-        if (is_string($action['uses']) && ! Str::contains($action['uses'], '@')) {
+        // If the uses property is a string we check that it has a callable structure.
+        // The dynamic invocation will be set if the string is not a callable item.
+        // This provides a full uses property for the rest of the routing engine.
+        if (is_string($action['uses']) && ! Str::contains($action['uses'], ['@', '::'])) {
             $action['uses'] = static::makeInvokable($action['uses']);
         }
 
diff --git a/src/Illuminate/Support/Str.php b/src/Illuminate/Support/Str.php
index bdce3fa..cb52e73 100644
--- a/src/Illuminate/Support/Str.php
+++ b/src/Illuminate/Support/Str.php
@@ -191,7 +191,7 @@ public static function words($value, $words = 100, $end = '...')
     }
 
     /**
-     * Parse a Class@method style callback into class and method.
+     * Parse a Class@method or static style callback into class and method.
      *
      * @param  string  $callback
      * @param  string|null  $default
@@ -199,6 +199,10 @@ public static function words($value, $words = 100, $end = '...')
      */
     public static function parseCallback($callback, $default = null)
     {
+        if (static::contains($callback, '::')) {
+            return explode('::', $callback, 2);
+        }
+
         return static::contains($callback, '@') ? explode('@', $callback, 2) : [$callback, $default];
     }
 
diff --git a/tests/Routing/RoutingRouteTest.php b/tests/Routing/RoutingRouteTest.php
index 8ecebb8..2aef9fb 100644
--- a/tests/Routing/RoutingRouteTest.php
+++ b/tests/Routing/RoutingRouteTest.php
@@ -893,6 +893,26 @@ public function testInvalidActionException()
         $router->dispatch(Request::create('/'));
     }
 
+    public function testCallableAction()
+    {
+        $router = $this->getRouter();
+
+        $router->get('/', ['uses' => ['Illuminate\Tests\Routing\RouteTestControllerStub', 'index']]);
+        $router->dispatch(Request::create('/'));
+
+        $router->get('/', ['uses' => ['Illuminate\Tests\Routing\RouteTestControllerStub', 'staticIndex']]);
+        $router->dispatch(Request::create('/'));
+
+        $router->get('/', ['uses' => 'Illuminate\Tests\Routing\RouteTestControllerStub::staticIndex']);
+        $router->dispatch(Request::create('/'));
+
+        $router->get('/', ['uses' => [ActionStub::class]]);
+        $router->dispatch(Request::create('/'));
+
+        $router->get('/', ['uses' => ActionStub::class]);
+        $router->dispatch(Request::create('/'));
+    }
+
     public function testResourceRouting()
     {
         $router = $this->getRouter();
@@ -1256,6 +1276,11 @@ public function index()
     {
         return 'Hello World';
     }
+
+    public static function staticIndex()
+    {
+        return 'Hello Static World';
+    }
 }
 
 class RouteTestControllerMiddlewareGroupStub extends Controller
diff --git a/tests/Support/SupportStrTest.php b/tests/Support/SupportStrTest.php
index 4716859..d13d182 100755
--- a/tests/Support/SupportStrTest.php
+++ b/tests/Support/SupportStrTest.php
@@ -91,6 +91,7 @@ public function testParseCallback()
     {
         $this->assertEquals(['Class', 'method'], Str::parseCallback('Class@method', 'foo'));
         $this->assertEquals(['Class', 'foo'], Str::parseCallback('Class', 'foo'));
+        $this->assertEquals(['Class', 'method'], Str::parseCallback('Class::method'));
     }
 
     public function testSlug()
```

</details>
