### ISSUE TITLE
What's the release cycle for read-only packages?

### ISSUE THREAD

**Issue by ntzm** [laravel/internals#422]
I use a couple of the read-only packages like [illuminate/database](https://github.com/illuminate/database) on some projects, but it seems that releases only happen a couple of times per major version. In a project that I am working on at the moment I need to have at least [5.4.11](https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md#v5411-2017-02-10), but I can't bring it in using the version number because the latest release illuminate/database is only 5.4.9. Obviously I could use a commit hash or whatever but I would prefer to have a stable release but also get future minor versions.

What's the protocol on updating these? And is there any way this can be automated? I know it would be a pain for the maintainers to go and make a new release for every minor change for every single illuminate/* package, but I would definitely find it useful!

Thanks :)

**Comment by franzliedke** [comment]
The Illuminate components are released when their source is changed in a laravel/framework release. 

To use them safely, you can just use a `5.4.*` constraint in composer.json.

**Comment by ntzm** [comment]
@franzliedke That only gets me 5.4.9, not the latest version

**Comment by sebastiandedeyne** [comment]
Hmm odd, the latest tagged version is indeed 5.4.9, I always thought they were in sync too.

https://packagist.org/packages/illuminate/database

**Comment by franzliedke** [comment]
Then that means there have been no changes to the database component since Laravel v5.4.9.

**Comment by Garbee** [comment]
Which isn't correct, the tagging is out of date.

As of writing ( February 19th ):

1. Last db tag was [16 days ago](https://github.com/illuminate/database/releases) which was February 3rd.
2. Database component has had [commits since then](https://github.com/laravel/framework/commits/5.4/src/Illuminate/Database) upstream in `laravel/framework`. At least one of which [modified executing code](https://github.com/laravel/framework/commit/cf9822aff2f37d27464dcdbc917bc8c7a30986b3#diff-b235776bc0ece6213c96e138c611c82b).
3. That should have been in the `5.4.12` tag from [4 days ago](https://github.com/laravel/framework/releases).

So it seems quite clear that something isn't updating the tags as it should if it should be automated on any change within a component.

**Comment by franzliedke** [comment]
That probably means something went wrong during the release. /cc @taylorotwell 

My [original comment](https://github.com/laravel/internals/issues/422#issuecomment-280853198) still stands.

**Comment by ntzm** [comment]
Really would like some clearance on this. Seems all of the read-only packages are on 5.4.9 which is really annoying for me.

**Comment by RemiCollin** [comment]
I can confirm this happening here as well. `composer require illuminate/database` from an empty composer project resolves to `5.4.9` at the moment we speak.

**Comment by ntzm** [comment]
All illuminate/ packages have been updated. Would still be nice to know why they aren't updated every version

**Comment by tomschlick** [comment]
@ntzm was most likely a bug with the git split [scripts seen](https://github.com/laravel/framework/tree/5.4/build) here not running correctly

**Comment by taylorotwell** [comment]
This is automated now.

**Comment by ntzm** [comment]
Thanks for the update!
