### ISSUE TITLE
Merge .env.dusk instead of replace when running Dusk tests

### ISSUE THREAD

**Issue by sahibalejandro** [laravel/internals#429]
- Laravel Version: 5.4.*

### Description:
I know this is a Dusk related issue, but I think the changes need to be made into the Laravel Framework and the Dusk package as well.

It would be nice to detect when Dusk tests are running and **merge** the variables in `.env.dusk` and `.env`.

This is helpfull when you only need to change a few variables when running Dusk tests.

Let's say I have this `.env` file:

```
APP_ENV=local
DB_CONNECTION=mysql
DB_DATABASE=my_awesome_app
```

When running Dusks tests I want to **only** use a diferente database, would be nice to define **only** that variable in my `.env.dusk.local` file, like this:

```
DB_DATABASE=my_awesome_app_testing
```

And the resulting environment variables when running Dusk tests in the browser should be:

```
APP_ENV=local
DB_CONNECTION=mysql
DB_DATABASE=my_awesome_app_testing
```

Is that make sense?

At this time, you need to make a entire copy of your `.env` file to `.env.dusk` and then change only a few values, but leaving all the others same as the original `.env` file.

The related Dusk issue is here: https://github.com/laravel/dusk/issues/96

**Comment by franzliedke** [comment]
Not sure if this applies (I suppose it depends on what is stored in `.env`) - but I have had bad experiences with merging testing config with the local config (which is not version controlled) for tests.

This can sometimes lead to unreproducible behavior, because your local config affects some behavior of your tests that silently depended on the test-specific configuration. Then, these problems only appear when merging the test config with your local config, but not with your colleague's.

Again, not 100% sure whether this applies here, but I at least wanted to put out a warning. :-)

**Comment by themsaid** [comment]
Yes, miss 1 line and boom your database is gone :)

**Comment by sahibalejandro** [comment]
Well... it is your resposability to define all variables you need for your Dusk tests in your `.env.dusk` no matter if the `.env` is "merged" or "replaced".

My point is ¿why we need to copy the entire `.env` if just need to change one or two values?

Another example can be, as a project grows it is possible you add more values to `.env`, and each time this happen you need to add them to the `.env.dusk` file too, even if you need the same value for tests.

I really think that a merge will keep the `.env.dusk` file cleaner and more mantainable.

**Comment by skyrpex** [comment]
Looks like you care more about maintaining a file than unpredictability.
You shouldn't...

**Comment by sahibalejandro** [comment]
Hum... 🤔

I'm trying to see your point here.

When running normal tests, values defined in phpunit.xml are merged with the ones in .env, that should have the same side effects as mergin .env.dusk with .env ?
