### ISSUE TITLE
Better Tinker workflow

### ISSUE THREAD

**Issue by sebastiandedeyne** [laravel/internals#432]
If you want to use tinker to work on some code in a REPL workflow, you need to exit and restart the session every time to have your code changes come through.

Would it be interesting to be able to execute a command as an argument to `tinker`, to avoid having to exit/restart the whole time?

```
> php artisan tinker "App\\User::first()->doSomething()"
...
> php artisan tinker "App\\User::first()->doSomething()"
...
```

instead of...

```
> php artisan tinker
> App\\User::first()->doSomething()
...
<ctrl+c>
> php artisan tinker
> App\\User::first()->doSomething()
...
```

**Comment by skyrpex** [comment]
I swear that I felt the need for this more times than I can remember.

**Comment by salomoni** [comment]
I would love to have something like this

```
> php artisan tinker
> App\\User::first()->doSomething()
>
> reload()
>
> // Laravel application refreshed
> App\\User::first()->doSomething()
```

I have no clue how the artisan has implemented so would this be even doable?

**Comment by brayniverse** [comment]
@salomoni that might be an issue if you have a helper function called `reload()`.

**Comment by calebporzio** [comment]
I think about this all the time...

**Comment by calebporzio** [comment]
So, I've been digging into this pretty deeply. I think it may just not be possible. You would have to refresh composer's autoload file (I think) then create a fresh app instance, then create a shell from that instance and run it. It would open a new tinker instance anyway which is way less cool. 

I'm convinced at this point "hot-reloading" tinker is not a possibility. Therefore we should explore other options to make this common problem a little less icky. 

Only thing I can think of is somehow grabbing the history of tinker since you opened it, closing, re-opening and running those commands. Although, re-running commands automatically could be seriously dangerous, especially in a production scenario.

I think our best bet is something just auto-restarting tinker. It would be awesome if that could live in an artisan command, but I'm not getting my hopes up that tinker can restart itself...

**Comment by taylorotwell** [comment]
I'm not sure this is even possible.
