### ISSUE TITLE
When namespaces begin with `\` they should reset.

### ISSUE THREAD

**Issue by MrMashy** [laravel/internals#434]
I had a discussion at Laravel/Framework/#18078

I've created the code for it in a pull request. You can read the discussion and pull request and get back to me.

**Comment by skyrpex** [comment]
Clickable link to the discussion [here](https://github.com/laravel/framework/issues/18078). Can't find the pull request, though.

Anyway, I think that we should find a solution to the underlying problem. You can't currently define routes by calling helpers. Example:

```php
// routes/web.php

// This is broken because will try to register routes to App\Http\Controllers\Skyrpex\MyController
Skyrpex\MyRouteRegistrar::registrer();
```

```php
// vendor/skyrpex/MyRouteRegistrar.php

namespace Skyrpex;

use Illuminate\Support\Facades\Route;

class MyRouteRegistrar
{
    public static function register()
    {
        Route::get('do/awesome/things', MyController::class.'@doAwesomeThings');
        Route::resource('things', AnotherVendoredController::class);
    }
}

// vendor/skyrpex/MyController.php

namespace Skyrpex;

class MyController {
    // ...
}

// vendor/skyrpex/AnotherVendoredController.php

namespace Skyrpex;

class AnotherVendoredController{
    // ...
}
```

I admit that handling leading slashes may not be the ideal solution. I think that the `namespace` option of the router and the string shorthand 'Controller@method' is an antipattern. Instead, I propose removing that behavior and allowing something like this:

```php
// routes/web.php

Route::get('show/me', [
    'use' => [App\Http\Controllers\ShowController::class, 'show'],
]);

Route::post('do/awesome/things', [
    'use' => [Skyrpex\MyController::class, 'doAwesomeThings'],
]);
```

This has the following pros:
* Can use PHP's `use` statements to write less (so no `namespace` option is needed).
* Enables autocompletion for your IDE.
* Allows declaring routes with helper functions inside any routing group without breaking (since we removed the `namespace` option).

The cons (IMO, of course):
* Removing the namespace option is a breaking change. Anyone that relies on it would hate me for a while.
* Declaring routes will be more verbose.

**Comment by MrMashy** [comment]
Hi, Skyrpex

Thanks for the input.

I want to know why you think handling leading slashes isn't an ideal solution, I've implemented it in my project and it works perfectly fine... In PHP, you enter the global namespace by putting a `\` infront of namespaces/classes.

This is just adding it to laravels namespace transformer, which I think should be in there.

Here's the code I changed if you want to test it in your projects:

`Illuminate\Routing\RouteGroup.php`
```php
   /**
     * Format the namespace for the new group attributes.
     *
     * @param  array  $new
     * @param  array  $old
     * @return string|null
     */
    protected static function formatNamespace($new, $old)
    {
        if (isset($new['namespace'])) {
            if (substr($new['namespace'], 0, 1) == '\\') {
                return trim($new['namespace'], '\\');
            }
            return isset($old['namespace'])
                    ? trim($old['namespace'], '\\').'\\'.trim($new['namespace'], '\\')
                    : trim($new['namespace'], '\\');
        }

        return isset($old['namespace']) ? $old['namespace'] : null;
    }
```
In all my projects there is no breakages

**Comment by MrMashy** [comment]
[Here is the pull request](https://github.com/laravel/framework/pull/18081)
