### ISSUE TITLE
[Question] Is request object singleton?

### ISSUE THREAD

**Issue by pankitgami** [laravel/internals#440]
Is request object singleton?
If so then I am having weird behaviour with request object.

```
public function index(FormRequest $request) {
    	$request->merge(['test' => 'test']);

	var_dump($request->get('test')); // This prints test
	var_dump(Request::get('test')); // This prints null
}
```

**Comment by joshmanders** [comment]
`$request` is a new instance of `FormRequest`.

**Comment by pankitgami** [comment]
If I do the same i.e merge something in request object and access it through request facade, in middleware it is giving me same result.
Shouldn't it return `test` on both the case??

@joshmanders This means request is not singleton right??

**Comment by joshmanders** [comment]
The `Request` facade is a singleton, if you create a `FormRequest` then the container injects a new instance of it, so it's not the same.

**Comment by pankitgami** [comment]
I guess not..
Because if I merge something in request object in middleware. I am not being able to fetch it through `Request` facade in my controller.

**Comment by sisve** [comment]
The answer is no; Request is not a singleton. You're seeing this behavior because the FormRequest instance and the Request instance are two separate instances.

**Comment by pankitgami** [comment]
If laravel is providing `Request` facade, shouldn't it be singleton??

**Comment by sebastiandedeyne** [comment]
`FormRequest` and `Request` are two different classes. Are you sure you're using a `Request` object in your middleware, and not a `FormRequest` ond?

**Comment by pankitgami** [comment]
@sebastiandedeyne Sorry, I checked middleware is working correctly with `FormRequest` as well as `Request`. 

I agree both are different classes but `FormRequest` is a sub class of `Request` class. Shouldn't it share the same `get` and `merge` method? 

In an ideal case, if I merge something in `FormRequest` using `this` means I am merging parameters in `Request` object and it should be accessed by `Request` facade.

**Comment by SamAsEnd** [comment]
@pankitgami **No**, but i understood what you mean

The `$request` parameter you got and the `Request::` facade works with different objects and both are not singletons.

I hope it's not bulky but let me share what i found out.

```php
// SomeMiddleware.php
public function handle($request, Closure $next)
{
    $request->merge(['middle' => 'ware']);
    return $next($request);
}

// SomeController.php
public function index(SomeRequest $request)
{
    $req = app(Request::class);

    $req->merge(['app(Request::class)' => 'test1']);
    $request->merge(['SomeRequest' => 'test3']);
    \Request::merge(['\Request::' => 'test4']);
    request()->merge(['request()->' => 'test5']);

    dd($req->all(), $request->all(),\Request::all(),request()->all());
}
```

and guess what was the output

```php
array:4 [▼
  "middle" => "ware"
  "app(Request::class)" => "test1"
  "\Request::" => "test4"
  "request()->" => "test5"
]
array:2 [▼
  "middle" => "ware"
  "SomeRequest" => "test3"
]
array:4 [▼
  "middle" => "ware"
  "app(Request::class)" => "test1"
  "\Request::" => "test4"
  "request()->" => "test5"
]
array:4 [▼
  "middle" => "ware"
  "app(Request::class)" => "test1"
  "\Request::" => "test4"
  "request()->" => "test5"
]
```

As you see only the `FormRequest` deviate from your expectation because it's is a fresh new instance of `SomeRequest` class. 

The `Request::` Facade, the `request()` helper function and the middleware `Request` parameters are all kinda pulled out of the service locator but laravel can't inject the `Request` object it has in it's container in the type hinted (`SomeRequest`) parameter because only children classes can morph into their parent class not vise versa. 

So laravel clones the request object (check [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L34)) and inject it your controller. 

Even if the `FormRequest` class inherit from the `Request` class, as you clearly see the `FormRequest` object is a new instance created (or cloned) from the `Request` object from IoC which was bind [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Http/Kernel.php#L140) 
from the instance instantiated [here](https://github.com/laravel/laravel/blob/master/public/index.php#L53).

You also mentioned you couldn't fetch a value you merged in a middleware.
That's probably because you didn't assign the middleware for that route (I actually have added the `SomeMiddleware` in the web middleware group).

I hope it was clear. Thanks

**Comment by pankitgami** [comment]
@SamAsEnd Thanks for providing a detailed description of how `Request` and `FormRequest` works in Laravel.

I completely understand why data merged through `FormRequest` are not fetch by `Request` object. 
As both, the classes share the `ParameterBag` class to store the request parameter. Couldn't we create some way to solve this issue?

**Comment by SamAsEnd** [comment]
I think laravel could rebind the clone instance for `app('request')` when it **inject** the form request

**Comment by vedmant** [comment]
There is a catch, facade will work as singleton, means if you access request with `Request::` you will always get the same object. That's because facade caches all objects accessed through it https://screencast.com/t/MboUZJL2UQj . I personally think it's confusing, as there is no difference if you bind singleton on not trough container, using facade will always return singleton.
