### ISSUE TITLE
Adding a "getByIndex()" method on collections

### ISSUE THREAD

**Issue by Numline1** [laravel/internals#446]
I've recently encountered a situation with an array similar to this one:

```[1 => 'Lorem', 4 => 'Ipsum', 5 => 'Dolor', 7 => 'Sit']```

I ended up needing the 3rd item from the mentioned array/collection, which in this case, is 'Dolor'. There are several ways to approach this:

- Using get(2), I'm not sure how this behaves, but I'd assume it searches for the key name
- Re-sorting the collection to reset the keys (problem: user may want to keep the original keys)
- Using slice(2, 1) and then first() to get the specified item (problem: slightly too long)

My proposal is to add getByIndex() method (the best naming I was able to come up with using my potato english), which would simplify the retrieval of the previously mentioned item. I believe using the slice and first method could be the answer, so we'd just end up with a wrapper method.

I'm willing to create the PR of course, I was just wondering if this is the right way to go.

Regards,
Martin

**Comment by Garbee** [comment]
`get` is looking for the key name. So `get(2)` in that instance should return `null` since the `2` key doesn't exist.

If the keys don't matter it would be best just to re-key right away. Or you could call `values` before `get` to get a new collection of only the values (keyed then by integers starting at 0) and you can call what you want via `get` that way.

Slicing in this scenario seems a little quirky and I'm not sure in what cases you know the indexes unless you are manually indexing them using `indexBy` or the like. So, I'm not entirely sure where the proposed solution really comes in handy with many applications.

**Comment by Numline1** [comment]
Hey @Garbee, you're indeed right about the get() behaviour. As far as using values() or sort() or something similar goes, that would do what I'm trying to achieve at the cost of re-creating the array (hence filling some additional memory I'd assume). If slice() works the way I think it does, it avoids the issue with array duplication entirely and just iterates through the original array. This may be useful if we work with an array that has several thousands of entries (just in theory :]), although I'd assume people don't usually access those by a key.

My specific scenario where I needed to use the slice(1, 1)->first() was Dusk/Facebook Web Driver, where I had to go more low level and collect table's <tr> elements. There were about 15 rows, each having 5 columns (<td>). I was aware at which position the specific content was, however it was only possible to access it by a key without mapping each <td> to a key. I could iterate through each of the 15 rows and access the second or third column.

This is very a edge-case scenario, but perhaps it could be useful somewhere else as well (that's what I'd like people to discuss in this topic :]).
