### ISSUE TITLE
aseertSee() throws entire html

### ISSUE THREAD

**Issue by lcjury** [laravel/internals#448]
I'm trying to write FeatureTest with the following code:

```
public function testViewIndexPosts() 
{
    $post = \App\Post::create(['name' => 'Primer Post']);                                                                                                 

    $this->get('/posts')
            ->assertSee($post->name);
   }
```

Now, this test fails becouse inside the post controller I have the following:

```
public function index()
{
    $posts = \App\Post::all();
    return view('post.index', compact('posts'));
}
```

and I don't have created the post.index template file. But when I run the test, inside the terminarl I get all the html output of the error. It would be better to get just the error displayed there and not all the html.

**Comment by Garbee** [comment]
What is a way this could be solved without changing the existing output? A CLI flag perhaps or a different method to run that toggles dumping the markup?

I personally find seeing the output extremely useful in some cases to see what the code is generating in order to know what my code is doing for the given test. I'd wager others find it useful in different cases. So best not change the existing method but add a new one or some CLI flag can be used to hide the output if you're never interested in it.
