### ISSUE TITLE
Add concept of 'eval' view parts

### ISSUE THREAD

**Issue by garygreen** [laravel/internals#452]
Wonder what you guys think of this - it's an idea to improve rendering performance when it comes to 'static dynamic' type content in views. For example, often you generate routes / urls in views:

```php
<a href="{{ route('users.index')}">
```

This will compile into:

```php
<a href="<?php echo route('users.index'); ?>"
```

However - if you think about it, this shouldn't really ever change and could be eval'd and become the actual link in the compiled view

```php
<a href="http://www.mysite.com/users">
```

This could work for a number of things, like `url()` and other content that is 'dynamic' yet 'static' in nature - it won't work for everything, but could be a nice improvement.

Something like:

```php
<a href="@eval(route('users.index'))">
```

**Comment by Garbee** [comment]
This wouldn't work in a *large* number of scenarios. Like, anything with a dynamic route parameter. I think it best we not introduce anything like this since it would be only useful to developers in a small set of cases and that could be confusing as to when to use it. The extra overhead for the routes that are static wouldn't make a difference in most applications. If you're at the level where it would matter, you'd be maintaining that another way anyways.

:-1: It's just an unnecessary micro-optimization.

**Comment by sisve** [comment]
This is already supported-ish in "userland" code by writing a custom blade directive. You could write a `@route('users.index')` that does this.
