### ISSUE TITLE
[Proposal] New validation rule - like alpha_dash and spaces

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/internals#473]
I thought it will be awsome if we could make new validation rule like `alpha_dash_spaces` so it can validate 
alpha_dash plus spaces, for me it was usefull when I want to validate someones name (not user name) , but can't use alpha_dash.

If you're interested, I can provide the code with tests and all other things that you need, but most of it is done here http://blog.elenakolevska.com/laravel-alpha-validator-that-allows-spaces/

**Comment by michaeldyrynda** [comment]
This is a specific use case that can easily be solved using the [regex](https://laravel.com/docs/5.4/validation#rule-regex) rule. Something like `regex:/[a-z\- ]+/i` should serve this case; I wouldn't create a new validation rule for it.

**Comment by Dylan-DPC** [comment]
alpha_dash already exists.

**Comment by vladyslavstartsev** [comment]
@michaeldyrynda ok, thanks for answering.

**Comment by chronofish** [comment]
@vladyslavstartsev : I personally wouldn't give up on this.  While it is a specific use case, one could argue all of the convenience rules are specific and can be solved via regex.  I've needed this exact functionality in the last 3 Laravel projects that I've created and my solution was to extend the validation rules set to include the "alpha_dash_spaces" option

**Comment by virtualmix** [comment]
I'm in the same situation. I'd like to allow for my users to register with either their real name (alpha_space) or a made-up username (alpha_dash). I believe this is a common use case and a modern trend based on the websites I visit.
 
The documentation for registering a custom validation rule is very lean and by the time I fully understand how it works I will likely be a couple of hours into implementing this functionality. I'm also reluctant in adding my own features to the framework since future Laravel updates could break them.

I just wanted to voice my opinion in case someone is considering to reopen this issue.
Meanwhile I will use the "string" validation rule. 

Thanks all.

**Comment by ludo237** [comment]
Create a new Rule or a private package... It's not like Laravel has the duty to solve all the validation issues. I've create so many custom rules and you can find a plethora of FOSS packages about them
