### ISSUE TITLE
Queue without listeners (background/cron)

### ISSUE THREAD

**Issue by barryvdh** [laravel/internals#49]
Currently, there is a simple DB driver, but this still requires to setup a listener (and monitor that the process keeps running). For small sites, I usually find that there are some tasks that are slow and can be done using queues, but setting up the listeners + supervisor seems unnecessary complex.

Using the DB driver, we can have 2 alternatives:
- Push to background, using a process in the background (eg. `php artisan queue:work $id > /dev/null 2>&1 &`. Fires directly (like `sync`), but isn't blocking. Downside: not 100% crossplatform. Example: https://github.com/barryvdh/laravel-async-queue
- Schedule by cron. Instead of running directly, the cron scheduler calls a command to process the existing tasks in the queue. This isn't instantly, but every minute (or as often as the cron is run).
  This is also what Magento does for sending emails.

These two methods are not for 'heavy' sites, as they probably don't scale as well, but for simple sites it can be easy to just push emails to the queue without any additional config (aside from setting up the cron once). Both options can use the database driver. 

The cron idea seems relatively easy to implement without configuration. What do you think?

**Comment by tomschlick** [comment]
You should be able to do the cron option like this

```php
$schedule->command('queue:work')->everyMinute()->withoutOverlapping();
```

**Comment by tomschlick** [comment]
On second thought you'd probably have to add a loop there since `queue:work` only processes one job at at time. So if you had 5 jobs in your queue it would take 5 minutes to process.

**Comment by barryvdh** [comment]
Yeah so it would probably just have to be something between the 1-time worker and the deamon. Eg, work all jobs until finished, then exit (instead of keep running).
(Not sure however if we could just run the worker in deamon mode without overlapping, and have it act as a regular listener?)

**Comment by tomschlick** [comment]
Yeah I'm thinking it would be as simple as adding a `--once` parameter to the daemon params where when it would normally go to sleep for x seconds it just exits.

**Comment by tomschlick** [comment]
Looks the the interrupt could happen right after this line https://github.com/laravel/framework/blob/5.2/src/Illuminate/Queue/Listener.php#L105

**Comment by barryvdh** [comment]
Yes or keep the worker running as long as the `job` key in the result from runWorker is not null. https://github.com/laravel/framework/blob/2eb5551b92a89ae2481fbf9aaf2ecee7aa1b4c45/src/Illuminate/Queue/Console/WorkCommand.php#L107

**Comment by JosephSilber** [comment]
Instead of pushing to a background process, can't we just do it in a terminate middleware?

**Comment by barryvdh** [comment]
According to the notes here, this isn't reliable for all configurations:
http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-terminate-event

> Internally, the HttpKernel makes use of the fastcgi_finish_request PHP function. This means that at the moment, only the PHP FPM server API is able to send a response to the client while the server's PHP process still performs some tasks. With all other server APIs, listeners to kernel.terminate are still executed, but the response is not sent to the client until they are all completed.

So that could improve the `sync` drivers for some some users (probably the default on Forge/Homestead anyways), but not valid in all cases.

**Comment by zmorris** [comment]
I agree with @tomschlick, the queue currently has queue:listen and queue:work, but what we really need is a way to tell either of these to run in one-shot mode (--once) to process all queue items and then exit.  My current setup is:

crontab:
`* * * * * php /path/to/artisan schedule:run 1>> /dev/null 2>&1`

app/Console/Kernel.php->Kernel->schedule():
`$schedule->command('queue:work --daemon')->everyMinute()->withoutOverlapping();`

I would prefer to use a setup like this:

crontab:
`* * * * * php /path/to/artisan schedule:run 1>> /dev/null 2>&1`

app/Console/Kernel.php->Kernel->schedule():
`$schedule->command('queue:listen --once')->withoutOverlapping();`
or:
`$schedule->command('queue:work --daemon --once')->withoutOverlapping();`

The first uses one request per item and the second uses one request for all items (to save resources).  Ideally it might be nice to limit the number of items with a timeout or max number of items to process, but I digress.

The solution I'm using currently works, but the issue is that starting and stopping the queue requires a series of additional commands like `ps -fe | grep '[a]rtisan'` to get the queue process id and kill it.  A one-shot (--once) mode would allow turning the queue on and off by simply commenting the artisan line in the crontab and allowing the queue to run till completion.

**Comment by bjoern-tantau** [comment]
Why not use the best of both worlds and start the daemon through cron? You would have to collect its PID and save it to a lockfile. On cron execution check if the PID is still running, if it is, exit, and if it isn't start a new daemon and save the new PID in the lockfile.

It would give ease-of-use for small sites but still allow setting up the daemon through systemd or whatever for advanced users.

**Comment by Kyslik** [comment]
Any news on this?

**Comment by taylorotwell** [comment]
I don't have a great idea for this off the top of my head. If someone comes up with something feel free to PR it if it's clean and simple.

**Comment by jonnott** [comment]
+1 for this

**Comment by jonnott** [comment]
How about just an artisan command that can be triggered via crontab (e.g. every minute, every 5 minutes, whatever the project owner decides), and processes everything on the queue (that's due to be processed) until it's done. The existing 'overlapping' features would prevent a subsequent running of the cron task from processing the same jobs (if they took e.g. > 1 min), right?

**Comment by barryvdh** [comment]
Yeah you should probably only need to add a flag to exit the deamon when it's done with it's current tasks, like @zmorris said. 
But the be honest, running queue jobs with the cron might be a bit slowish and bad practice. Eg. you will have to wait for max 1 minute on reset password mails etc. And Forge makes it much easier to manage Supervisor.
And there is still https://github.com/barryvdh/laravel-async-queue ofcourse.

**Comment by jonnott** [comment]
Something based on something here? https://gist.github.com/mauris/11375869

**Comment by barryvdh** [comment]
You can already do 'withoutOverlapping()' in Laravel.

**Comment by jonnott** [comment]
@barryvdh So are you saying that if you ran, say, 'artisan queue:listen' from the Scheduler (via a cron task 'artisan schedule:run', say each minute), and used withoutOverlapping(), Laravel will already take care of making sure artisan queue:listen isn't already running when the Scheduler is next run via cron?

**Comment by barryvdh** [comment]
Yes I think so

**Comment by jonnott** [comment]
@barryvdh If your original post you specify queue:work rather than queue:listen. To my knowledge, queue:work only processes one queued job per run, so if your app generates more than 1 job per minute on average, the queue processing would never keep up. But with queue:listen, then queue 'listener' is running in the background continuously, and if it stops for some reason, the Scheduler task (running every minute via cron) would start it up again. Is this correct?

**Comment by sisve** [comment]
@jonnott It sounds like you've mixed up queue:listen and queue:work. The queue:work command, with the default daemon mode, will execute several jobs within the same instance of the framework. It will shut down based on other logic, like signals or memory usage.

**Comment by jonnott** [comment]
@sisve If daemon mode is 'default', then how come when I run from the command line manually, with many jobs waiting on the queue, it only processes one at a time..
`
fusionms@*.org [~]# cd ~/app
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:08] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:10] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:12] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:14] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:16] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:18] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
[2018-03-20 09:31:19] Processed: Illuminate\Queue\CallQueuedHandler@call
fusionms@*.org [~/app]# php artisan queue:work
fusionms@*.org [~/app]# php artisan queue:work
fusionms@*.org [~/app]#
`

**Comment by sisve** [comment]
I would guess that you're running an older version of Laravel. Daemon mode is default since ... 5.3, iirc. Try running `php artisan queue:work --daemon` to enable it in your version, if it exists at all.

**Comment by jonnott** [comment]
@sisve You're right...

<pre>fusionms@missionstyles.org [~/app]# php artisan -V
Laravel Framework version 5.2.29
fusionms@missionstyles.org [~/app]#</pre>

--daemon does exist, but as an optional flag..

**Comment by jonnott** [comment]
@sisve ..and there's no --once flag yet ;)

**Comment by simonhamp** [comment]
Been mulling over this for a while as we're in a similar situation to @barryvdh (don't want to go through the trouble of setting up Supervisor etc).

So as a very quick solution, we opted to do the following in `app/Console/Kernel.php`:

```
protected function schedule(Schedule $schedule)
{
    $schedule->command('queue:restart');

    $schedule->command('queue:work');
}
```

`queue:restart` tells any existing workers to gracefully shut down. `queue:work` in some configuration will then boot up new daemon workers.

It's not ideal to keep shutting down and starting up workers every minute, granted, but there's potential to write some logic that determines whether workers need to be shut down and new ones started.

I'll be monitoring this over the next few weeks to see how it performs. Early signs are that it's working quite well.

**Comment by Izazkhan** [comment]
@simonhamp So, after weeks, How its performance is? is it Good to You, i think it would be good enough ;)

**Comment by simonhamp** [comment]
@izazkhan it’s working just fine for our workload so far. We haven’t experienced any problems.

**Comment by KeithTurkowski** [comment]
Here's what I'm using inside of Kernel.php

```
        $schedule->command('queue:restart')->hourly();
        $schedule->command('queue:work --sleep=3 --timeout=900 --queue=high,default,low')->runInBackground()->withoutOVerlapping()->everyMinute();
```

**Comment by jonnott** [comment]
> Here's what I'm using inside of Kernel.php
> 
> ```
>         $schedule->command('queue:restart')->hourly();
>         $schedule->command('queue:work --sleep=3 --timeout=900 --queue=high,default,low')->runInBackground()->withoutOVerlapping()->everyMinute();
> ```

@KeithTurkowski Can you explain the logic behind each of your options/flags and commands?

**Comment by KeithTurkowski** [comment]
@jonnott Sure.

The first line: I'm using "queue:restart" to shut down (it doesn't actually restart) all queue:work instances that are running for the Laravel installation, including any that might be running from the console. It runs once an hour. It also stops them "gracefully", which means they finish processing the current job before stopping, unlike using a "kill -9" command.

The second line: I'm using "queue:work" to start running the queue again. I'm using it instead of "queue:listen", because "queue:restart" doesn't shut down "queue:listen" instances (I will explain why this is problem when I explain "withoutOverlapping"). It can be nicer to use "queue:listen", as it reloads completely for each job it processes, and you don't have to worry about memory leaks. However, for that same reason, "queue:work" is more efficient and runs faster.

I'm using "--sleep 3" to tell the "queue:work" instance to check every 3 seconds (once the queue is empty) for new jobs. It's an arbitrary number, and if a mail job (for example) is added to an empty queue, it will take up to 3 seconds before it processes, and sends.

I'm using "--timeout=900" to tell the queue to let jobs run up to 15 minutes before stopping the job, and retrying it again. I have some jobs that can several minutes, so this is a reasonable number for me. Note: it's important to write long running jobs like this in such a way that they can be safely stopped and restarted.

I'm using "--queue=high,default,low" to set the priority at which jobs will be handled. All "high" jobs will be processed first, then "default", then "low". Under config/queue.php the default queue name is "default", (and I didn't change anything there) so when jobs are "dispatch"ed without "onQueue" method, they will go into the default queue. I add my longer running jobs using: "Job::dispatch()->onQueue('low')".

I could probably duplicate the second line a few times, and add multiple "queue:work" instances to focus on specific queues or sets of queues (e.g. a queue:work with only "--queue:high"). That would be more robust, as long running "low" priority job could start right before a "high" priority job is added, and it could be 15 minutes before the job finishes, and "queue:work" checks and finds the "high" priority job.

I'm using "runInBackground" because the "queue:work" will continue running indefinitely, and unless it's the last line of the scheduler, I believe it will block further scheduling. I specifically do not use "runInBackground" for the "queue:restart", as I want it to complete before the "queue:work" starts, although I'm not 100% sure it won't stop the "queue:work" that is started immediately after.

I'm using "withoutOverlapping" to prevent more than one instance of the "queue:work" from running (as my scheduler is called from cron every minute, and I don't want another "queue:work" to start again. I don't know exactly what would happen if I had two duplicate "queue:work" lines, if it would still only limit it to one instance, or each line would be treated as a separate instance (my guess is only one would run). I also don't know what happens if there are two separate "queue:work" lines with different parameters, (my guess is both would run). Now, as I mentioned before, because you can't shut down "queue:listen" with "queue:restart" (at least with the database driver), this is a problem. According to the documentation, "withoutOverlapping" locks expire after 24 hours. That means, if the "queue:listen" instances never crash, or stop, a new one will be added every day (I assume, unless the lock expiring causes the instance to stop running).

I'm using "everyMinute" to check every minute, and make sure the "queue:work" instance is still running, and if not, start it again. In my experience, queue worker instances will randomly get shut down or crash every few hours or days (I assume that a crash / shutdown will immediately expire the "withoutOverlapping" lock, but I haven't actually verified that).

In my case, I often have jobs added right after the hour mark (when all "queue:work" instances are shut down). This allows me to spawn additional "queue:work" instances that I call using the "--stop-when-empty" (so they terminate once the job queue is empty). Because they start right after the hour mark, they will run up to ~59 minutes before the scheduler "queue:restart" shuts them down.

This system has worked for me so far, but I'm not an expert, I'm just basing this off what I've read.

**Comment by iBelit** [comment]
how to set cron jobs in cpanel for this? with "ea-php72"?

**Comment by KeithTurkowski** [comment]
This is my  Cron job:
```
* | * | * | * | * | cd /home/user/laravel/app_root && /usr/local/php72/bin/php-cli artisan schedule:run >> /dev/null 2>&1
```

This is my updated code inside Kernel.php (Laravel 5.8):
```
$schedule->command('queue:restart')->hourly();
$schedule->command('queue:work --sleep=3 --timeout=900 --tries=254 --delay=600 --queue=high,default,low')->runInBackground()->withoutOverlapping()->everyMinute();
```

I added "--tries=254", as the table limit for the field is 255, and it will generate an error if a job reaches 255 failed attempts, and stop the rest of the queue from processing. I also added the Laravel support for failed_jobs table, so if a job fails 254 times it will be stored there instead of deleted.

I added "--delay=600" as my email sending jobs would sometimes have trouble connecting, and it was causing the jobs to fail until smtp/etc. started working again. This way, the jobs retry every 10 minutes (for a little under 2 days) before they are moved out of queue to failed_jobs (instead of failing almost immediately if email services are temporarily down / restarting).

**Comment by htoomgt** [comment]
> You should be able to do the cron option like this
> 
> ```
> $schedule->command('queue:work')->everyMinute()->withoutOverlapping();
> ```
It is very nice idea. I think it is better than supervisor to use.

**Comment by howtomakeaturn** [comment]
My solution is:

```
$schedule->command('queue:restart')
    ->everyFiveMinutes();

$schedule->command('queue:work --daemon')
    ->everyMinute()
    ->withoutOverlapping();
```

Currently it is working. 
Will try a few days to see if there's any issues.

**Comment by fchienvuhoang** [comment]
+1 for this

**Comment by j7550155** [comment]
```php=
$schedule->command('queue:work database --queue=testQueue --tries=3 --sleep=3')
   ->withoutOverlapping() 
   ->everyFiveMinutes();
$schedule->command('queue:restart')
   ->hourly();
$schedule->command('test') //send some log ->"test schedule"
   ->everyFiveMinutes();
```
i'm using laradock and configure this above code ,and this code work fine.
During this time of execution this "test schedule" the terminal below shows multiple programs open about this above schedule code,i'm confused is this normal?Can someone explain 
```shell=
laradock 25821  0.0  0.0   4504   180 ?        Ss   06:16   0:00 /bin/sh -c /usr/bin/php /var/www/curl/artisan schedule:run >> /dev/null 2>&1
----------------
laradock 25823  0.0  2.9 371768 17820 ?        S    06:16   0:00 /usr/bin/php /var/www/curl/artisan schedule:run
----------------
laradock 25830  0.0  0.0   4504   180 ?        S    06:16   0:00 sh -c '/usr/bin/php7.3' 'artisan' queue:work --queue=testQueue  > '/dev/null' 2>&1
----------------
laradock 25831  0.0  2.9 371768 17388 ?        S    06:16   0:00 /usr/bin/php7.3 artisan queue:work --queue=testQueue
----------------
laradock 26051  0.0  0.1   4504   704 ?        Ss   06:27   0:00 /bin/sh -c /usr/bin/php /var/www/curl/artisan schedule:run >> /dev/null 2>&1
----------------
laradock 26054  1.9  6.3 371768 37736 ?        S    06:27   0:00 /usr/bin/php /var/www/curl/artisan schedule:run
----------------
laradock 26061  0.0  0.1   4504   708 ?        S    06:27   0:00 sh -c '/usr/bin/php7.3' 'artisan' test > '/dev/null' 2>&1
----------------
laradock 26062  6.0  6.2 371768 37372 ?        S    06:27   0:00 /usr/bin/php7.3 artisan test
```

**Comment by woodongwong** [comment]
> You should be able to do the cron option like this
> 
> ```
> $schedule->command('queue:work')->everyMinute()->withoutOverlapping();
> ```

If our application is a cluster deployed on multiple servers, using `withoutOverlapping` will cause `queue` to run on only one server, which is a Laravel design issue and we need the `withoutOverlappingOneServer` feature.

**Comment by jazz7381** [comment]
currently i use this for database driver:
```
exec('php ../artisan queue:work > /dev/null 2>&1 &');
$this->dispatch(new JobClass);
```

is this have a disadvantage?
