### ISSUE TITLE
Multi-tenant multi-database applications

### ISSUE THREAD

**Issue by philbates** [laravel/internals#53]
Building a Laravel application where each tenant has their own database is currently possible, but I feel like there's a lot of room for improvement, even if I'm not sure right now what exactly needs to change.

After discussing some of the issues faced in a multi-tenant multi-database application in laravel/framework#13109, I thought I would create a thread here so that we can discuss what the ideal way of solving this problem is, and see if we can find a way in which Laravel can more easily support multi-tenant multi-database applications.

Off of the top of my head, here is some issues faced with this architecture:
- Each tenant needs their own storage directory. Some storage files could be shared, but some such as cache, upload etc should definitely not. This also breaks the new `public` disk, as it is no longer a case of simply creating a single symlink from `public/storage` to `storage/app/public`.
- What is the ideal way to store and retrieve the database credentials of each tenant? The most common way right now seems to be to store them in a `master` database in a `tenants` table, retrieve the details based on host name (or however you match a request to a tenant) and force a database re-connection.
- Migration rollback. For me this is the big issue, demonstrated by example:
  1. I have a tenant with the following migrations in their database:
     
     | migration | batch |
     | --- | --- |
     | 2016_01_01_create_users_table | 1 |
     | 2016_02_01_create_blogs_table | 2 |
  2. I add a new tenant on 2016-03-01 and create a new database for them:
     
     | migration | batch |
     | --- | --- |
     | 2016_01_01_create_users_table | 1 |
     | 2016_02_01_create_blogs_table | 1 |
  3. Migration rollback is now potentially very dangerous and destructive, as all it does it roll back the last batch: in the first tenant's case, it would roll back only `2016_02_01_create_blogs_table`, but in the second tenant's case, both `2016_01_01_create_users_table` and `2016_02_01_create_blogs_table` would be rolled back. Ideally some solution to roll back to a specific migration rather than the last batch would be better. Imagine a scenario with 500 tenants, and the 250th tenant's migrations go wrong. You may wish to roll back migrations for all tenants that have been migrated as part of that deployment to the state they were in before the deployment started. Right now this isn't possible. laravel/framework#12569 proposed the idea of migration tags, which seems like it could be a possible solution, but it was closed.
- The default artisan commands that interact with the database (migrations, seeds) all need to be modified to be able to either target a specific tenant's database, or loop over all database's.

Feel free to list other issues you've had trying to set up a multi-tenant multi-database application, and lets see if we can come up with any ideas as to how the core could be modified to make this easier for us.

**Comment by tomschlick** [comment]
Background queue jobs become more complicated as well. I have added a `useTenant()` method to my base jobs class that i pass in the current tenant when firing off the job.

All good points though, I have outlined how I have mine setup on this blog post: https://tomschlick.com/2015/11/29/lessons-from-building-multi-tenant-apps-part-1-databases/

**Comment by philbates35** [comment]
That's a good point. So do you have one queue worker daemon running per tenant, something like `php artisan queue:work --daemon --tenant=tenant-id`? I guess you would have to do this, especially when using the database queue driver.

**Comment by tomschlick** [comment]
No, All queue workers (currently 20 something) can run any tenants data. The tenant id is passed through as a data variable that is picked up at execution and the provider is switched just like a web request would be.

**Comment by philbates35** [comment]
When you say the tenant id is passed through as a data variable, any chance you could give me an example of what that looks like, and how you're storing the tenant id on the queue job? All I can think of is that you're passing the tenant id into the job class' constructor. Is that right?

**Comment by tomschlick** [comment]
I have a `useTenant()` method that I pass the tenant to on job creation
![](https://s3.amazonaws.com/tomschlick-screenshots/gmgiY2tisgzcz.png)

I pass it through like this
![](https://s3.amazonaws.com/tomschlick-screenshots/mD0M84IED0jAy.png)

**Comment by tomschlick** [comment]
That useTenant() method is on the base job class btw

**Comment by philbates35** [comment]
Ah got you, makes perfect sense, thanks. Do you do the same thing on events that have queued listeners?

**Comment by tomschlick** [comment]
I'm not currently using any events in that way but yes I would employ the same method if/when I use those.

**Comment by philbates35** [comment]
Great, thanks. Although that would work, I definitely see having to manually do that every time you want to dispatch a job / fire an event is pretty annoying, and could easily be forgotten.

`Queue::before()` is called just before a queue job is started, so if there was a way to register additional data into a job (probably in a service provider) before every job is added to the queue, we could use that to append the tenant id into the data, and then use `Queue::before()` to retrieve the tenant from the additional data and configure the application to use that tenant for the job it is about to process. I think that makes sense... I'm not sure if that's possible right now though.

**Comment by tomschlick** [comment]
Queue::before & Queue::after run when the actual job is going to be executed, not when it's added to the queue (as far as i know). So you still need to add that tenant information to each queueable object before you put it in the queue. I'm sure we could come up with a much more elegant solution, for now this has seemed to work because I throw an exception if the tenant param isn't passed to a job.

**Comment by philbates35** [comment]
Yeah that's right, so if there was a way to register application meta data (in our case the tenant id) at the time the job was added to the queue, and then in `Queue::before()` we could retrieve that meta data (tenant id) and set the database connection etc.

Something like this (pseudo-code):

```php
public function boot()
{
    Queue::metadata(function() {
        return [
            'tenant_id' => app('tenant'),
        ];
    });

    Queue::before(function ($event) {
        $tenant = $event->metadata['tenant'];

        // Now that we know then tenant we can set database connection...
    });
}
```
I'm still not convinced this is the best solution, or would even work. The underlying point is that there needs to be some way to automatically store certain things about the state the application was in at the point something is queued without having to do it manually.

**Comment by legshooter** [comment]
This is a topic I'm longing for Laravel and Taylor to tackle with. I dare to say that most of us are building SaaS, and multi-tenancy is at the heart of it.

I've chosen to go with the multi-database approach as well due to its benefits, with the top three being: 
- Better performance for very large tables
- Better security with the ability to use different database users with different permissions for different databases
- Scale-friendly by being able to move a busy database/s to a different machine

In some sectors separate databases are not a recommendation but a requirement due to security concerns.

I think it is in the best interest of Laravel to offer concrete aid on this matter for its users, and it shouldn't be dismissed as another way-too-specific-use-case-for-us-to-care-about. It should benefit a meaningful share of Laravel users, If not today, then tomorrow.

Until that happens, we are on our own, and so I have tackled with some of these issues. It's an ongoing refactoring, but here's what I have so far:

## Connectivity

For tenant connectivity I setup a separate master database with a `tenants` table that holds all tenants' info, in columns such as `subodomain` (app), `domain` (custom), `db_host`, `db_name`, `db_user` etc.

I have an `IdentifyTenant` middleware running for each request, and the `handle` method looks like this:

```php
    config(['tenant' => $this->getTenant($request->getHttpHost())]);

    $this->setDatabaseConnection(config('tenant'));

    return $next($request);
```
`getTenant()` retrieves the tenant from the database/cache by extracting the request's subdomain / custom domain. I'm leaning towards using the cache since otherwise a database call gets executed for every request. So right before the tenant is retrieved, I set the cache prefix to the tenant's subdomain / custom domain. The tenant is then assigned to the `tenant` key in the `config` so I'd have access to its data throughout the request's life.

`setDatabaseConnection()` assigns connectivity info to the `database.connections.{$tenant['id']}` key in the `config`, and reconnects to this connection.

Oh, and a middleware seems better suited than a service provider, because it's easier to enable/disable this behaviour to different routes this way.  

## Migrations

I created a `TenantsCommandAbstract` which its entire job is to run an artisan console command for all tenants:

```php
protected function tenants(string $command, array $options = null)
{
    // Each option needs leading dashes when the command is called
    foreach ($options as $key => $value) {
        $options['--' . $key] = $value;
        unset($options[$key]);
    }

    $tenants = Tenant::all();

    $this->output->progressStart(count($tenants));
    $this->output->newLine(2);

    foreach ($tenants as $tenant) {

        $this->info("{$command} >> tenant id: {$tenant->id}");

        $options['--database'] = $tenant->db_name;

        $this->setDatabaseConnection($tenant);

        $this->call($command, $options);

        $this->output->progressAdvance();
        $this->output->newLine(2);

    }

    $this->info("Finished {$command} for all tenants.");
}
```

And then for each existing DB console command I created a small command relying on the abstract, the following way (comments removed for brevity):
```php
class TenantsMigrate extends TenantsCommandAbstract
{
    protected $signature = 'tenants:migrate {--database=} {--force} {--path=} {--pretend} {--seed} {--step}';
    protected $description = 'Run the database migrations for all app tenants.';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $this->tenants('migrate', $this->option());
    }
}
```

This allows me to `php artisan tenants:migrate` to migrate all databases, `tenants:migrate:rollback` to rollback all databases, etc. The same applies to seeding.

You've mentioned some of what is still ahead of me, like solutions for partial rollbacks, storage (S3 and the like) and queues. Haven't thought about those yet.

Hopefully the above will help explain our needs and inspire a Laravel Zonda™ solution, or at least gives people who read this some directions for their own projects.

**Comment by Luceos** [comment]
Multi tenancy isn't something that is all that easily accomplished, if you want to do it perfectly that is. And all tenancy situations are different anyway. For instance some people prefer having all tenants in the same database.

What I wanted to achieve with [my package](https://github.com/hyn/multi-tenant) is to be as unobtrusive and flexible as possible. In my case I wanted to keep all tenant data separated, so files and databases. All tenants files are by default stored in the `storage/multi-tenant` folder and database connections are set up during runtime, much like what @legshooter does.

What I've also assumed was that you would almost certainly have only one install of a SaaS on one machine (VM or otherwise), therefor I decided to integrate as closely to php, database and webserver. Your first point, how to symlink a tenants public folder I could easily fix by using [Apache](https://github.com/hyn/webserver/blob/master/views/webserver/apache/includes/server-block.blade.php#L29) or Nginx aliased directories. Using an alias a directory is virtually mapped from any directory to any public facing directory.

Your second point, how to store database passwords safely. That's a bit tricky, I would never ever persist cleartext database passwords in any database. So while implementing the tenant connections on the fly I decided to base it completely on an tenant identifier, which is hashed using the app Key. This allows for a secure way of working with your tenant databases.

Migrations had been a bit of an issue for me. As my goal was to be unobtrusive I decided to [overrule them](https://github.com/hyn/multi-tenant/tree/master/src/Commands/Migrate) and add a tenant flag to the command itself, with a clean fallback if no tenant flag was given. However as was said before, it does not take into account what migrations has been executed on what database yet.

I hope this helps others, please note my package [hyn/multi-tenant](https://github.com/hyn/multi-tenant) is currently available only for the Laravel LTS (5.1) version.

**Comment by legshooter** [comment]
The current shape of my `IdentifyTenant` Middleware:

```
public function handle($request, Closure $next)
{
    $this->tenant->getByDomain($request->getHttpHost())->init();

    return $next($request);
}
```
As you can see, I've encapsulated all tenant logic to the `Tenant` Model.

For example, here's `Tenant::init()` from above:
```
public function init()
{
    $this
        ->connect()
        ->setAsSingleton()
        ->setCachePrefix()
        ->setAppSettings();
}
```
This allows me to conveniently initialize the tenant outside of HTTP, like in Console Commands or Jobs.

Here's an example of how I'm utilizing it in queued Notifications' extended parent:
```
class Notification extends BaseNotification
{
    public $tenantId;

    public function __sleep()
    {
        $this->tenantId = tenant()->id;

        return parent::__sleep();
    }

    public function __wakeup()
    {
        (Tenant::find((new ReflectionClass($this))->getProperty('tenantId')->getValue($this)))->init();

        parent::__wakeup();
    }
}
```
This way, anytime a Notification is being processed by the daemon, the tenant context is properly switched.

In case you're wondering, `tenant()` is a helper function that gets the `Tenant` instance I've set via `Tenant::setAsSingleton()`.

**Comment by taylorotwell** [comment]
I don't think Laravel will do anything out of the box for these type of multi-DB setups. However, I do want to make sure that we at least allow packages to do it. So, if there is something preventing packages from accomplishing this please let me know.

**Comment by pabloleone** [comment]
The problem with multitenancy is Listeners as far as I tested them. Jobs are queued in the right DB and the event is triggered using the right DB if you have them properly set up using the `connection` field in the queue connections config file.

As soon as an event arrives at the `handle` method the DB connection is not the selected anymore, the system is picking up the default DB connection. So we receive the event from the X database but into the listener, we only have access to the Y database!

**Comment by crabbly** [comment]
@pabloleone I have solved this by passing the tenant connection information to the event. Once the listener is processed, first thing it should do is to set the correct tenant connection, by accessing that information from the event.
