### ISSUE TITLE
[ Proposal ] Get list of events fired between two point.

### ISSUE THREAD

**Issue by pankitgami** [laravel/internals#530]
Currently, there is no way to get the list of events fired between two points in the code.
We have `DB::enableQueryLog()` and `DB::getQueryLog()` functions to get the log of the query runs between two points in code.

I am suggesting two functions `Event::enableEventLog()` and  `Event::getEventLog()` to enable logging for events and get the list of event fired and listeners which are bind to fired events respectively.

This will be very helpful in debugging the events.

**Comment by brayniverse** [comment]
Can you not use a wildcard event listener and temporarily store the event details somewhere?

**Comment by pankitgami** [comment]
Wildcard event listener will give me all the events happening in my application. But I don't want all the events. I want events happening between two point in code.

**Comment by brayniverse** [comment]
I've submitted a PR for this functionality. However, I feel an `Event::disableEventLog()` method is required, otherwise all events will be logged even after you're done with the log. I've asked for advice on how to implement this.

Out of interest, why do you need this functionality? If it's for testing purposes, could you make use of the [Event Fake](https://laravel.com/docs/5.4/mocking#event-fake) feature?

**Comment by brayniverse** [comment]
Taylor didn't think this was worth being a baked in feature, and recommended using a wildcard event listener.
