### ISSUE TITLE
artisan queue:down command for deployments

### ISSUE THREAD

**Issue by halaei** [laravel/internals#54]
I think there should be an easy way to deploy, while allowing for web requests, but stopping the queue workers.

Currently, inside forge for example, the only option to do this is to manually stop the workers before running deploy scripts and create them again after deployment, or maybe messing with cron.

I think 2 commands like `php artisan queue:down` and `php artisan queue:up` are required for that. I am sure that `php artisan queue:restart` is not the solution as suggested by @taylorotwell [here](https://github.com/laravel/framework/issues/5175)

**Comment by tomschlick** [comment]
Something like `queue:pause` and `queue:resume` might be better in this case vs up/down.

**Comment by alexbowers** [comment]
This is sorely needed if you have a HA setup with many servers.

**Comment by alexbowers** [comment]
I can look into an implementation sometime  this week, if anybody else has any input it'd be appreciated.

**Comment by sisve** [comment]
Isn't this what `supervisorctl stop all` and `supervisorctl start all` does?

**Comment by kslimani** [comment]
@sisve : the problematic here is that while deploying a job is maybe "processing". If you stop supervisor, you kill the job beeing processed.

I also propose that the `queue:restart` automatically resume queue in addition to restart queue worker daemons. (_maybe also add an optional `--no-resume` command line argument to force restart without resume : i don't see an immediate purpose, but may be usefull in some case_)

**Comment by sisve** [comment]
@kslimani No, supervisor sends`stopsignal` (default SIGTERM) and waits for `stopwaitsecs` seconds (default 10) before finally terminating the process with a SIGKILL signal. That means that, unless configured otherwise, all queue workers have 10 seconds to shut down cleanly.

This is already implemented if you have Laravel 5.4 and PHP 7.1. https://github.com/laravel/framework/blob/9357854e3c8f15c8b6738530b3158b12ee5f7f0c/src/Illuminate/Queue/Worker.php#L486-L488

It can be implemented in other versions of Laravel by listening for the Looping event (was 'illuminate.queue.looping') to check for an incoming SIGTERM signal and terminating when one is received.

Regarding your automatic restart feature; supervisor already has this feature; `autorestart=true`. This is also the configuration used in the example at https://laravel.com/docs/5.4/queues#supervisor-configuration

**Comment by kslimani** [comment]
@sisve you are correct about supervisor behaviour.
Though, i think in HA setup, you don't want to kill current running job while deploying, only signal workers to not process new incoming jobs in queue. (_this is where the `queue:pause` comes in action_)

When new code is deployed, the `queue:restart` fits perfectly, because it wait for current running job to finish before kill worker. (_unless i am missing something ?_) And the killed worker is automatically restarted by supervisor (_using new app fresh code_).

And if `queue:restart` auto "resume" worker by default, then you don't need to call `queue:resume` after restart.

To resume, when you deploy a new release of you application, you need to ensure that all running job (_which are using previous app code_) continue to run until finished. Then when job is done, the worker restart to use the new app code for process next incoming jobs. All of this without puting app in maintenance mode (_HA setup_).

**Comment by sisve** [comment]
I'm not sure where the high-availability setup becomes an issue. You mention `queue:restart` which restarts _all_ queue workers that share the same cache. The only way for you to limit it to your current server would be to use per-server cache drivers (`CACHE_DRIVER=file`), any other setup will restart queue workers on unrelated machines.

Assuming you're on the latest-and-greatest (Laravel 5.4, PHP 7.1) you already have support for the supervisor signals that tells the worker to shut down cleanly. I've set `stopwaitsecs=900` (15 minutes) for my workers that process long-running jobs. That means that a call to `supervisorctl stop all` will...

1. Run `supervisorctl stop all` to signal (SIGTERM) all workers to stop processing and quit.
2. Supervisorctl blocks until all processes have terminated. Processes that doesn't terminate for `stopwaitsecs` seconds will be forcefully (SIGKILL) terminated.
3. /* deploy stuff here */
4. Run `supervisorctl start all` 

The workers checks for incoming SIGTERM signal in every loop, and will exit as the processing of a job has completed. The workers will not terminate a currently executing job. The only way jobs would be terminated forcefully would be if they didn't complete in `stopwaitsecs` seconds, in which case supervisor would be the one killing it. (Another scenario would be that your job has been running longer than the max allotted time specified in `queue:work --timeout=...`, which would be a separate non-deploy related issue.)

To be clear; sending SIGTERM to a queue worker will gracefully shut it down.

**Comment by kslimani** [comment]
@sisve all what you describe is correct : Laravel + supervisor contains (_i think_) all required mechanics to gracefully stop or restart job worker.

The requested feature here is a command to signal workers to stop to handle next incomming jobs in listened queues (_but to continue with currently handled, if any_).

**Comment by sisve** [comment]
I still don't get it. Are you asking for a command that replicates what supervisor+queue:work does? Or does  a queue:pause+restart differ in some way from a supervisor stop+start?

**Comment by kslimani** [comment]
(_let's consider we only have one worker with a single queue_)

Requested feature is a `queue:pause` command  which signal the worker to stop to handle available jobs in queue.

In this state, if worker is running a job, then it will continue until job finished (or failed), then if there is a job available in queue, the worker will simply ignore it and sleep.

If `queue:resume` command is run then the workers will resume handling available jobs in queue.

I propose also that `queue:restart` command should also "resume" worker by default. (_with an optional --no-resume argument_).

**Comment by Kyslik** [comment]
I don't get it either, @sisve already made many comments about using `supervisord` to gracefully stop all workers. 

From that point you may start updating your application (except migrations, since application code in memory of any worker that is still running may use database).

After deployment is done just use `supervisord` to start workers as before. There is no need for `queue:pause` and `queue:resume`, `supervisord` takes care of it.

Maybe shed some light with real life example.

**Comment by kslimani** [comment]
_(i am not a queue expert and i may have missed some capabilities, please correct me if i am wrong)_

I would like to satisfy these conditions while deploying new PHP code :

* application is not in maintenance mode
* running jobs are not interrupted
* jobs in queue are not handled

To achieve this, i think, a possible solution is :

* run artisan `queue:pause`
* deploy php code
* run artisan `queue:restart`

If there is already a way to achieve this i would be happy to known.

**Comment by Kyslik** [comment]
When you have maintenance mode queues are not worked unless they are run with `--force` switch.

---

As @sisve already commented [here](https://github.com/laravel/internals/issues/54#issuecomment-293236839) it is possible using supervisord.

 - `supervisorctl stop all` (jobs that are processed at this moment are finished (handled) and no new queue job is taken because of SIGTERM just as `queue:pause` would do)
    - mind database changes during deployment, any long running job involving database may fail because schema will change after migrations are run during deployment rutine
 - deploy code
   - during deployment no workers exist
 - `supervisorctl start all` start all workers with new code base

>**Note**: queue workers use php code from memory so once started, code does not change just like `artisan tinker`.

**Comment by kslimani** [comment]
@Kyslik you are correct and i am aware of this behaviour.
But "application not in maintenance mode" is one condition i need to satisfy.

**Comment by Kyslik** [comment]
You don't need to put application in maintenance.

**Comment by kslimani** [comment]
Oh ? i supposed that maintenance mode make application return a 503 HTTP code.

I am gonna re-check the documentation.

**Comment by sisve** [comment]
Whether the application returns a HTTP 503 or not is irrelevant to the queue system (and this issue).

It sounds like you're asking how to do proper connection draining and stopping traffic to a web server while that server is being deployed to. What you are asking about would be a hosting configuration issue; and (in my view) should be done _without_ returning HTTP 503. Remember that your load balancer will take time to react to the new error code, and users will get HTTP 503 from that server until your load balancer has stopped sending traffic there.

Instead, communicate with your load balancer and say "don't send more traffic to this server"; wait for some time to let all existing requests finish (30-90 seconds are common), then you can close down nginx/fpm and do whatever you want. As the final step, tell your load balancer to "start sending traffic to the server again", and it would start sending traffic to your newly deployed server once it passes all your configured health checks (perhaps 3 successful http requests to /status-check).

**Comment by halaei** [comment]
Actually, I found that in order to implement this feature without changing the core laravel/framework package, one can listen to the `queue looping` event. Inside the listener, return `false` if you need to pause the worker, null otherwise. This looping event was a lot useful for me in other situations, so I sent a PR to document it a while ago. Check [this link](https://laravel.com/docs/5.4/queues#job-events) to see the docs.

Since not everyone agrees to put the feature inside the core, here is a not-tested code that let me implement `queue:pause` and `queue:resume` artisan commands via `Queue:looping`:

```php
Queue::looping(function() {
    if(Cache::has('laravel:queue:paused')) {
        return false;
    }
});

Artisan::command('queue:pause', function() {
    Cache::forever('laravel:queue-paused', 1);
});
Artisa::command('queue:resume', function () {
    Cache::forget('laravel:queue:paused');
});
```

**Comment by sisve** [comment]
@halaei Using the cache will fail if you have several queue workers all using the same cache. That means that all workers will be paused, instead of just the one being deployed to at the moment. It even involves workers handling different queues than the one you're deploying to. You're basically taking down your entire queue processing every time you deploy to a single server. That sounds really bad.

I do not understand why people want their php process running while you swap out the underlying source code during the deploy. Can someone tell me why they want the processes idle during the deploy, instead of stopping them? It does not make sense at all to me. Can someone explain this to me?

Seriously; you have to restart the queue process anyway since it needs to start using the newly deployed php code. So it has to go down sooner or later, before the deploy is finished. This solution, the idea to pause the worker, is just added complexity that attempts to solve a problem I have not yet understood. Again, can someone explain this to me?

**Comment by tomschlick** [comment]
Pausing / resuming the queue workers is useful for more than just deployments. Especially the ability to pause a single queue and allow the others to continue to proceed.

**Comment by sisve** [comment]
@tomschlick Nothing in this thread will help you with pausing a single queue, just perform an action on the queue workers on the current machine. Pausing a single queue would need a central queue controlling mechanism.

For example, if I run `queue:work --queue=default,pdf-generation,world-domination` and would want to pause he world-domination queue... well, that's not handled by anything in this issue (yet). This issue is about pausing the worker, so it will stop processing all three queues. The jobs in these queues may still be processed if other workers on other machines is still running.

So, your answer is currently out-of-scope. This issue is not (currently at least) discussing per-queue artisan commands, but per-worker artisan commands.

And if it was an attempt to answer my request for explanation; it didn't clear anything up. There's nothing in your answer that tells me why the worker needs to be paused but still running, compared to stopped totally.

To recap how the queue system works;
1. There is 1..n number of servers.
2. There is 1..n number of workers on every server.
3. There is 1..n queues handled by any worker.

And my simplistic view on the deploy to a server handling queues:
1. You connect to one server.
2. You stop all workers on this server _(this is where I seem to differ with many in this thread)_
3. You deploy
4. You start all workers on this server
5. You find next server to deploy to and start over..

So, you can have one server running one worker with one queue. That is the absolute simplest case. You can also have a dozen servers, running several workers per server, handling several queues per worker. You don't even have to have uniform configuration of your workers, you can have two of them processing queue A and twp of them B+C (using two process groups in supervisor). You can even have some of your workers use redis others the database, at the same time.

I am getting the vibes that people are only thinking of the "one server, one worker, one queue" scenario without having the other setup in mind. If I could ask something of you all, please consider "**two servers, two workers per server, two queues per worker**" when you discuss this issue.

For example, @halaei code requires that you have a per-server cache so that `Cache::has('laravel:queue:paused')` only works on the server you're on right now. Using the `CACHE_DRIVER=file` sounds logical, but would have issues if your deploy involves replacing the entire wwwroot with a new zip-file from you CI server. In which case the workers will start working again when you remove the file (the cache entry) representing laravel:queue:paused.

@tomschlick mentions "the ability to pause a single queue". Once again, easy to do with "one server, one worker, one queue", but requires some kind of central management of all queue drivers to work in other cases. I see some kind of solution where all queue drivers registers their work in a central queue-manager-thingie, perhaps backed by a database table, where you could toggle single queues on and off. It will probably be useful for many things, but it isn't really in-scope of this issue which talks about deploys. A deploy need to stop the processing of all jobs on all queues on the current server being deployed to.

So, I'm still in the mental state where I do not see why there would need to be a queue:down command when supervisor already has equal functionality (stop processing new jobs and finish currently executing jobs). Can someone explain it to me?

**Comment by taylorotwell** [comment]
The queue worker listens for the USR2 signal to pause and SIGCONT to continue.

**Comment by sisve** [comment]
@taylorotwell 

Your answer is hard to implement correctly, and you would still need to restart the worker to pick up on new changes.

I don't see how you could get away with a pause-and-continue, you would need a restart after the deploy to pick up changes to the source code, and thus it becomes a USR2+SIGTERM. But the pause itself is hard to do since you need to block the deployment until the pause is in effect in case a job starts autoloading new files. You don't want a job to start reading the newly deployed files while still running (partially) with old code.

The queue:restart command is still (semi-)unusable for any real cache setups since it restarts _all_ queue workers using the cache, not just the one on the machine currently being deployed to. Sure, restarting all the queue workers wont (usually) blow anything up, but it's just unnecessary actions done to other machines. Deploying to 10 servers means that you'll issue queue:restart 10 times, which is a total of 100 restarts of queue-workers if all servers restart their workers for every invocation...

The only safe way to deploy, in my view, is still to stop the queue workers using supervisor, and then start them again after the deploy.

**Comment by halaei** [comment]
I think I submit this issue before `queue:work --daemon` command has a --timeout option, so we where forced to use `queue:listen` instead. Currently, the daemon workers are super reliable so we just need a mechanism for daemons to pause or resume.
My personal preference would be listening to `Event\Looping` queue event and inside the listener return false if the queue should be paused. The event is documented here: https://laravel.com/docs/5.6/queues#job-events

This is the code we need (not tested):
```php
Queue::looping(function () {
    if (Cache::has('queue:paused')) {
        return false;
    }
});
Artisan::command('queue:pause', function () {
    Cache::forever('quque:paused', Carbon::now());
});
Artisan::command('queue:resume', function () {
   Cache::forget('queue:paused');
});
```

I love the hidden features of Laravel framework.

**Comment by sisve** [comment]
@halaei You have told us of that approach further up in this thread, and all the problems with it still persists.

> Using the cache will fail if you have several queue workers all using the same cache. That means that all workers will be paused, instead of just the one being deployed to at the moment. It even involves workers handling different queues than the one you're deploying to. You're basically taking down your entire queue processing every time you deploy to a single server. That sounds really bad.

Source: https://github.com/laravel/ideas/issues/54#issuecomment-293580447

Your solution only works if 1) you have a single server doing the queue processing, 2) or you're using the local file system cache so that servers don't share the same cache. The second point also requires that you do execute a cache:clear as part of the deployment steps, or replace the wwwroot folder, since that would remove the existing cache entries and the worker would start again.
