### ISSUE TITLE
[proposal] new functions for eloquent models

### ISSUE THREAD

**Issue by carusogabriel** [laravel/internals#552]
For new release of Laravel, is viable to have some Eloquent functions in `Model`class that facilitates the use of views, stored procedures and functions in database?

**Comment by Garbee** [comment]
Not really. Eloquent is about the tables relationship to the application. Not inner functions and procedures.

In the case of views, they should just act like tables. So make a model bound to the view. Not sure what extra special is needed there. Could you elaborate some more on that point? Possibly provide some detailed examples of what you're thinking should be allowed?

Thank you.

**Comment by carusogabriel** [comment]
I study more before elaborate an answer, sorry for the delay.

<b>First</b>: sorry about `Views`, now I know it's just necessary create a `Model` and attribute to it. 

Back to what my proposal is about: _facilitates_, _simplify_, make the code more _semantic_ and _pretty_ (because we're Artisans, right?). 

As can be seen in this questions in Stack Overflow ([1](http://stackoverflow.com/questions/30498227/how-to-call-stored-procedure-on-laravel), [2](http://stackoverflow.com/questions/34497063/how-to-execute-stored-procedure-from-laravel)), and in [this](https://laracasts.com/discuss/channels/laravel/run-mysql-function) Laracast Discuss, there's always the doubt if use `DB::statement`, `DB::raw` or `DB::select`, furthermore if the Stored Procedure is call by `exec` or `CALL`, and deeper, what if it has <b>parameters</b>, what's the best way to bind it?

My idea is to have two new `functions` in class `Illuminate\Database\Connection` (btw, (as I'm new in Laravel's world), is here the best place?) called, for example, `DB::procedure` and another called `DB::{someNameToCallFunction}` that standardize the `use`, `return` and `parameters` of procedures and functions.

What do you think?

**Comment by sisve** [comment]
> As can be seen in this questions in Stack Overflow (1, 2), and in this Laracast Discuss, there's always the doubt if use DB::statement, DB::raw or DB::select

Those links does not back up your argumentation. The Stack Overflow questions asks how to executed a stored procedure, and both ::statement and ::select works. It depends on what the stored procedure returns, and if you care about the result.

The third question doesn't really state anything. It's one guy with an unclear problem; he wants to execute a function and is having problem with the values passed into it. The function is called "varbintohexsubstring" and converts a varbinary(n) into a varchar(n) containing hex. But he isn't using a varbinary(n) value, he's sending in a php-variable as a string. He should probably just have used [bin2hex](https://secure.php.net/manual/en/function.bin2hex.php) instead.

Regarding your implementation of a `DB::procedure()`; there will be issues with databases not supporting procedures (at least sqlite).

Regarding `DB::{someNameToCallFunction}`, I prefer if it where moved somewhere else to avoid conflicts with existing (and future) methods. You could implement this as DBProcedures facade, but it could just be a class with static methods in your own app folder.

> standardize the use, return and parameters of procedures and functions

There will be _lots_ of quirks and odd cases you need to handle. My usage of procedures has been with SQL Server, so here's some fun things;

1. There is a variable number of parameters
2. Parameters are typed
3. Parameters can have default values. `EXEC example_prox @param = DEFAULT`
3. Parameters can be output-parameters that is used to return values. `DECLARE @holding INT; EXEC example_proc @param = @holding OUTPUT; SELECT @holding`
4. An output parameter can be a cursor (here be dragons!)
5. Table-valued parameters (more dragons!)
5. A procedure can generate a resultset (it executes a single SELECT)
6. A procedure can generate several resultsets (it executes several SELECT)

Writing a generic wrapper for procedures is complex. It's probably easier if you just write static wrapper methods in your own code base instead of trying to implement this as a framework feature.

**Comment by carusogabriel** [comment]
I'll study ways for my situation in this case, thanks folks :+1:

**Comment by carusogabriel** [comment]
I'll study ways for my situation in this case, thanks folks :+1:
