### ISSUE TITLE
trigger error if model column is missing

### ISSUE THREAD

**Issue by abumostafa** [laravel/internals#58]
There is a problem when you call any Elqouent model property and this property is missing you never get any warning, notice or exception

**Comment by pedrommone** [comment]
You get a `null` value, thats engought when some properties dont exists, no?

**Comment by a7mds3d** [comment]
what if you wrote the column/property name wrong. you still has no error

**Comment by sebastiandedeyne** [comment]
Not sure if this is a good idea. It would require for you to either declare your attributes beforehand or make a database call to find out which attributes are available.

E.g.

```
$post = new Post();
// Eloquent can't magically know which fields are available in the database table, we're just creating an empty object
```

**Comment by deringer** [comment]
Eloquent doesn't really have any knowledge of the database structure. You'd have to make a database call in order to get the fields on that model, and possibly cache them (how do you know when to refresh the cache?)

As @sebastiandedeyne mentions, an unhydrated model wouldn't have the information available either.

You could potentially implement the functionality as a trait, overriding the `getAttribute` method on the model. At that point, you have to consider any mutators (maybe you have other behaviour for a `null` field value), as well as any relations.

In any case, I don't think an error should be default behaviour.

**Comment by Garbee** [comment]
Also with this the `fill` method when just tossing form data into a model could cause issues. Even though the developer knows full well some columns don't exist and they handle those inputs after (or before) the data is filled.

**Comment by a7mds3d** [comment]
i agree with you guys. but we also break the behaviour of PHP object by calling undefined property and we. i think a notice will be more helpful

**Comment by Garbee** [comment]
So developers that know full-well they are filling in non-existant columns get notice spam?

How is this actually helping developers in a tangible way? Wouldn't proper unit tests make the need for this irrelevant?

**Comment by a7mds3d** [comment]
I don't mean assigning or creating the object i'm talking about calling undefined property.

`
$post = Post::first();
echo $post->foo; // foo isn't a column so there is should be a Notice undefined property
`

**Comment by jlaswell** [comment]
If something doesn't exist, it is `null`. The behavior is correct and does not gain any value by providing a warning or notice.

**Comment by happyDemon** [comment]
I'm with @Garbee & @jlaswell here, proper testing and/or validation can prevent this. a null value should be enough.

**Comment by a7mds3d** [comment]
thanks guys

**Comment by kjdion84** [comment]
It's better that it returns a `null` value rather than throwing an error, because if the attribute does not exist then it is the definition of `null`.

**Comment by tomaspekar** [comment]
`$data = new \StdClass;
dump($data->name);`
Standard StdClass throws ErrorException Undefined property: stdClass::$name

IMHO, this is better for mistypeing... for example:
`$user = User::find(1);
echo $user->naem; // returns null`
but you want `$user->name` and sometimes is dificult to find this bug, especialy in blade.

**Comment by Garbee** [comment]
>Standard StdClass 

stdClass is a very special class. Do you have another built in class that does this? No, because it's not how *normal classes* work in PHP. stdClass is only created internally when casting one type into an object type. Therefore it has special properties that regular classes don't.

> IMHO, this is better for mistypeing... for example:

what is better for mistyping is writing direct methods to access values. Or properly documenting your code and setting things up in your views so an IDE or static analysis can read into what is going on.

There are perfectly manageable alternatives that lead to a much better code-base overall than throwing errors over nothing internally. Asking for a non-existent property can happen a lot depending on the codebase and how it is engineered. Throwing an exception is over-stating the problem.

**Comment by sebastiandedeyne** [comment]
> Do you have another built in class that does this?

All class instances throw an `Undefined property` notice when you try to access something that doesn't exist, or are we talking about something else here?

**Comment by tomaspekar** [comment]
`class Post {}
$post = new Post();
echo $post->title;`
Every php class trhow `Undefined property`, except Eloquent :) because magic `__get()` method

**Comment by Garbee** [comment]
Oh yea. Sorry got confused with another language.

But whatever, it's eloquent and how it works. Still not a good idea to go changing to throwing exceptions. There being plenty of methods to work around the problem still exist, you just need to work at it (which with Eloquent you need to end up doing a lot of.)

**Comment by abumostafa** [comment]
i think it's Eloquent's responsibility from the beginning not to hide the Errors then let the consumers  find a way to catch it. when i wrote this issue i spend almost hours to find a ```typo```

**Comment by drbyte** [comment]
I imagine that a test-driven-development workflow would catch such typos.
https://course.testdrivenlaravel.com

I suppose you could also extend Eloquent and override the magic __get to serve your needs.

**Comment by JaydenJames** [comment]
As @michaeldyrynda said, you have to consider [accessors](https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor) and [relations and dynamic attributes](https://laravel.com/docs/5.5/eloquent-relationships#relationship-methods-vs-dynamic-properties) which are not real properties in the model itself. How do you want to handle those scenarios?

An i agree totally with @drbyte, if you're spending hours to find that the whole problem was a typo, you should improve your testing strategies instead of blaming eloquent.

**Comment by tomaspekar** [comment]
I think, that catch typo in test is too late. Also tried to override getAttribute($key) method, but no idea, because sometimes returns null is needed value.

```
public function getAttribute($key){
        $result = parent::getAttribute($key);
        if ($result === null)
            throw new \ErrorException("Undefined property");      
        return $result;
    }
```

**Comment by mfn** [comment]
I don't think this will ever change. IMHO it's simply not the philosophy how Eloquent works.

And: I'm actually glad. Having worked with CakePHP2 which did this introspection and cached it was always a small additional pain when removing columns in production.

My best advice:
- use https://github.com/barryvdh/laravel-ide-helper to generate attribute metadata on the models
- use a smart IDE or static code analyzer (PHPStorm and phpstan come to my mind) which can work with the metadata have inspection/error reporting when it doesn't work
- write tests

On a code base with 50k LOC app and 155k LOC tests code I don't remember having this miss-type problems ever.

I always let the IDE autocomplete it anyway thanks to the package and I always make sure all vars are properly type declared or at least hinted.

**Comment by tomaspekar** [comment]
Ok thanks, I will use ide-helper in PHPStorm.
Also I will try this Trait [https://github.com/tomaspekar/GetAttribute/blob/master/GetAttribute.php](url)

**Comment by chamby** [comment]
I have asked for this before as well: https://github.com/laravel/framework/issues/10382

**Comment by crynobone** [comment]
You guys are asking an ActiveRecord ORM to behave as DataMapper ORM.

**Comment by jpleau** [comment]
> You guys are asking an ActiveRecord ORM to behave as DataMapper ORM.

Rails' ActiveRecord gets this right. 

`my_model.naem` will give me an error.

Why can't Eloquent do it?

**Comment by abumostafa** [comment]
@jpleau I think people have different opinions. I stopped using Laravel because it's magic.

**Comment by philipborbon** [comment]
An answer in Stack Overflow question has a solution for this. [Laravel - Make throw exception when trying to access attribute which is not in select](https://stackoverflow.com/questions/34737019/laravel-make-throw-exception-when-trying-to-access-attribute-which-is-not-in-s)
`"In Laravel 5.0 it should be enough to overwrite getAttribute method in Eloquent model:"`
```
public function getAttribute($key)
{
    $inAttributes = array_key_exists($key, $this->attributes);
    if ($inAttributes || $this->hasGetMutator($key))
    {
        return $this->getAttributeValue($key);
    }

    if (array_key_exists($key, $this->relations))
    {
        return $this->relations[$key];
    }

    if (method_exists($this, $key))
    {
        return $this->getRelationshipFromMethod($key);
    }

    throw new \Exception;
}
```
