### ISSUE TITLE
some very usefull helpers which i use a lot in my projects

### ISSUE THREAD

**Issue by amirniknami** [laravel/internals#613]
if(!function_exists('check'))
    {
        function check()
        {
          return  app(AuthFactory::class)->check();
        }
    }

    if(!function_exists('guest'))
    {
        function guest()
        {
          return  app(AuthFactory::class)->guest();
        }
    }

    if(!function_exists('user'))
    {
        function user($data=null)
        {
          if($data===null){
            return new User;
          }
          else if(is_array($data)){
            return new User($data);
          }
          else{
            return User::findorFail($data);
          }
        }
    }

**Comment by byCedric** [comment]
Those looks really useful! But I don't think it would be wise to add them to Laravel itself. Mainly because of these reasons.

1. Both `check()` and `guest()` methods are direct methods from the Guard/Factory class. And, currently, there is already a [helper](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L146) to fetch class instance itself. So basically you can replace both `check()` and `guest()` with `auth()->check()` and `auth()->guest()`.

2. I'm not really sure what the use case for the `user()` method would be. For an empty `user()` call you can simply use `new User` too. Same with filling it with data, just use `new User($data)` _(where `$data` is an array)_. The fallback to `findOrFail` is something I'm not a fan of, random objects are now being passed to that method too. Also you should use a capital `O` in `findOrFail` to avoid Unix issues with [case-sensitive actions](https://www.washington.edu/computing/unix/commandcase.html).

**Comment by amirniknami** [comment]
thanks a lot
