### ISSUE TITLE
[Proposal] Better splitting of read / write connections

### ISSUE THREAD

**Issue by spencerr-carimus** [laravel/internals#713]
See this issue for context: https://github.com/laravel/framework/issues/19641

What I had noticed is that Laravel will make both a write and a read connection even when preparing to run a select statement that will only use the read connection.  I think this is unnecessary overhead, both on Laravel's part and for the master DB node that needs to handle the excess, erroneous connection.

Moreover, I'd also like to ask if a feature could be added as part of this fix.

One issue we encountered when trying to implement the read/write split is that you do have to take into account replication lag, at least when you are saving an eloquent model or writing something, and then trying to immediately read back what was just written.  In such a case, it would be ideal if Laravel had a config value like so (in `config/database.php`):

```
'connections' => [
    'mysql' => [
        'read' => env('DB_READ_HOST'),
        'write' => env('DB_HOST'),
        'lag' => 25,
        ...
    ]
] 
```

Where `lag` specifies the number of milliseconds that Laravel will wait to use a read-only connection after a write statement has been executed.  In our Amazon Aurora cluster, typically our replica lag maximum is ~20 ms.  Not very high, but again it is enough to cause an error when you're trying to fetch a model for a record that was just inserted.

Thanks!

**Comment by laurencei** [comment]
Why would you fetch a model that was just inserted? You already have the model - and the insert returns the `id` - so you've got the "whole" thing already?

**Comment by sisve** [comment]
This is required because there's database logic involved, usually default values specified at the database level. You need to fetch the model again to get these values and the fetch the actual persisted data.

**Comment by spencerr-carimus** [comment]
@laurencei In addition to what @sisve mentioned, another case where this causes issues is when you're syncing associations on a model and you then want to re-fetch those associated models.

**Comment by laurencei** [comment]
Ok - fair enough.

I can see the fix for separate read/write connections to be fairly easy. But I dont see an obvious way to introduce the 'lag' concept?

Plus thinking outloud - for atomic level type stuff - it would need to apply to all connections after every write?

i.e. if User A writes to the database, and User B tries to access all records 10ms later - should that include the lagged result (therefore reading from master), or is it acceptable for User A's result not to be there (reading from slave)?

**Comment by laurencei** [comment]
Ok - fair enough.

I can see the fix for separate read/write connections to be fairly easy. But I dont see an obvious way to introduce the 'lag' concept.

The only idea I can think of is the framework could connect to the "read" connection anytime it does a read. But if it "writes" to the database, then any subsequent read is also from the write database for the remainder of that request lifecycle.

That should solve it?

**Comment by spencerr-carimus** [comment]
I think the lag concept would just apply to a single bootstrapped laravel process.  So it would be okay for User B to get the lagged result.  What isn't okay is for User A that just wrote something and expects to read that back to get a lagged result.

Does that make sense?  Thanks!

**Comment by laurencei** [comment]
@spencerr-carimus - yes, sorry - I re-wrote my comment.

**Comment by spencerr-carimus** [comment]
Ahh yes, I see that now.  I think that would be perfect!

**Comment by laurencei** [comment]
Ok - let me see if I can do a PR around it... I'll check out the code now...

**Comment by spencerr-carimus** [comment]
Sweet, let me know.  Thanks @laurencei !

**Comment by laurencei** [comment]
Actually - before I spend any time on it;

ping @themsaid - thoughts? You've done alot of work on DB connection stuff recently...

**Comment by sisve** [comment]
One thing I do not really understand; why the need to use two connections at the same time? I understand that the read-connection can be lots of read-only database mirrors, but once you move into writing (and transactions), then you need to use the writable connection. Why would you move back to the read-only connection after you initiated at write/transaction?

The original issue seems to be that the write-connection was opened eagerly instead of lazily, and it seems reasonable to wait as long as possible before opening it. But it does not make sense, in my mind, to move back to the read-only connection and expect any kind of up-to-date data there. The readonly replicas are usually implementing eventual consistency; your data will be there in the future, you just do not know when.

A lag parameter is built around assumptions on how long it will take to replicate your data from the main database to the replicas, and that varies on load, io, network- and server goblins, and other things that are hard to quantify. Hardcoding a value that _probably_ work sounds like an odd solution.

**Comment by laurencei** [comment]
>  but once you move into writing (and transactions), then you need to use the writable connection. Why would you move back to the read-only connection after you initiated at write/transaction?

@sisve - I completely agree. That is what I was trying to say above.

I think the answer is to open a read connection initially. If a write action is performed, the connection is swapped to the write and stays there for the rest of the request cycle.

That would seem logical, and should be relatively easy to code?

**Comment by laurencei** [comment]
@spencerr-carimus @sisve - I've done a PR.

Have a look and we can take the discussion there.

**Comment by laurencei** [comment]
@spencerr-carimus @sisve 

This has been merged. It is now configurable in 5.5 👍 

This ticket should now be closed.

**Comment by spencerr-carimus** [comment]
Thanks @laurencei!  Much appreciated.

**Comment by nerdo** [comment]
I realize this thread is closed, but I want to chime in.

I definitely understand the problem and have ran into replication issues, but this solution doesn't address intent. It can undermine the very benefit to having a read/write connection. And worse of all, it can lead to nondeterministic behavior, introducing performance issues.

Consider, for example, an application that writes an audit log to the database. In that application,  the audit log happens to write first, followed by an expensive read operation *that has nothing to do with the audit log write*. With the current solution, the expensive read will take place on the write connection, but it shouldn't.

What we really need is a way to tell Laravel that our intentions for operations like the write, immediate read, are for it to read from the write connection. Although it implies something slightly different, a database transaction already implies this behavior.

If we need a separate construct to be able to accomplish this outside of a database transaction, a similar construct should be created. Otherwise, a database transaction already reads from the write connection and should be used as the solution.

**Comment by mfn** [comment]
In reply to https://github.com/laravel/internals/issues/713#issuecomment-320048398 : 
>> Why would you fetch a model that was just inserted? You already have the model - and the insert returns the id - so you've got the "whole" thing already?

> This is required because there's database logic involved, usually default values specified at the database level. You need to fetch the model again to get these values and the fetch the actual persisted data.

For the most basic cases, and in my case the majority if not exclusive cases, we defined the `$attributes` property on every model required to mimic the default relations value.

Doesn't help with more complex cases (trigger generating varying values?) but so far this worked well for us.

**Comment by nerdo** [comment]
There are definitely use cases for reading data from a database after a write, but I think this approach is flawed. See my comment on the pull request for an explanation:

https://github.com/laravel/framework/pull/20445
