### ISSUE TITLE
[Proposal] Default laravel log file should be splitted into separate files by date, e.g YYYYMMDD.log

### ISSUE THREAD

**Issue by ajcastro** [laravel/internals#765]
This make the laravel log files easier to read in a text editor like sublime, because the current laravel.log tooks more time to read and sometimes hang in other editors because the log file becomes so big.

Also consider, that it might be better if we also separate logs with different level, e.g. `YYYYMMDD.info.log`, `YYYYMMDD.debug.log`, `YYYYMMDD.error.log`, `YYYYMMDD.warning.log`.

**Comment by dinhquochan** [comment]
Great Idea, currently, only `laravel.log` in `logs` directory and sometime `laravel.log` has big size. It's so cool if has many files with level and date, e.g: `YYYYMMDD.info.log`, `YYYYMMDD.debug.log`, `YYYYMMDD.error.log`, `YYYYMMDD.warning.log`.

**Comment by aik099** [comment]
In other words you're suggesting to change default for `app.log` config setting (see https://github.com/laravel/laravel/blob/master/config/app.php#L124) from `single` to `daily`.

Not sure that changing the default would help much, because it's already possible to change that config setting via `APP_LOG` setting in the `.env` file.

**Comment by ajcastro** [comment]
Oh... Maybe the `daily` option can do the job for this,. am I right?

**Comment by michaeldyrynda** [comment]
You can swap in your own custom logger if your want to separate out the log levels to different files, but I wouldn't expect there to be any debug entries in production and error/warning would be minimal so you wouldn't need to separate them out.

If you need more granularity, there are better options for logging (logstash, for example)

**Comment by jacurtis** [comment]
I was going to suggest that this is really best handled by one of the myriad of error logging services out there (I'll let you research and compare them on your own). These services are built to better manage and sort through log files.

I think on production a single file is generally better because if you let your app run for a year without clearing out that file you could have 365 log files in there.  But these error management services can add layers of additional features to better handle errors when they happen or sort through past errors.
