### ISSUE TITLE
documentation example on default values with {locale} a bit confusing

### ISSUE THREAD

**Issue by deathkillz** [laravel/internals#810]
I was implementing the new laraqvel 5.5 'default value' to make my project use {locale} param in urls like:

mysite.tld/en/section
mysite.tld/nl/section

i followed this:
https://laravel.com/docs/5.5/urls#default-values

there it says:
> You may wish to call this method from a __route middleware__ so that you have access to the current request

and __route middleware__ links to:
https://laravel.com/docs/5.5/middleware#assigning-middleware-to-routes

where it says:
> By default, the $routeMiddleware property of this class contains entries for the middleware included with Laravel. 
> To add your own, simply append it to this list and assign it a key of your choosing

so when adding it to $routeMiddleware and then adding the middelware to the routes itself initially seems to work very well.
Im using auth scaffolding so to add the middelware to the auth routes i copied them to my web.php routes file.
and all was still fine.

However, it does break in one instance and that is when the login session has expired and internally the path to login redirect gets called... or in this case, the path to: {locale}/login

```
Illuminate \ Routing \ Exceptions \ UrlGenerationException
Missing required parameters for [Route: login] [URI: {locale}/login].
```

after some investigation a better way would be to just add the middelware as first entry in: $middlewareGroups.

Not sure if this should be pointed out more clearly in the docs but i asked this question on laracasts and it became a very long thread before anyone was able to figure out why this error popped up and how to fix it.

so when someone asked me why i had done it like this in the first place i replied that this was basically how the docs suggested to implement it.

so he suggested i should create a report here.

so here i am.

**Comment by 36864** [comment]
Just to clarify, the error occurs because there is a call to `route()` made in a middleware in the default 'web' group (using laravel's built-in Auth), which is called before any middleware you define in route files.

Possible solutions: 
Change the docs to clarify that defaults need to be set before any potential call to `route()`;
Change the way defaults are handled to ensure any call to `route()` will find the defaults;
Change the order in which middleware is called, so route- or group-specific middleware runs before more general middleware;
Make defaults "lazy" or provide a static fallback value for defaults so a call to `route()` before the defaults are set doesn't cause an exception. Lazy loading defaults would probably imply finishing the middleware stack execution even if a redirect is triggered, which might not be desirable.

**Comment by Dylan-DPC** [comment]
You can make a PR to laravel/docs repo.

**Comment by Dylan-DPC** [comment]
@deathkillz do you still want to pursue this proposal ? else you can close the issue

**Comment by deathkillz** [comment]
ok,
posted it to laravel/docs 
thx
