### ISSUE TITLE
New Validation rule: Forbidden

### ISSUE THREAD

**Issue by ElMatella** [laravel/internals#84]
Hi, I think that a small new validation rule named `forbidden` could be useful: 
### Use case

When updating a $user model for example, and that updating the username is forbidden for some reason. Using a `forbidden` validation rule would make this code work without taking the risk of a user updating his username:

```
$this->validate($request,[
    'username' => 'forbidden',
    'email' => 'required',
]);

$user->update($request->all())
```

The implementation would be simple:

```
/**
 * Validate that a required attribute is NOT present.
 *
 * @param  string  $attribute
 * @param  mixed   $value
 * @return bool
 */
protected function validateForbidden($attribute,$value)
{
    if(!is_null($value)) {
        return false;
    }
    return true;
}
```

What do you think about it?

**Comment by lindyhopchris** [comment]
This is a good idea, but isn't it more that the `username` attribute is allowed but it's not allowed to be different from the current value? I.e. if `username` is currently `foo@example.com` then the data is valid if `foo@examplie.com` is submitted, or invalid if it is different. I.e. the `username` attribute is *immutable*.

I have a lot of situations in APIs where I have immutable attributes on existing models. At the moment I use the `in` rule to validate them... i.e. I'd use `in:foo@example.com` as the validation rule. However, this is fragile because it means the existing value cannot have a `,` in it, as that will change the meaning of the `in` rule.

Maybe an `immutable` (or some other name) rule is required which uses the form `immutable:current_value`? Either instead of `forbidden` or in addition to it?

**Comment by themsaid** [comment]
hmmm, I wonder if it's reasonable to throw a Validation Exception when attempting to make a forbidden action rather than an Authorisation Exception, or just neglect.

I usually use `Request::only()` to pass only the fillable attributes, that way I'm 100% sure that only these attributes shall be altered.

**Comment by pedrommone** [comment]
Maybe it can be useful in PUT requests where some values cannot be changed, ie: id.

**Comment by michaeldyrynda** [comment]
Would you not either ignore the key you don't want to update, or mark it as not fillable? You're going to be returning some error to the user in either case.

**Comment by lindyhopchris** [comment]
For an API that is being consumed by third-parties over which you have no control over what they are submitting at you, my preference would always be to return a specific message if their request attempts to change something that is immutable. It seems that validation is the right point at which to do this, mostly because the validation messages will be keyed to the correct part in the request JSON that holds the immutable value - i.e. you can clearly identify the value to the client that is immutable.

The problem with mass assignment exceptions is how do you key it back to the client? The immutable key might be at `data.attributes.username` in the client's request, but your model knows it as `username` and is not aware of how its `username` attribute is represented in JSON if your serialization layer is separated.

**Comment by themsaid** [comment]
Looking at twitter for example, it ignores keys that are immutable and non-existing keys. In the documentation it shows mutable keys only, when you send any extra keys it just ignores. Maybe in a different use case showing an error might be useful, I personally just ignore extras.

**Comment by pedrommone** [comment]
As you can see here https://issues.oasis-open.org/browse/CAMP-34 when you want to receive a PUT request, everything thats immutable should return an error.

In my opinion, that's a good idea and should be implemented.

**Comment by ElMatella** [comment]
Reading all your comments also makes me think that an immutable validation rule would be better than a forbidden validation rule. I never contributed to any open source project so I am going to try to make my first pull request as soon as I can for that.

**Comment by Decadence** [comment]
https://github.com/laravel/internals/issues/203

**Comment by yagomassiah** [comment]
So any thoughts on this? why it was closed? I wanted to return an error when someone tried to update a column it shouldn't :(

**Comment by ollieread** [comment]
> For an API that is being consumed by third-parties over which you have no control over what they are submitting at you, my preference would always be to return a specific message if their request attempts to change something that is immutable.

It shouldn't matter what they provide. You should only accept what you accept. If you're blindly passing in `$request->all()` the issue is not validation, it's the code.

**Comment by ollieread** [comment]
> So any thoughts on this? why it was closed? I wanted to return an error when someone tried to update a column it shouldn't :(

Easy.

    $input = $request->all(['first_name', 'last_name', 'email', 'password']);
	if (count($request->all()) > count($input)) {
		// return error here
	}

Or better yet, just use the first line and ignore any junk data.

**Comment by lherreranetlink** [comment]
@ollieread  Don't like your solution :( it makes the code looks dirty. I still think it would be more sophisticated to have some kind of immutable validation in the Request class and in the controller just pass `$request->all()` in order to maintain the controller clean.

**Comment by ollieread** [comment]
You shouldn't be just throwing all input into something. Use the only method in requests to retrieve only the data allowed. 

Adding extra things to the core so that you can just throw all user input at something is less than ideal. Generally speaking, the all method on request should be avoided.

**Comment by lindyhopchris** [comment]
@ollieread don't totally agree with that for APIs, as I think sometimes it's useful for an API to return a message saying a field is not recognised.

however, the new rule objects makes that pretty straightforward to implement, so agree that this probably doesn't need to be added to core. Anyone who does want to implement a forbidden style rule can write their own rule object.

**Comment by ollieread** [comment]
It should be the case even more so with Apis. 

While I understand why you may want to return an error if an extra field is provided, I'm not sure this is the solution. Why is this field not updateable? Is it permission based? If that's the case, you'll want to return a permission error that would better handled in your own code. If it's simply a field that can't be updated, then you'll want to just ignore it, otherwise you're going to want to implemenr similar functionality for any fields provided that aren't part of the model, otherwise you're going to blindly pass through a whole bunch of data.

If I submit an extra 50 fields that aren't part of the model it won't be caught by the validator and your use of all will pass through the values to whatever code you have after the validator.

**Comment by lindyhopchris** [comment]
> It should be the case even more so with Apis.

My point is that it's the choice for the API's design, rather than generalising to say it should never be done.

**Comment by ollieread** [comment]
I didn't say that it should never be done, just that it should be avoided. In my comment above I listed some reasons as to why you'd want to avoid it.

**Comment by ameenross** [comment]
I wonder why this was closed... people put time into exploring this idea and describing it. It's a feature, and even though people can think of a billion workarounds for not having this (simple) feature, it still remains a feature. Time will tell whether people will find it useful. This discussion has taken longer than it would take to implement.

I think it's perfectly valid to have a `$request->only()` with all model properties in your controller. Then in the case where a normal user (not an admin) updates his profile, you have slightly stricter validation. For example, you disallow changing the email address. Very easily done with *not* having the email field in your form, except for when someone tries to spoof it. Then you could easily block that by putting `email => "forbidden"` in your validation class for non-admin users.

I think controllers are more about plumbing, and validation is more about security, so the seems to be the right place to do it.

**Comment by ameenross** [comment]
https://gist.github.com/ameenross/c96191e46f60e2ae68dd48523cc3c409

**Comment by ollieread** [comment]
Unfortunately @ameenross, validation is about data validation and has very little to do with security. Any link between the two would be purely coincidental.

If you don't want a field provided, do not request that field from the request object, it's as simple as that.

The example that you have posted doesn't actually change anything. You'd require some extra logic to determine whether or the user is an admin user and remove the `forbidden` rule if that is the case. You'd also need some view logic, I assume, to hide the form field.

**Comment by ameenross** [comment]
If it's about my security I'm prepared to use any tool at my disposal, even if its primary function is not to protect me. My usecase is perfectly valid and that way a lot more pleasant to implement than in the controller action. I really don't understand the opposition.

> You'd also need some view logic, I assume, to hide the form field.
You don't have to *assume* that if you read my comment completely, because I described that.

**Comment by ollieread** [comment]
Either way, this issue was closed largely due to the impracticality and lack of usefulness of the rule. It promotes lazy coding habits.

Also, just as a side note, the particular issue you raised is only regarded security because you suggested introducing a new feature to the framework to make up for a security vulnerability you introduced.

**Comment by donnysim** [comment]
It would also tie the validation package with auth package so this is better left in userland.

**Comment by ameenross** [comment]
@ollieread I know you have a vested interest in making Laravel look good, but I feel you're being disingenuous here.

> this issue was closed largely due to the impracticality and lack of usefulness of the rule

That's subjective. Multiple people already chimed in here who disagree with you.

> It promotes lazy coding habits.

You're saying that like it's a bad thing, while [it's actually a virtue](http://threevirtues.com/). And if I wasn't lazy, I wouldn't be using a framework.

> a security vulnerability you introduced into your own code

I did not introduce a security vulnerability. I was talking about a hypothetical situation. FWIW, I have a concrete situation which is a little different, but where the `forbidden` rule is also pleasant to have. I'm not going to go into specifics, but you made a misjudgment.

> 'if' clutter in validation

Finally, a valid counter-argument. It's just that you need that if statement anyway, and IMO having it in the controller action is unpleasant. I *would* just omit the property from the validation array, but Laravel is written to accept any *extra* submitted information that is not handled by the controller anyway. I don't know, that *might* be a feature, although I can't think of an immediate use-case, but in that case it could be complemented very nicely by the explicit `forbidden` rule.

**Comment by ollieread** [comment]
@ameenross I'm not sure what you mean regarding my point about making laravel look good. I use laravel but I frequently complain about the internals.

Anyway, my point was that every use case mentioned in this entire thread is easily solved by other, simpler methods. 

There are no reasons for needing a validation rule that fails if a value is provided when you had to actually retrieve the value yourself. You're basically saying "please write some code that will prevent the code that I very specifically wrote, from doing what I wrote it to do".

If you don't want a user to be able to update a field, do not provide a form field and do not grab that value from the request. Do not blindly throw it at the model hoping that they've followed your rules. Write proper code, don't be lazy, and absolutely do not demand others do something to fix potential security issues that you very intentionally wrote yourself.

What you want, are schemas. You want to validate the schema, not the data.

**Comment by ameenross** [comment]
> I'm not sure what you mean regarding my point about making laravel look good.

I was trying to rationalize your opinion. Apparently it still doesn't make sense to me.

> This discussion has taken longer than it would take to implement

I'll leave it at that.

**Comment by ollieread** [comment]
It absolutely has taken longer to discuss than it would have done to implement. This would however, promote some seriously bad and lazy coding habits, habits that have already found ground in that some of you think it's okay to just throw all at a request.

The rule makes no logical sense, that's all there is to it. If you disagree, you're wrong.

**Comment by thannaske** [comment]
> If you disagree, you're wrong.
No matter if this idea is logical or not: Discussion skills 10 out of 10.

**Comment by ollieread** [comment]
@thannaske after the entire discussion that has happened here, if people are still arguing that this is a good idea they're wrong. My discussion abilities are irrelevant, I tried explaining many ways and many times.

**Comment by donnysim** [comment]
I'd personally say that instead of validator checking if it is allowed, you could move the logic to a policy e.g. (just an example, not proper impl.):

```php
$data = $this->validate(...); // using usual rules
$model->fill($data);
authorize('update', $model);

// update policy

if ($auth->cannot('update.title') && $model->isDirty('title')) {
    return false;
}
```

At least it does not tie it to validation as it's really not validating anything. Other than that I'd try to avoid throwing errors on "not allowed to update" fields, but rather ignoring them, especially for APIs as it can break many applications because someone figured to change field permission and that leaves an unhappy developer/client. Imagine translating an article, you took half an hour and during that time someone pushed and update that disallows adding an author - suddenly the user cannot save anymore, have to refresh the page and loose all the work because it throws an exception.
