### ISSUE TITLE
Expand Integrated test package to include testing javascript

### ISSUE THREAD

**Issue by marcusmoore** [laravel/internals#87]
> Laravel developers can already easily test their APIs and it would be awesome to allow them to easily test the JS apps that consumes those APIs as well.

I think a good "next step" to encouraging developers to test their apps while making it as easy as possible is to re-implement the javascript testing functionality that was in the original [Integrated](https://github.com/laracasts/Integrated) package. I'm not exactly sure how to approach this but if it is deemed a good idea and we start a discussion about it I'm sure we can collaborate on something.

Moving the code to it's own repository as mentioned in #4 would be a good first step I think.

**Comment by Modelizer** [comment]
That's why we build this [Selenium](https://github.com/modelizer/selenium) package. Most of the JS work has been taken into consideration but you can point out what else you expect to see? Also, I will be glad to see new features coming up :+1: 

In near future, I'm also planning to give support for BDD with Selenium testing. But need some more review and feedback whether it would be a great idea or not? :thinking: 

ping @chrispecoraro

**Comment by marcusmoore** [comment]
Hey @Modelizer, I completely forgot that I created this issue and I'm actual following your Selenium package. I haven't had the chance to use it yet unfortunately but thank you for the work you're putting into it.

I'm going to close this since it seems like the community will take care of this outside of the core.
