### ISSUE TITLE
[Proposal] Blade @foreach should accept not only array and Countable but also Traversable

### ISSUE THREAD

**Issue by mpyw** [laravel/internals#892]
https://github.com/illuminate/view/blob/498c86e971b7f9057b2c9ce416c5cc74fe3f12bc/Concerns/ManagesLoops.php#L25

It seems that `@foreach` only accepts `array` and `Countable`. However, iteration could be done even if we don't know its length. `Traversable` such as `Iterator`, `IteratorAggregate` and `Generator` are popular interfaces. I think it should be supported.

**Comment by paulofreitas** [comment]
You're and always was allowed to use a `Traversable` in `@foreach`. 👍 

The `Illuminate\View\Concerns\ManageLoops` class is related to the [Loop variable](https://laravel.com/docs/5.5/blade#the-loop-variable) feature. The highlighted line of code is just checking if the traversable is countable so that it could set `$loop->remaining` and `$loop->last` accordingly. 😉

**Comment by sisve** [comment]
The linked line is only meant for calculating the `$loop->count` (and thus `$loop->remaining` and `$loop->last`) which cannot be done on an Traversable (without traversing it twice, which may have side effects).

Can you provide an example of something that should work, but isn't working?

**Comment by mpyw** [comment]
I'm very sorry, that was my stupid mistake. My `getIterator()` implementation was:

```php
return new \ArrayIterator($collectionOrArray);
```

But it should be

```php
return $collectionOrArray instanceof \Traversable ? $collectionOrArray : new \ArrayIterator($collectionOrArray);
```
