### ISSUE TITLE
[Proposal] Add __toString() in query builder

### ISSUE THREAD

**Issue by ajcastro** [laravel/internals#894]
So that you can easily `echo` or  `die()` a query:
```
die($query); 
echo $query;
```

**Comment by Dylan-DPC** [comment]
`toSql()` isn't enough?

**Comment by ajcastro** [comment]
It is shorter to code especially when debugging queries.

**Comment by sisve** [comment]
I'm against this. This change wouldn't be just a short debugging thing, it would also give the query builder the capability to be implicitly casted to a string, just to save a few keypresses for a scenario that would never end up in production code.

Can we even guarantee an implementation of __toString that never throws exceptions?

**Comment by brayniverse** [comment]
A developer runs the risk of accidentally printing out a database query. At least without `__toString()` an exception would be thrown if they unintentionally return a database query instead of the result.

As @Dylan-DPC pointed out, you can use `toSql()` which is better (in my opinion) because you are explicitly requesting the SQL query.

**Comment by ajcastro** [comment]
Yeah you have the point guys. Thanks for pointing that out!
