### ISSUE TITLE
[Proposal] DataMapper ORM

### ISSUE THREAD

**Issue by DevPlus31** [laravel/internals#903]
A Datamapper ORM would be awesome.

**Comment by Kyslik** [comment]
Have you played with Eloquent already?

**Comment by DevPlus31** [comment]
Yes. but Eloquent is Active Record Implementation. 
With Data Mapper I meant something like Doctrine.

**Comment by crynobone** [comment]
I don't think Laravel ever going to have both data mapper and active record build by the core team. Should probably focus on finding external package and integrate it with Laravel.

**Comment by brayniverse** [comment]
I've never used it but I have seen a doctrine package for Laravel that looked well maintained.

**Comment by DevPlus31** [comment]
@brayniverse  Yes but I think official Support would be better.

**Comment by DevPlus31** [comment]
@crynobone  That's what I'm doing for now.

**Comment by Dylan-DPC** [comment]
Laravel is flexible enough for you to use another ORM incase you don't like to use Eloquent.

**Comment by sisve** [comment]
The other mentioned package is available at https://www.laraveldoctrine.org/

I think it would be hard to include two totally different database layers into the framework. Beginners will have a hard time keeping them apart, and we'll start seeing support questions asking what differs between them.

**Comment by aftabnaveed** [comment]
@Dylan-DPC I think you can't separate Eloquent from Laravel.

**Comment by aftabnaveed** [comment]
@mfn Sorry for not being clear,  I understand that Eloquent can be used independently, but looks like it is the core part of the Laravel Framework making it hard to remove its dependency from it.

**Comment by aftabnaveed** [comment]
We love the core request, response, middleware, routing, service providers and the IOC containers part of the framework.  Because Eloquent is most of the time magic it was not something which we could rely on for our enterprise application, therefore, we replaced Eloquent with Doctrine thanks to these guys 
 https://www.laraveldoctrine.org/

In my opinion, Laravel is a combination of awesome tools and libraries, but Eloquent is not something which is not best suited for enterprise applications. In order for Laravel to compete with other frameworks such as Symfony, Django, Flask and ROR it needs to support DataMapper ORM such as Doctrine.  Its always better to have options.

I am not suggesting to make it part of the core but at least make it part of the supported family of libraries such as Laravel Passport and Laravel Socialite.

**Comment by ollieread** [comment]
I think a better approach to this would be to have Eloquent as its own package rather than part of the DB package. I've tried to fully remove Eloquent to no avail. In the end, I just ended up replacing it.
