### ISSUE TITLE
[Proposal] Pass the results total to the closure given to DB/Model::chunk

### ISSUE THREAD

**Issue by marcelopm** [laravel/internals#912]
It would be great to have access to the results total from the closure given to DB/Model::chunk, for debugging purpose, figuring out progress, etc.

https://laravel.com/docs/5.5/eloquent#chunking-results

https://github.com/marcelopm/framework/commit/81aae3b373e6cc64f3d2594de85aa09046d15bd0

**Comment by sisve** [comment]
You already have this value by calling `$results->count()` in the callback yourself.

**Comment by marcelopm** [comment]
Unfortunately, that doesn't seem to be true.

i.e consider the following test:

`
var_dump(Model::count()); // equals to 2 - number of rows on DB
Model::chunk(1, function ($models, $page, $total) {
   var_dump($models->count()); // equals to 1 - the size of the  collection - chunk piece
   var_dump($page); // equals to 1 and after 2
   var_dump($total); // equals to 2 - number of rows on DB
});
`

**Comment by sisve** [comment]
The $countResults isn't supposed to contain the total number, it's supposed to contain the number in the chunk. That's why the loop exists when $countResults differs from the page size, it means we've hit the last chunk.

https://github.com/marcelopm/framework/blob/81aae3b373e6cc64f3d2594de85aa09046d15bd0/src/Illuminate/Database/Concerns/BuildsQueries.php#L24-L46

**Comment by marcelopm** [comment]
Yeah, you're right, I created false assumptions without proper understanding the code.
As far as I can see this is not possible without first running the given query as a count query, which seems unlike to happen. Thanks for your time.
