### ISSUE TITLE
Inconsistencies in how eloquent updates records

### ISSUE THREAD

**Issue by yurtesen** [laravel/internals#93]
I have 2 tables, 'users' and 'activation_tokens', each user can have 1 token. So User model has

```
    public function ActivationToken()
    {
        return $this->hasOne(ActivationToken::class);
    }
```

For example:

`$user->ActivationToken->update(['token' => $this->getNewTokenString()])`-> uses model//instance/fillablable from Eloquent\Model

$user->ActivationToken->updateOrCreate(['token' => $this->getNewTokenString()])` -> uses model/instance/fillable from Database\Eloquent\Builder

`$user->ActivationToken()->update(['token' => $this->getNewTokenString()])` -> uses query builder
from Relations\HasOneOrMany DOES NOT use fillable

`$user->ActivationToken()->updateOrCreate(['token' => $this->getNewTokenString()])` -> uses instance/fillable from Relations\HasOneOrMany

I find this somewhat inconsistent. What do you think?

**Comment by lagbox** [comment]
Its not inconsistent, and this was already explained why.

**Comment by lagbox** [comment]
Reference laravel/framework#13568

**Comment by yurtesen** [comment]
From 4 different ways to do the same thing, 3 of them behave similarly and 1 disregard the fillable setting.

Why these 2 should function totally differently? (besides one should create a row if it doesnt exist)
`$user->ActivationToken()->updateOrCreate(['token' => $this->getNewTokenString()])`
`$user->ActivationToken()->update(['token' => $this->getNewTokenString()]) `

The explanation in the reference you gave was that update() in this case do not work on model/instance.(well that is more or less stating the obvious).  

It makes no sense to just say what it does (uses query builder) as an answer. Because that is the problem itself, it is not a real answer or explanation. The explanation would be explnaining why one of these uses instance/fillable and other one is using query builder and it is not explanined in the reference you provided.

**Comment by lagbox** [comment]
They are not doing the same thing as pointed out already. Im sorry you can't grasp the difference.

**Comment by yurtesen** [comment]
@lagbox I think you do not understand what is inconsisten behavior. Your answer is simply stating the obvious and the problem itself. I just told that they are not doing the same thing(=working similarly) and it is inconsistent. You tell me as an answer, they are not doing the same thing. How can you think anybody to accept that as problem solved/explained? We all know this is how it works right now. It does not mean that it is correct behavior.

The only difference between those 2 calls should be that one of them should fail if the row does not exist. Otherwise they should function identically.

Because they are called exactly the same way and one is an Update function and the other one is UpdateOrCreate function. Do you understand now that the problem is that they are not working similarly when they should be? 

If you want to contribute a real answer, please explain why they shouldn't be doing the same thing when called exactly the same way? I am trying to reason with you. But you do not make an explanation of why this is happening, just keep saying this is how it works. (which is obviously inconsistent)

**Comment by JamesGuthrie** [comment]
@yurtesen your proposal is essentially to add an `update()` method to the `HasOne` relation. This would allow `$user->ActivationToken()->update([...])` to use the actual model referenced in the relation, hence using the `fillable` method on update.

There are a couple of issues here: 

Firstly there would then be an inconsistency when dealing with `HasMany` relations. Assuming that a user has multiple roles, what would you expect `$user->roles()->update(...)` to do? It would not be able to use the assumption that there is only one model behind the relation which is meant to be updated. You would have to figure out the semantics of these different cases before being able to deal with the inconsistencies that you claim.

Second, using `updateOrCreate()` as a reference for consistency is not very helpful either. `updateOrCreate()` does some "weird magic" which I wouldn't (personally) want to rely on. For instance calling `updateOrCreate()` on a `HasMany` relation without providing all of the required attributes will result in the first that matches (but not all that match) being updated, or (if none matches) the creation failing because you would be missing some model attributes.

**Comment by lagbox** [comment]
>Because they are called exactly the same way and one is an Update function and the other one is UpdateOrCreate function.
>... why they shouldn't be doing the same thing when called exactly the same way?

They are not called in the same exact way. They have different signatures.

`Eloquent\Builder`, `Relation\HasOneOrMany`, etc ...
```php
/**
 * Create or update a related record matching the attributes, and fill it with values.
 * @return \Illuminate\Database\Eloquent\Model
 */
public function updateOrCreate(array $attributes, array $values = [])

/**
 * Perform an update on all the related models.
 * @return int
 */
public function update(array $values)
```
`updateOrCreate` (Create or update a related record, singular). It is a convenience method that returns a model as that is what it is doing the update on, a model, which is why 'fillable' applies. It is for a singular entity.

`update` only takes ... values. It is for updating ALL.

They don't look the same to me nor are their descriptions the same.

>The explanation would be explnaining why one of these uses **instance/fillable** and other one is using query builder and it is not explanined in the reference you provided.

Hmm, well I did already => The part about the efficiency of a single UPDATE query compared to having to select the records, hydrate models, then spin through them, fill them (which is where fillable comes in) and then save them, is part of the explanation of why. As this is for mass updating based upon the method description (Perform an update on ALL). It also lets you update any fields you want just like a query would. This is a flexible method. I don't see any reason to add extra queries (1 SELECT to get them and then 1 UPDATE per model) to accomplish what 1 UPDATE query can do.

>The only difference between those 2 calls should be that one of them should fail if the row does not exist. Otherwise they should function identically.

Neither of these are **dependent** upon existing records at all. `updateOrCreate` will create one, if there isn't a match. `update` will just ... update nothing as its a DB update statement.

"Function identically" - as you asked "What do you think?" I think it should not. One deals with a single entity, the other deals with many. One returns a model, one does not. One can 'create' a record the other can only 'update' records. To have these be even close to the same functionality you will have to reference the explanation above about selecting models and hydrating them etc ... They are for 2 different purposes as based upon the description of the methods.

>I am trying to reason with you. But you do not make an explanation of why this is happening, just keep saying this is how it works. (which is obviously inconsistent)

The entire explanation from the previous issue was to explain "why this is happening" ("is happening" means an observed effect [result], not theory or reasoning of why something was built how it was). To explain why "this is happening" you have to know how it works as it was designed and built to work this way.

Perhaps you mean to ask, "Why was this designed and built to function this way"? That is partially explained above. But I did not build this, you would have to ask the creators for their exact reasoning, anyone else can only give you their best educated assertion and try to provide reasoning for it, as I have.

If none of this is sufficient then you will have to wait for @taylorotwell or another member of the internals team.

My opinion, since you asked for it ("What do you think?"), is that this should not change. Fillable should not come into play as there is no model being filled with that `update` call. That is my opinion. This isn't an argument, you are asking for what people think. If you don't like the explanation then it is what it is.

In the previous issue I already explained why your assertion of a bug existing was incorrect. In this one where you ask "What do you think?" you have exactly what I think now and the reasoning. That is all anyone can provide as you are asking what people think.

**Comment by yurtesen** [comment]
@JamesGuthrie  updateorCreate() checks if a record matching valid values exist. But it updates the record using the user id (at least in my case). Therefore it would update all the records belonging to user, not the first match.

I expected the update() to do something like this also:

**Comment by yurtesen** [comment]
@JamesGuthrie  Yes, you are right, the naming scheme is not the best perhaps. I guess they should have named it something like updateRandomRecordOrCreateNew()   :)    but you can get update() to update all the records while still checking the fillable for a single model which is the basis of all records which will be updated. No?

@lagbox  You are right, there is a difference, update() records all records, but this does not mean that it can't check fillables. Why can't it do something like this?

```
    public function update(array $attributes)
    {
        if ($this->related->usesTimestamps()) {
            $attributes[$this->relatedUpdatedAt()] = $this->related->freshTimestampString();
        }
        $this->query->getModel()->fill($attributes);
        return $this->query->update($attributes);
    }
```

Sure, some wasted instructions.. but at least it would conform to mass-assignment rules.?

In either case, I give up... the way this whole thing is working is kind of strange and well maybe it is best to let it be...
