### ISSUE TITLE
[5.2.x] When Gate::getPolicyFor() the before method is not called

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/internals#97]
when calling the `Gate::getPolicyFor(MyEntity::class)` method one would assume that the `before()` method would be invoked as well. Although this is not the case:

Real world example:

```
$gate->getPolicyFor(Job::class)->create($request->user(), $organisation);
```

Im assuming to make this operate I would have to actually do something like the following: 

```
$policy = $gate->getPolicyFor(Job::class);

return $policy->before($request->user()) && $policy->create($request->user(), $organisation);
```

Yuck...? 

**What is gained from not being explicit? It could be so much simpler**

e.g. `$gate->authorize(MyEntity::class, 'create', $argument)`

OR

`$gate->policy(MyPolicy::class)->authorize('create', $argument)`

**Comment by JosephSilber** [comment]
Automatically calling the before method is part of the magic you're trying to avoid.

You either embrace the magic or you don't. If you don't like magic, there's no 'yuck' in explicitly calling the before method.

**Comment by andrewmclagan** [comment]
I'm more pointing to how the policy classes are resolved through inspection of the first parameter:

`$gate->allows('update', [$post, $team]);`

Sure, the above resolves the `Post` entity policy class.

Although consider the following:

`$gate->allows('create', $team);`

On the surface it would seem the developer want to create a `Team` entity. Although they may actually want to create a `Post` entity and simply need to pass along the Team to check it the user is authorized to create Posts for that team?

**Comment by lsalazarm99** [comment]
I totally agree with @andrewmclagan. A case I faced today is that I wanted to authenticate a user to read user information (only his information, not others' information). In order to do so, I created a policy `view` that received **a user ID** and checked if the authenticated user ID matches the passed user ID (obtained from a parameter in the request).

But that didn't work. Since I'm just using `$user->can('view', $userId)` I guess Laravel has no way to determine what policy I'm referring to (it checks the class of the parameter I'm passing in order to find the associated policy) so it just thinks it's a gate, and since it doesn't exist as a gate, it assumes the user is authorized.

A workaround? Associate a gate with a single policy method using `Gate::define('view-user', [UserPolicy::class, 'view'])`. That way, it executes the `before` method too.

It would be nice if we could specify the policy we want to use. Something like `$user->can('view', $userId, UserPolicy::class)`.
